### ISSUE TITLE
 Map.set: Wierd behavior when the first argument is an array

### ISSUE THREAD

**Issue by shanSyapse** [facebook/immutable-js#1002]
Using Immutable@3.8.1, we accidentally passed in an array to Map.set, and see the inconsistent behavior as described in the following code:

```
var state = Immutable.fromJS({
  rootKey: {
    keyA: ['valueA']
  }
})
 state = state.set(['rootKey'], Immutable.Map()) // proper way is to use .set('rootKey')
console.log(state.toJS().rootKey) // empty object {}
console.log(state.get('rootKey')) // { keyA: ['valueA'] }
```

This creates mysterious bug and hard to debug.
We would expect either
1. an error/warning message when the the first argument of set is an array
Or
2. state.toJS().rootKey is the same as state.get('rootKey')

**Comment by leebyron** [comment]
Immutable collections allow for any kind of value as a key, not just strings. Your application may expect the proper way is to use strings, but other applications use these collections in other ways. It would be inappropriate to limit the usefulness of the library.

However `toJS()` only works as expected when you are using keys which convert to strings soundly. It sounds like part of the issue is that you are relying on `toJS` and converting Arrays to strings results in comma separated values of their children.

I strongly suggest using Flow or Typescript to catch these sorts of mistakes.
