### ISSUE TITLE
Map#setIn overwrites nested Maps when key in keyPath is a Number

### ISSUE THREAD

**Issue by horyd** [facebook/immutable-js#1008]
### What happened

When using `Map#setIn` and passing a `keyPath` that includes a numeric key, Immutable does not see that the key already exists and over-writes the `Map` at that `key`.

### How to reproduce

You can see this reproduced [here](https://jsbin.com/zarolikuqu/3/edit?html,js,console)

**Comment by dmitrif** [comment]
+1

**Comment by dmitrif** [comment]
@horyd Have you found a workaround for now?

**Comment by horyd** [comment]
I just made sure that whenever I was passing an integer through to `setIn` I made sure it was sent as a String instead :P

**Comment by leebyron** [comment]
This is expected albeit confusing behavior by JavaScript. 

The issue is:

```
{
  11: {
      name: 'some error'
  }
}
```

This looks like `11` would be a number property on Object, but Objects can *only* have string properties, so JavaScript first converts `11` to `"11"` and then sets a property with a string that happens to have numeric characters.

Collection types like the ones Immutable.js provides (and the native Map and Set collections) allow for all kinds of types as keys or entries, not just strings.

You can use Map with numeric keys, but you just can't create it from a javascript object which itself enforces string keys, instead would have to use a sequence of [k,v] tuples. For example:

```js
Map([ 
  [ 11, Map({ 
    name: 'some error'
  }) ] 
])
```
