### ISSUE TITLE
Map.merge with meantime changes but equal result return new instance of map

### ISSUE THREAD

**Issue by nexinto-gmbh** [facebook/immutable-js#1017]
Merging two different, but equal maps, result in the original map.
That's ok and expected.

`var x = IM.Map().set(1,2)`
`var z = IM.Map().set(1,2)`
`//to be true`
`x.merge(z) === x`

Merging maps, wich changes the orignal map meantime, but equals at the end results a new map.
That is unexpected.

`var x = IM.Map().set(1,2)`
`var y = IM.Map().set(1,3)`
`var z = IM.Map().set(1,2)`
`//should be true`
`x.merge(y,z) === x`
`//result is equal => true`
`x.merge(y,z).equals(x)`

The problems are MakeRef and SetRef. SetRef is irreversible when used once, so merging back to the original value dosn't reuse the original map.

Exists workarounds for this problem?

**Comment by philpl** [comment]
I wouldn't consider this something you can bet on. Strictly speaking an operation on a persistent data structure should always yield a new instance. The refs are an attempt to optimise the performance. It tries to find out whether the value has actually changed. Now finding out whether the value has changed after two merges is actually an expensive operation.

Since the partials you are passing are merged separately, in-order, after the merge, there's no way comparing the changed values efficiently. I don't think this is something that should be worked around either.

In this case you're changing a value like this: `2 => 3 => 2`. Immutable.js shouldn't try to be slower to optimise this case, and this should really be something that you should take care of, if you really care about optimising this case. ;)

**Comment by leebyron** [comment]
Great answer by @philpl 

Returning the same reference for "no-ops" is a performance optimization and so only occurs in cases where it can be done performantly.

One work around is the following:

```js
x.merge(y.merge(z))
```
