### ISSUE TITLE
Immutable.setIn doesn't account for shared object referencing from multiple parents.

### ISSUE THREAD

**Issue by Glidias** [facebook/immutable-js#1023]
I sort of expected this would happen. Is this normal? 

I just wished Immutable.setIn(...) was intelligent enough to keep track of cases where multiple parents reference the same object reference within the map tree, and update it along multiple paths up multiple parent chains. Unfortunately, this isn't the case.

http://jsfiddle.net/xryk992o/1/

**Comment by philpl** [comment]
This won't be expected behaviour as it goes against how persistent data structures work.

There's two problems with the example you provided; The first one is that `fromJS` just goes through an object or array recursively and converts it to an Immutable.js structure. This means that `d` will be already duplicated to begin with.

The second problem is that even if `d` in your structure would be the same shared Map, it would not update when `setIn` is called on one of its paths.

Consider what happens when you update a value in a persistent Map:

It will get the value at the specified key, then change that data, then set it on the Map, yielding a new instance of Map. Even though that `d` Map is shared, `setIn` will go down your path, it will create a new Map, then it will update the parent Maps. At no point does it know about the shared value. This happens because it's persisted, so we are not actually mutating it in-place.

**Comment by leebyron** [comment]
Great answer by @philpl

**Comment by stavalfi** [comment]
Is there another library that takes care of shared objects?

**Comment by leebyron** [comment]
@stavalfi if you need shared objects I would recommend using plain JS objects and arrays, using utilities like lodash if necessary. “Shared” objects implies mutability, defeating much of the purpose of keeping values immutable

**Comment by stavalfi** [comment]
no mutability here. I use redux to maintain graph changes and I tried to find a library which can update the graph by creating a new graph. 

How lodash can help me out here?
