### ISSUE TITLE
Typings for Map.toObject()

### ISSUE THREAD

**Issue by sir-marc** [facebook/immutable-js#1054]
If i write something like this:
```
interface SomeInterface {
  prop: any
}


const map = Immutable.Map<SomeInterface>({
  prop: 'hi'
})
```

and later want to convert it back using:
`const obj = map.toObject();`

My typescript IDE says that `obj` is of type `{ [index: string]: SomeInterface }` but why isn't it of type `SomeInterface` ? Am I getting something wrong or do I use `Map` the wrong way?

**Comment by leebyron** [comment]
`Map` typically takes two type arguments, the type of the keys and the type of the values: `Map<KeyType, ValueType>`, however since it's really common to use strings as keys, `Map<ValueType>` is also allowed, the type argument `ValueType` refers to what type you expect every value in the Map to be. Your example likely doesn't type check, but what would type check is:

```js
interface SomeInterface {
  prop: any
}

const map = Immutable.Map<SomeInterface>({
 someKey: { prop: 'hi' },
 someOtherKey: { prop: 'hello' }
})
```

A key detail is that `Map`, much like `Array`, is a *collection* type where every value in the collection is expected to be the same type. If you are looking for each value to be a different type depending on the key, you might be interested in `Immutable.Record`
