### ISSUE TITLE
Map.update is broken?

### ISSUE THREAD

**Issue by benny-medflyt** [facebook/immutable-js#1061]
Immutable version 3.8.1

I must be doing something seriously wrong, or have missed something fundamental:

```
$ node
> var Immutable = require('immutable');
> var m = Immutable.Map();
> m.size
0
> m = m.update(42, "hello", (x => x));
Map {}
> m.size
0
```

Why wasn't "hello" inserted into the map? According to the [docs](https://facebook.github.io/immutable-js/docs/#/Map/update), update is:

> Equivalent to: map.set(key, updater(map.get(key, notSetValue))).

Let's try running that instead:

```
> m = m.set(42, (x => x)(m.get(42, "hello")))
Map { 42: "hello" }
> m.size
1
```

That seemed to work just fine! So why didn't "update" work?

**Comment by tolmasky** [comment]
I've  investigated this a bit. The problem seems to be:

1. On [line 784](https://github.com/facebook/immutable-js/blob/master/src/Map.js#L784), it checks whether the new value is the same as the existing value. If it is, it considers no need to do anything. In this case, the existing value is the not-set-value. So it SHOULD still do something because the not-set isn't there yet.
2. On [line 98]( https://github.com/facebook/immutable-js/blob/master/src/Map.js#L98) if no value is set, it returns undefined. It should just return itself.

**Comment by leebyron** [comment]
This is an edge case to how `update` works with identity functions and default values.

See documentation discussion: http://facebook.github.io/immutable-js/docs/#/Map/updateIn

> If the updater function returns the same value it was called with, then no change will occur. This is still true if notSetValue is provided.

@tolmasky thanks for investigating, I added some additional tests for this case and unfortunately I think the changes you made would have broken them

**Comment by benny-medflyt** [comment]
If the current behavior is what is intended, then I must say it is very surprising.

I see that something is indeed mentioned under "updateIn", but the documentation for [Map.update](http://facebook.github.io/immutable-js/docs/#/Map/update) does not mention this. It should be mentioned there as well, and the line saying that update is

> Equivalent to: map.set(key, updater(map.get(key, notSetValue))).

should be removed, since it's clearly not true.

Thank you

**Comment by leebyron** [comment]
I agree this corner isn't a great one. I'm hoping to improve it in a future major version. In the meantime these are great documentation suggestions
