### ISSUE TITLE
Request: Convenience methods for mean & sum

### ISSUE THREAD

**Issue by schmod** [facebook/immutable-js#1063]
I would like to propose adding convenience methods for computing the mean and sums of numeric values in an `Iterable`:

* `mean()`
* `meanBy()`
* `sum()`
* `sumBy()`

While a similar proposal was rejected in #636 on the basis that same result could be accomplished via `.reduce()`, we already have similar convenience methods for `.min()`, `.max()`, and `.count()`, and the same argument could be made about those.

If there are no objections, I would be happy to propose an implementation in a PR.

**Comment by leebyron** [comment]
Unfortunately I will still suggest that we do not do this.

Every method added has cost: more bytes for a compiled Immutable.js bundle means longer to download. More code means longer startup time in a browser or vm. And cognitive load is important to consider as well. Already one of Immutable.js's common complaints is that the API is relatively large and can take some effort to learn. Adding more methods makes this problem worse.

We only want to add methods when they add a unique capability that aligns to the goal of the library (programming with immutable data) and are non-trivial to implement (methods which take advantage of the inner workings of the data structures). Unfortunately `mean` and `sum` really do not meet these criteria. Honestly I believe it was a mistake on my part to have allowed `min` and `max` to be added as well, and could consider removing them in a future major release.

Immutable.js collections all implement the ES2015 Iterable protocol which was an intentional decision to make it easier to build general purpose versions of the types of methods you're suggesting. Then they could benefit from 1) not being bundled directly with Immutable.js and 2) work equally well with Immutable.js and native collections.
