### ISSUE TITLE
Pathological Behavior without Merkel Trees?

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#1065]
So, I have a React app where everything is an Immutable object, rooted in the same place. I am thus using I.is() to know whether a tag needs re-rendering. However, it appears that you may end up with SUM(1 ...N) comparisons, where N = level of change to the tree. So for example, if you had something like:

````
A -> B -> C -> D -> E
   \ -> F -> G
````

A is the root of the tree, it splits off into two branches. Let's assume I change E to H. As such, that entire spine must become new as such:

````
A' -> B' -> C' -> D' -> H
   \ -> F -> G
````

So, if I had my react app:

````
<root A = { A }>

root's render:
   <B B = { B } />
   <F F = { F } />

etc.
````

In the componentShouldUpdate, it is doing a I.is() for each of the attributes. Initially, I.is(A, A'), This requires traversing every node, since you won't get a difference until E != H. The left node is easy, I.is(F, F) returns and no render is needed. HOWEVER, I.is(B, B') must retraverse nearly the entire spine (4 comparisons: B == B', C == C', D == D', E !== H). This causes a re-render, and thus now next tag I.is(C, C'), which is 3 comparions. And so forth. You end up with SUM(Level(change)) comparisons.

If we implemented a lazy Merkel hash on each node, the first comparison would of course requires 5 comparisons (all the way down until it found the difference), but then the next time through merkel !== merkel and we'd be done.

**Comment by leebyron** [comment]
I would strongly recommend against using value based equality checking (`Immutable.is(a, b)`) within shouldComponentUpdate and instead use reference identity based equality checking (`a === b`). 

That's because you're doing a expensive computation (equality check) to determine if you can skip doing a expensive computation (re-render). If the equality check is slow itself, then you haven't really gained anything. However reference identity is extremely cheap and is perfectly suited for use in `shouldComponentUpdate` when using with React.

The issue with computing Merkel-style hashes per node when doing equality checking is that you may convert a one-pass equality algorithm into a two-pass equality algorithm, first computing and comparing hashes, and then if equal comparing data structures as well to avoid collisions. An important difference from a Merkel-tree is that Immutable data structures are designed to live in memory and operate efficiently for general purpose use, so they do not use cryptographically secure hashes.
