### ISSUE TITLE
Seq.reduce.map.reduce executes out of order

### ISSUE THREAD

**Issue by felipeochoa** [facebook/immutable-js#1071]
In the following:
```
const s = [1, 2, 3];
Immutable.Seq(s).reverse().map(e => (console.log(e), e * 2)).reverse().toArray();
```
I expected the log to output 3, 2, 1 and the result of the call to be [2, 4, 6]. The result is correct, but the two reverses apparently cancel each other out.

I realize such are the perils of side-effects, but did not see any warnings about `Seq` expecting commutative transformations.

**Note**: I realize in this case I can just swap the second `reverse` and the `toArray` to get the desired ordering, but I still think this is a bug

**Comment by leebyron** [comment]
This is actually a feature! `Seq` is a lazy collection and does not produce intermediate representations. Because of this, the order in which data is read results in the order in which the prior functions are called. Since the Sequence was reversed twice before being consumed, it is consumed in it's original order.

**Comment by leebyron** [comment]
If it's important that intermediate transforms like `map()` are called in a particular order, you'll need to ensure you convert the lazy Seq back into a real data structure (like an array) before calling it.

**Comment by felipeochoa** [comment]
Well, it's not immediately apparent (to me at least) that this is due to laziness; though I guess that depends on your definition of "intermediate representation". To me I thought the chained calls were doing something like the following:

```
Immutable.Seq -> Sequence based on array s
.reverse() -> Sequence based on array s; iterating from the back
.map() -> Sequence based on array s; iterating from back; applying lambda
.reverse() -> Sequence based on array s; iterating from back; applying lambda; reversing
.toArray -> make it happen
```

In other words, I thought Seq as a sort thunk aggregator.

**Comment by leebyron** [comment]
Intermediate representations in this context refers to an actual data structure which holds the results of the previous operation. For example, if you use `Array` instead of `Seq` and call the same sequence of operations, you'll produce new intermediate representation Array data structures after each operation which will culminate in a final data structure. With `Seq` there are no intermediate representations, and what you say is correct that `Seq` is essentially planning a sequence of operations which is only executes lazily when necessary.

For example, consider this similar example which uses `reverse()` and `map()` but rather than calling `toArray()`, just accesses a single value with `get(2)`:

```js
const s = ['A', 'B', 'C'];
const result = Immutable.Seq(s)
  .reverse()
  .map(ch => (console.log(ch), ch.toLowerCase()))
  .reverse()
  .get(2);
// console.log: 'C'
// result: 'c'
```

Because `Seq` is lazy, the `map()` operation only applies to the one value requested, so `console.log` is only called once. Similar code with eager `Array` will console.log all three values.

This might illuminate what's happening when we "reify" the lazy sequence into a real data structure. `toArray()` is essentially calling `get(0)`, `get(1)`,  ... `get(seq.length - 1)` to produce all the items in the returned `Array` data structure, each access triggering only the transformation operations necessary to produce that specific value, and in aggregate triggering all those necessary to produce and return the `Array`.

**Comment by felipeochoa** [comment]
I understand the principle, but I guess I had assumed `Seq` would materialize intermediate views to respect the order of chained methods. I think the current behavior is non-intuitive and should perhaps throw when it hits this problem (as a point of comparison, in Python `reversed` requires a materialized sequence and will throw if given an iterator)

At any rate, the behavior of `reverse` is inconsistent with that of `sort`, as the following example shows:

```js
Immutable.Seq.of([2, 'a'], [3, 'b'], [2, 'c'], [3, 'd'], [1, 'd'])
  .map((x, i) => (console.log('first:', x.join(',')), x.concat(i)))
  // Sort by first element; break ties by moving later element first
  .sort(([a1, _, a2], [b1, __, b2]) => (a1 - b1) || -(a2 - b2))
  .map(cs => (console.log('second:', cs.slice(0, 2).join(',')), cs.slice(0, 2)).join(','))
  .toArray();

/*
first: 2,a 
first: 3,b 
first: 2,c 
first: 3,d 
first: 1,d 
second: 1,d 
second: 2,c 
second: 2,a 
second: 3,d 
second: 3,b
*/
// Returns: [ "1,d", "2,c", "2,a", "3,d", "3,b" ]
```
