### ISSUE TITLE
.has(-1) shouldn't error

### ISSUE THREAD

**Issue by tmcw** [facebook/immutable-js#113]
This seems like it should either be specified in documentation that the key given to `has` must be positive, or it should return `false`: http://mistakes.io/#bb5a86b8372adc8a8479

**Comment by xixixao** [comment]
I'd like to point out that this is a horrible behavior! (imo) Coming from CoffeeScript the fact that its ranges go both ways and so does iteration always caused me pain (and I don't think I have used it as a feature once). Having has(-1) return true is extremely counter intuitive. I guess this boils down to the fact that having an index and wanting to know whether it is valid happens more frequently than the situation where I want to know whether index is valid or it is a negative index which is valid... Adding another method which is strict will pollute the API and keeping it this way will lead to hard to debug/surprising errors down the line. Just my 2 cents.

P.S.: 1. Although people asked for negative indexing, this was rejected for performance reasons mainly in CS)
2. Although I think negative indexing is evil, has(-1) is much worse (especially since has is polymorphic over all Iterables including Maps).

**Comment by leebyron** [comment]
Good feedback, @xixixao. Something to consider for future versions.
