### ISSUE TITLE
Map: Is it a Function or Class?

### ISSUE THREAD

**Issue by papercuptech** [facebook/immutable-js#1162]
Both the ES6 source and `immutable.js.flow` declare `Map` as a class, and presumably sub-class-able.

However `immutable.d.ts` declares it as a module/function/interface, preventing sub-classing from it.

I'm using TS, and would like to sub-class Map.

Is Map not meant to be sub-class-able, or is the TS declaration incorrect?

**Comment by dsm0880** [comment]
I looking to do the same as @papercuptech. Sub-classing is my biggest issue with Immutable.js. We had to implement Records everywhere to get typing information but I could still not sub-class from a parent record. 


```javascript
const parentRecord = Record {a:1,b:2}
class Parent extends parentRecord{
a:number;
b:number;
constructor(a:number,b:number){
    super(
        {a:a,b:b}
    )
  }
}
```

Now I want to extend this Parent class:

```javascript
const childRecord = Record {c:1,d:2}
class ChildClass extends Parent{
c:number;
d:number;
constructor(a:number,b:number,c:number,d:number){
    super(
        {a:a,
        b:b,
        c:c,
        d:d
      }
    )
  }
}
```

This obviously doesn't work but you can see what I'm getting at. Given it appears you are refactoring all this new code for Typescript what do you recommend moving forward for developers who want to use an immutable type but need to create a class hierarchy and get dot notation intellisense.

**Comment by leebyron** [comment]
Immutable.js doesn't support subclassing of Maps, Lists, and other collection types. The type constructors are functions (they don't need be called with `new`). The TS declarations are correct, the flow definitions are incorrect in this particular way but using the class definition made other desirable behaviors work with the flow checker.

Records can be sub-classed as a means of adding additional methods to the prototype, however subclasses cannot add new fields to the Record store and cannot perform work in a constructor (since every "mutation" results in the construction of a new Record). I typically recommend against subclassing Records and instead favor general purpose functions which accept the records as arguments - this approach is easier to type check, easier to scale in a codebase, and is more performant at runtime.

**Comment by leebyron** [comment]
Part of the confusion is the source text which was written before ES6/ES2015 was finished. It is using a non-compliant class transform which converts back to a prototypal function constructor

**Comment by dsm0880** [comment]
@leebyron Got it. I just want to give my thoughts on this if that's OK. I believe I understand (I may not) that we have separate programming styles here with functional and object oriented. Although libraries such as this one have revealed an alternate reality to me which is we instead work on spectrum and you can incorporate each style into your code. With that being said I personally don't see the value of Immutable.js as a functional programming library (you may not either) but instead an awesome library that prevents me from passing all my objects by reference and tearing out all my hair :) I may be missing the point but that is the beauty I see here. This is why I get confused by your answer because to me I'm inches away from reducing massive amounts of my typescript code if I could inherit class properties while maintaining immutability. Now you may say that last sentence is impossible given the inherent mutation that I'm asking for but then you have to ask yourself what do developers like myself do? Is the answer to code in a functional style? Maybe but I believe the unexpected popularity of your Records type as you noted in your 2016 road map document is likely due to a number of the reasons I pointed out above.

**Comment by papercuptech** [comment]
@leebyron 
>I typically recommend against subclassing [Thing] and instead favor general purpose functions which accept the [things] as arguments

Looking at Immutable-js source, it seems to be organized by kinds of things (Collection, Map, Set, etc.) hierarchically related, as indicated by the names of files and their contents, and then within by explicit class declarations, and in some cases with several levels of derivation, almost exactly precisely like what is called an "Object Oriented" organization. Why does Immutable get to do the very thing you recommend against?

>this approach is easier to type check, easier to scale in a codebase, and is more performant at runtime.

Can you provide a link to research that shows this to be more than hyperbole or anecdotal?

...as it implies, given this interface:
```typescript
interface IThing {
  attribute: string
  useAttribute: () => string
}
```

...that this:
```typescript
class Thing implements IThing {
  attribute: string
  useAttribute() {return this.attribute + ' used'}
}

const thing = new Thing()
thing.a = 'Hello'
const used = thing.useAttribute()
```

is somehow harder to type check, prevents organizing many functions over a shared structure, and performs materially slower than:

```typescript
function useAttribute(thing: IThing) {
  return thing.a + ' used'
}

const thing: IThing = {}
thing.a = 'Hello'
const used = useAttribute(thing)
```
TS at least, easily type checks both, and provides mechanisms to 'scale' code for a type across files (namespaces). With JIT optimizations, practically speaking, there's no difference in call overhead. This seems, on the face of it, to fly counter to your claim.

I've often experienced, in projects using the later approach, that they regularly don't explicitly define `IThing` (and all the related IOtherThings), and instead encourage the inherent schema of the graph of data for the particular problem domain, be implicit within how function's operate on the graph. This usually comes along with lots of type-related functions spread across disparate files. All this makes it quite a bit easier to end up with code harder to maintain (i.e. for others to grok and change), and can inhibit useful tooling features like intellisense and type checking. 

@dsm0880 The implementation of Record is rather straight forward and small. We copied and tweaked to provide a typed Immutable Record (Model) to fit our needs. Along with a decorator, we get to use like so:
```typescript
class Model {
  //plagiarized and tweaked Record

  changed: Model = this
  hasChanged() {return this !== this.changed}
}

function property(prototype: object, name: string) {
  Object.defineProperty(object, name) {
    get: function() {return this.changed.get(name)}
    set: function(v) {this.changed = this.changed.set(name, v)}
  }
}

class Thing extends Model {
  @property firstName: string
  @property lastName: string
  @property title = 'Unknown'
 
  constructor(firstName: string, lastName: string, title?: string) {
    this.firstName = firstName
    this.lastName = lastName
    this.title = title || this.title
  }
}

let thing = new Thing('john', 'doe')
thing.firstName = 'Does this'
thing.lastName = 'Work?'

if(thing.hasChanged()) 
  thing = thing.changed
  //;i.e. can be used to 'change' a thing in a redux action,
  //but only update the store in the companion reducer (by
  //the reducer returning thing.changed); its a handy optimization
