### ISSUE TITLE
Large power-of-2 hashCode fails

### ISSUE THREAD

**Issue by garrettm** [facebook/immutable-js#1176]
Using Immutable js 3.8.1 and 4.0.0-rc2

### What happened
`Set([1, 2, 3, 4, 5, 6, 7, 8, new A(), new B()])`

results in:
RangeError: Maximum call stack size exceeded

### How to reproduce
```
class A {
  equals() { return false }
  hashCode() { return 0 }
}

class B {
  equals() { return false }
  hashCode() { return 2 ** 32 }
}

const test = I.Set([1, 2, 3, 4, 5, 6, 7, 8, new A(), new B()])
```

Constructing this set infinitely recurses--I would expect it to work.

Pull request with failing test: https://github.com/facebook/immutable-js/pull/1175

**Comment by garrettm** [comment]
This problem only appears in collections that are larger than 9 elements.  `[new A(), new B()]` does not cause this.

**Comment by myitcv** [comment]
@garrettm to add some details from my analysis using maps:

* It seems that for small map sizes, the `hashCode` method of a key is _not_ being used; instead `equals` is used. Above a certain size (and I've not looked into the code) `hashCode` is then used. This would seem to be a serious problem, and appears consistent with your analysis @garrettm (for me the trigger point is a map of size 8). `hashCode` should, if I understand the docs correctly, always be used if it exists
* I'm also seeing an issue with the [`Immutable.hash` function](https://facebook.github.io/immutable-js/docs/#/hash) but I will raise that separately because it's orthogonal to this thread

**Comment by myitcv** [comment]
@leebyron any thoughts here?

**Comment by myitcv** [comment]
Ping @leebyron - any thoughts on this given rc4 has just been released?

Specifically, the first bullet in [my last comment](https://github.com/facebook/immutable-js/issues/1176#issuecomment-287000974)

**Comment by philipp-spiess** [comment]
@myitcv You can find a response from @leebyron at the attached PR here: https://github.com/facebook/immutable-js/pull/1175#issuecomment-333024492

Regarding your first bullet: Immutable.js is using a non-hashed array map for small maps (the size of `8` is correct here). I found this discussion to that topic: https://github.com/facebook/immutable-js/issues/19 if you're, like me, curious why 😊

**Comment by myitcv** [comment]
@philipp-spiess thanks for the links. It's specifically the small maps that I'm interested in (hence this discussion could/should probably be moved to another issue).

Quite what backing data structure is used behind the scenes another topic; it's key equality I'm concerned with.

Consider the following Typescript:

```typescript
describe("Immutable hashCode bug", () => {
	it("shows", () => {

		let m = Immutable.Map<O, number>();

		for (let i = 0; i < 20; i++) {
			console.info(">> round", i);
			let k = new O(i);
			m = m.set(k, i);
		}

		expect(m.count()).toBe(20);
	});
});

class O {
	private v: number;

	constructor(i: number) {
		this.v = i;
	}

	equals(v: O): boolean {
		console.info("equals");
		return this.v === v.v;
	}

	hashCode(): number {
		console.info("hashCode");
		return this.v;
	}
}
```

This gives the output:

```
INFO: '>> round', 0
INFO: '>> round', 1
INFO: 'equals'
INFO: '>> round', 2
INFO: 'equals'
INFO: 'equals'
INFO: '>> round', 3
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: '>> round', 4
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: '>> round', 5
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: '>> round', 6
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: '>> round', 7
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: '>> round', 8
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'equals'
INFO: 'hashCode'
INFO: 'equals'
INFO: 'hashCode'
INFO: 'hashCode'
INFO: 'hashCode'
INFO: 'hashCode'
INFO: 'hashCode'
INFO: 'hashCode'
INFO: 'hashCode'
INFO: 'hashCode'
INFO: '>> round', 9
INFO: 'hashCode'
INFO: '>> round', 10
INFO: 'hashCode'
INFO: '>> round', 11
INFO: 'hashCode'
INFO: '>> round', 12
INFO: 'hashCode'
INFO: '>> round', 13
INFO: 'hashCode'
INFO: '>> round', 14
INFO: 'hashCode'
INFO: '>> round', 15
INFO: 'hashCode'
INFO: '>> round', 16
INFO: 'hashCode'
INFO: '>> round', 17
INFO: 'hashCode'
INFO: '>> round', 18
INFO: 'hashCode'
INFO: '>> round', 19
INFO: 'hashCode'
```

My [understanding](https://facebook.github.io/immutable-js/docs/#/Map) (although the docs aren't explicit on this) was that if `.hashCode` is defined on a key it will be used (_regardless_ of the size of the map). Else `.equals` will be used if defined. Else strict identity is used.

However the output above shows that `.equals` is used for "small" maps and `.hashCode` for "large" maps. 

It's entirely possible for two keys to hash to the same value but not be `.equals` (indeed the docs call this out), which is  how I came across this case.

Unless I'm missing something?

**Comment by myitcv** [comment]
Just to be clear on what I'd be expecting for "small" maps in my test case; that the `.hashCode` values be compared for equality (`===`) rather than the use of the `.equals` method on a key.

**Comment by philipp-spiess** [comment]
@myitcv Now I understand, thank you for explaining. 

I found the code responsible for this here:

https://github.com/facebook/immutable-js/blob/9af1caebea648cba32821f3856b33d5187679487/src/Map.js#L270-L278

When a `hashCode` collision is detected, it's obvious that we've to use `equals` (this is what's happening in `HashCollisionNode` as far as I can see), but in your case you expect a test of the `hashCode` as a guard before the potentially expensive `equals` is called in any case, right?

In that case, might it be feasible to call `hashCode` in your custom `equals` implementation as a guard, or is the `hashCode` expensive as well and thus you want to avoid it unless you have to? I think this is then more a performance optimization problem and not a faulty implementation (since `equals` will always be correct, even if `hashCode` collides). 

I'm sure that fixing this to always use `hashCode` as a guard is rather easy to implement, but I'm not sure if that's worth it. It'd probably be a good idea to benchmark this first.

In any case, we should add the correct behavior to the docs to avoid confusion 😊

**Comment by myitcv** [comment]
@philipp-spiess I think the point I'm raising is more of a high level one, way before collision detection etc. How key equality is defined?

At the moment key equality is a function of the size of the map into which the key-value pair will be inserted; that seems wrong.

Because to my mind key equality is only a function of the key itself (its behaviour).

Hence I'd expect the docs/implementation to read something like:

* if a key defines `.hashCode` use that
* else if a key defines `.equals` use that
* else use strict identity

Or something to that effect, hopefully you get the idea 😄

**Comment by leebyron** [comment]
Just pushed an update to the docs which adds this code.

There is no guarantee that `.hashCode()` will be called before `.equals()` since they serve different purposes. If a collection uses hash codes to organize itself, then `.hashCode()` will be called, but if it does not (as short Lists and short Maps do not) then `.hashCode()` will not be called. During a lookup, hash codes help to find a value but `.equals()` is always called since a hash collision could have occurred.

`ValueObject` (which are hashable) must define both `.hashCode()` and `.equals()`. If an object only defines one of the two methods, then Immutable.js will fall back to strict reference equality.

**Comment by myitcv** [comment]
Thanks @leebyron - I now see where I've gone wrong here. 

Apologies for the noise @garrettm and @philipp-spiess!
