### ISSUE TITLE
Status update on 4.0.0 final release?

### ISSUE THREAD

**Issue by pbomb** [facebook/immutable-js#1215]
Hi @leebyron,

Sorry if this isn't the right place to ask for a status update on the 4.0.0 release. I'm sure there are many others who are also eagerly anticipating the release. Just curious if you have any guess on when it might be released or a list of issues you still want to close before releasing.

If this is not the right place to ask this question, feel free to close this issue.

Thanks for your hard work on this very useful library!

**Comment by hmeerlo** [comment]
Ok, so nothing happened to this repo for 2 months now, has it been abandoned? I'm really looking forward to the 4.0.0 release for better flowtype support.

**Comment by bhouser** [comment]
Even another RC release would be nice.  This issue was fixed since the last RC release:
https://github.com/facebook/immutable-js/issues/1158

Would love to have access to that.

**Comment by kdudzik** [comment]
Another two months have passed, what's the status of this project? I would also love to have another release.

**Comment by davidlygagnon** [comment]
I was also wondering when 4.0.0 major release will happen? Last commit was in March, feels like this is being abandoned ?

**Comment by oriSomething** [comment]
@davidlygagnon 
<img width="362" alt="screen shot 2017-08-16 at 21 13 10" src="https://user-images.githubusercontent.com/2685242/29378438-c2a6564e-82c7-11e7-907b-6b3455a459bc.png">

**Comment by oriSomething** [comment]
I wonder if it's a time to a fork, `io.js` style. I'm not sure. Also from legal point of view because of the `PATENTS` file.

**Comment by philipp-spiess** [comment]
@oriSomething I think David means the 4.0` work that is happening in the `master` branch. The branch `4.0-abandoned` is from 2015. 

I'd rather have the maintainers reconsider #1005 before thinking about a hard-fork.

**Comment by oriSomething** [comment]
@philipp-spiess Of course better to have more maintainers. But it seems for a long time that nothing really happens here.
Even if this stagnation called "stability" it seems that many PRs that can make daily use of this library easier end less bugs prune such as #1276 are not event get any response.
And I understand that the maintainer have no time or will which is **okay**. But it seems this project doesn't really open to new maintainers that aren't from Facebook, which makes this project stuck which is a sad thing since pretty much everywhere `Immutable.js` recommended to anyone who works with `React` event with all the buzz of "you might not need Redux and Immutable as well"

**Comment by davidlygagnon** [comment]
Yeah I was talking about master going from rc2 to final...

**Comment by skeet70** [comment]
I'd also prefer we get more maintainers. If that's impossible because additional maintainers must be Facebook affiliated, forking seems like the only real option to keep the library going. I haven't seen any communication coming out of FB / @leebyron with regards to continued maintenance on this repo.

**Comment by thomhos** [comment]
It would be nice to know if maintenance is postponed, or being looked at, etc. At least some information would be nice. I was looking forward to using the v4 in a new typescript based project. But with the inactivity and obscurity around v4 I've decided not to use immutable, even though I'd really like to.

If we have some message from maintainers we at least know what to expect.

**Comment by davidlygagnon** [comment]
Yes - Kind of feel like @thomhos about the fact that inactivity on a repo may lead me to re-think upgrading to 4-rc2...

**Comment by leebyron** [comment]
Hey all, thanks for your continued patience. I'm working on an upgrade
strategy for a final v4 release as well as looking for additional
maintainers.

This project is definitely not dead, as we're using it in many projects,
but it's certainly been in hibernation recently.

**Comment by thomhos** [comment]
Hey Lee, that's a good message. I think we're all looking forward to a general status update when you've got some more information. But just this message is a good sign already :)

Looking forward to the update for the typings!

**Comment by asazernik** [comment]
@leebyron Is this search for maintainers purely internal to Facebook, or are you also open to maintainers from the broader community.

**Comment by jonathanmarvens** [comment]
@asazernik +1. @leebyron I would love to help as a maintainer.

**Comment by leebyron** [comment]
Closing this issue since the next release is coming imminently.

For help - submitting high quality PRs fixing reported bugs, providing code review on existing PRs, and helping to answer questions and close out issues is the kind of thing I'm looking for help for.

Please feel free to just take action and ping me when a repo-owner action is needed

**Comment by steventrouble** [comment]
Hi, it's been several months since this was closed, and still no release. I'd like to re-open this issue.
