### ISSUE TITLE
Add makeRecord helper

### ISSUE THREAD

**Issue by a-x-** [facebook/immutable-js#1217]
Hey,

Every time I create Record I have to write:
`Record(obj)(obj)`

that's because I'm too lazy to define default values and duplicate keys.

`makeRecord` helper reduces my code size:
```es6
export function makeRecord (obj) {
  return Record(obj)(obj);
}
```

**Comment by alexandrebodin** [comment]
Hi @a-x- 

You should be defining your records "statically" and use them to make sure some object match predefined interfaces.

```javascript 
const someRecordInterface = new Record({
 a: 1,
 b: 2
});

const o = someRecordInterface({a: 10, b: 30, c: 40}); 
// o: {a: 10, b: 30 } 
// c is ignored

// not the same as doing 

const o1 = new Record({a: 10, b: 30, c: 40})({a: 10, b: 30, c: 40}); 
// o1: {a: 10, b: 30, c: 40}
// c will be in your record and every key of the object you pass

```

It looks to me you would be better of using a Map. (only difference is you won't be able to add extra keys with Record but you already are too flexible in my opinion) 

I hope my point was clear enough. Let me know what you think or If I missed your point and use case :)

**Comment by a-x-** [comment]
yep, current API covers many cases.
But I won't be able to add extra keys. And I don't want to create separate Record definition with default keys. 

For example, I don't know actual keys, but I want to permit extending with new keys.

Finally, Record instances have [] accessors, Map instances have only `.get()` (why?).

**Comment by alexandrebodin** [comment]
Well from what your are saying you need to use a Map. 

I believe ( @leebyron correct me if I'm wrong) that Map just cannot have accessors for the property because you wouldn't be able to enforce immutability otherwise: 

To define a property you can use `Object.definePropery` and set the `configurable` option to false  to make sure a key will not be deletable. (Which is perfect for a `Record`).

But when you have a flexible set of keys like for a `Map` and you still want immutability you need set the keys a non-configurable but then it would mean you have to change the `propertyDescriptor` to make the key `configurable` again and in order to delete it. This is to costly for the "small" benefit of using property accessor instead of get

**Comment by a-x-** [comment]
Thank you much
