### ISSUE TITLE
Unable to call hashCode() on empty Map, produces error: Cannot assign to read only property '__hash'

### ISSUE THREAD

**Issue by hanvyj** [facebook/immutable-js#1228]
### What happened

I haven't been able to find any references to this, but I'm not 100% sure it's not come up before.

I found I've had bugs with `hashCode()`, specifically an error (in Chrome):

> TypeError:  Cannot assign to read only property '__hash' of object '[object Object]'

Caused by the `hashCode` function:

    // ### Hashable Object

    hashCode: function() {
      return this.__hash || (this.__hash = hashIterable(this));
    }

The hashIterable was returning an integer, but it couldn't assign it to the __hash object. At first I thought this was an intermittent problem, but recently I think I've found a way to reproduce.

### How to reproduce

It turns out I was using an filtering down to an empty map at some point. It was a valid Map, just with a size of 0, and when hashCode was called it produced the error.

I can reproduce it with:

    let emptyMap = fromJS({});
    console.log(emptyMap.hashCode());

I don't believe this is intended behavior?

**Comment by hanvyj** [comment]
I'm also getting "TypeError: Cannot add property __hash, object is not extensible" on Records.

**Comment by leebyron** [comment]
Sorry, I can't reproduce your issue.

If you could please submit a PR with a failing test case, that would be great

**Comment by bdurrer** [comment]
I was about to open a new issue, but I think this is exactly the same problem. I strongly suggest looking in `hashCode`, as I think it is simply wrong to ever try to assign a hashCode on a theoretically immutable object.

Here is the copy of my issue text:



### What happened
When working with records in collections, Immutable sometimes tries to set an hashCode of a frozen object, resulting in an exception.
**Expected behavior:** No exception, of course. I expect hashCode to be set when creating an instance, not generated later on.

The hashCode function looks like a getter but apparently it sets it too:
```
  hashCode: function hashCode() {
    return this.__hash || (this.__hash = hashCollection(this));
  },
```



### How to reproduce

It started happening after upgrading from 4.0.0-rc.9 to 4.0.0-rc.12.
I am very sorry, but I was unable to create an example which triggers this behavior. It only occurs in a big react/redux/saga project, where the redux state is using Immutable collections and various Record types heavily.

The behavior can be reproduced in said project, it reliably appears in the same code location. However, it appears in weird places, e.g. at one point a call to `orderedMap.has(itemRecord)` throws it, somewhere else it is a `list.valueSeq()` that fails.
Furthermore, calling `orderedMap.has(itemRecord)` in some other location might not produce an error at all. It seems like it is an arcane order of things that need to happen, before the error occurs.

Anyway, here is an stacktrace, which was triggered by a seemingly simple `orderedMap.has(itemRecord)`:

In this case, `has()` triggers `hashCode()` on the Record, which is already part of the `orderedMap` and (in my understanding) should already have set the hash code.

```
immutable.es.js:5032 Uncaught TypeError: Cannot assign to read only property '__hash' of object '[object Object]'
    at List.hashCode (immutable.es.js:5032)
    at hash (immutable.es.js:775)
    at immutable.es.js:5310
    at immutable.es.js:1111
    at ArraySeq.__iterate (immutable.es.js:452)
    at FromEntriesSequence.__iterate (immutable.es.js:1105)
    at hashCollection (immutable.es.js:5303)
    at FromEntriesSequence.hashCode (immutable.es.js:5032)
    at Record.hashCode (immutable.es.js:5479)
    at hash (immutable.es.js:775)
```
