### ISSUE TITLE
v4.0.0-rc2: Record: add back keySeq

### ISSUE THREAD

**Issue by Zalastax** [facebook/immutable-js#1282]
As of https://github.com/facebook/immutable-js/pull/1135 Records are no longer collections.
This is fine when using Records explicitly but makes "reflection" difficult, i.e. how do you iterate over each key? Converting to a Seq each time seems very wasteful.
Examples of when I need this: [Zalastax/immutable-devtools@13569c7](https://github.com/Zalastax/immutable-devtools/commit/13569c72ed250b29653dd62abc73292e7224a660#diff-913f07292bcfe99fe2e859460adde5ccR53) and [Zalastax/tsdiff@29609cc](https://github.com/Zalastax/tsdiff/blob/29609cc8873ccec747b4dc008c4d4ffed941b619/src/index.ts#L83)

**Comment by leebyron** [comment]
Treating Records as collections is not an API to be encouraged, which is why these functions were removed. For special cases that need to use reflection, converting to Seq is the right decision. Similar to how you might use `Object.keys()` to reflect on a plain JS Object, rather than assuming that Object to behave like a collection in all cases.

Seq is not wasteful in a performance sense, since it only offers a lazy view over the underlying data - there is very little overhead.
