### ISSUE TITLE
Broken documentation links.

### ISSUE THREAD

**Issue by dagstuan** [facebook/immutable-js#1313]
The links on http://facebook.github.io/immutable-js/docs/ currently seem to be broken. Nothing happens when clicking the links such as `Map`, `List` etc. in the right-menu.

**Comment by robininfo-edsx** [comment]
I don't have this problem can you give you us:
* You web browser and this version
* Errors and warnings you can get from your inspector

**Comment by remhume** [comment]
Same here.
When i navigate to e.g. List it still shows the overview (with url https://facebook.github.io/immutable-js/docs/#/List )
Whee i then click again on List link, the link directs me to https://facebook.github.io/List

Screenshot of console error attached.  
Latest MacOs Sierra + Latest Chrome 61  

![screen shot 2017-09-29 at 10 52 58](https://user-images.githubusercontent.com/3317423/31008549-da35f3a0-a504-11e7-8846-a8b0324b9df3.png)

**Comment by olieidel** [comment]
+1. Also in the current Firefox Developer Edition.

**Comment by gcoderre** [comment]
All docs broken, indeed ;(

**Comment by lanescherber** [comment]
On https://facebook.github.io/immutable-js/docs/#/ using Chrome stable 61.0.3163.79:

clicking the "List" link in the right sidebar index gives the following console error:
`Uncaught Error: Unknown kind undefined
    at p (Defs.js:341)
    at Defs.js:315
    at Array.reduce (<anonymous>)
    at p (Defs.js:315)
    at Defs.js:337
    at Array.reduce (<anonymous>)
    at p (Defs.js:336)
    at i (Defs.js:268)
    at r (Defs.js:261)
    at t.render (Defs.js:52)`
and so does OrderedSet, Stack, and maybe more.

Clicking "Map" (and some other links) opens the expanded content as expected. Links that fall under "Map" are working and properly scroll the page to the relevant content. 

At one point the `href` for the links in the sidebar was set to the bare hostname `https://facebook.github.io/List` instead of `https://facebook.github.io/immutable-js/docs/#/List` but now I can't seem to replicate it.

**Comment by jhonymoncada** [comment]
+1 I have the same issue: 

`Defs.js:341 Uncaught Error: Unknown kind undefined
    at p (Defs.js:341)
    at Defs.js:315
    at Array.reduce (<anonymous>)
    at p (Defs.js:315)
    at Defs.js:337
    at Array.reduce (<anonymous>)
    at p (Defs.js:336)
    at i (Defs.js:268)
    at r (Defs.js:261)
    at t.render (Defs.js:52)`

**Comment by shanimal** [comment]
http://devdocs.io/immutable/
