### ISSUE TITLE
mapKeys and mapEntries don't provide a way to merge values after clash

### ISSUE THREAD

**Issue by RReverser** [facebook/immutable-js#1364]
### What happened

I used `mapKeys` to transform map into another and accidentally noticed that I'm losing some of the values. 

After seeing this, it makes total sense (after all, some keys can be transformed to the same one and so one value always "wins"), but at the same time it seems there is no extra parameter to specify custom merging behaviour for this cases.

Would it be possible to provide such extra callback to `mapKeys` and `mapEntries` similarly to `update(...)`, `merge*()` and other methods for cases when one wants to merge values after new keys clashed?

### How to reproduce

Contrived example:

```js
> m = Map.of(1, 'x', 2, 'y')
Map { 1: "x", 2: "y" }
> m.mapKeys(() => 1)
Map { 1: "y" }
```

**Comment by leebyron** [comment]
I'm trying to keep the API surface area constrained - I'd rather provide primitives for users to build complex behavior rather than introduce APIs for all of those complex behaviors. Over time this library will likely trim back existing methods in favor of utility libraries rather than adding to it. To make these kinds of decisions I think it's important to consider how common an operation would be - complex behavior that's very common deserves first class API support (like `getIn` or `merge`)

This is definitely an interesting case, but I'm concerned that it's not common enough to warrant the additional complexity. Especially since it might break consistency with similar methods - adding it would lead to even more change in API surface to retain consistency.

I would suggest using `reduce()` for this use, since it gives you access to the in-progress value and lets you do whatever behavior you like for this kind of collision.

For example:

```js
// mapKeys
m.mapKeys(k => fn(k))
// equivalent to this reduce() call
m.reduce((m2, v, k) => m2.set(fn(k), v), Map())
// which could handle collisions like:
m.reduce((m2, v, k) => {
  let mappedK = fn(k);
  while (m2.has(mappedK)) {
    mappedK = tryToMakeUnique(mappedK);
  }
  return m2.set(mappedK, v);
}, Map())
```

**Comment by RReverser** [comment]
> but I'm concerned that it's not common enough to warrant the additional complexity

It just seems dangerous enough to allow mapping that silently drop some items from the original dataset.

**Comment by leebyron** [comment]
Would you suggest that it throws instead? I think there are probably cases where re-mapping keys to a smaller key space is intentional - that might be tricky to support both in an easy to understand way

**Comment by RReverser** [comment]
> I think there are probably cases where re-mapping keys to a smaller key space is intentional - that might be tricky to support both in an easy to understand way

Maybe, but even in these cases it seems like one would want an explicit control over which value ends up being used (which is covered by merging suggestion), and not just to rely on an undefined Map order.

> Would you suggest that it throws instead?

If you feel that merging callback for these would unnecessarily bloat code, yeah, I think it would be better to explicitly fail, have this documented and have people also use `.reduce` as you suggested above.

**Comment by leebyron** [comment]
Cool - I'd be happy to look at a PR implementing that

**Comment by RReverser** [comment]
> I'd be happy to look at a PR implementing that

To clarify - do you mean throwing on same keys?

**Comment by leebyron** [comment]
That if a `.mapKeys()` results in mapping two unique keys to the same key that an error be thrown upon detecting that.

I'm still a little nervous about adding that though, since even checking keys during mapping will have a real performance cost
