### ISSUE TITLE
MergeIn behavior change in 4.0.0-rc.7? List is now Array?

### ISSUE THREAD

**Issue by chrisnojima** [facebook/immutable-js#1370]
Hey,

I'm attempting to upgrade to 4.0.0 and ran into this issue. Wasn't sure if this was intended or not

v3
```
>  I.Record({search: I.Map()})().mergeIn(['search'], {results: [1,2,3]}).getIn(['search', 'results'])
List [ 1, 2, 3 ]
```

now in v4
```
> I.Record({search: I.Map()})().mergeIn(['search'], {results: [1,2,3]}).getIn(['search', 'results'])
[ 1, 2, 3 ]
```

Thanks!

**Comment by leebyron** [comment]
This is an intentional change!

Check out the second bullet under the "breaking" section for https://github.com/facebook/immutable-js/releases/tag/v4.0.0-rc.5

Merge used to deeply transform its input via `fromJS` before continuing, which was limiting. That step was removed to allow for merging in any kind of value.
