### ISSUE TITLE
Using flow, calling concat on a Seq with a Map([[V, V]]) causes a type error (v4)

### ISSUE THREAD

**Issue by acusti** [facebook/immutable-js#1406]
### What happened

Not sure if this is a type bug or a deprecated API thing or something else entirely, and I don’t fully understand the original intent of this code, but here’s what I’m seeing:

```js
  var startKey = selectionState.getStartKey();
  var endKey = selectionState.getEndKey();
  var blockMap = contentState.getBlockMap();
  var newBlocks = blockMap
    .toSeq()
    .skipUntil((_, k) => k === startKey)
    .takeUntil((_, k) => k === endKey)
    .concat(Map([[endKey, blockMap.get(endKey)]]))
    .map(operation);
```

In that code block, where `startKey` and `endKey` are strings and `blockMap` is an `OrderedMap` of (subclassed) Records, flow gives this error:

```
Error: src/model/transaction/modifyBlockForContentState.js:32
                       v-------
 32:   var newBlocks = blockMap
 33:     .toSeq()
 34:     .skipUntil((_, k) => k === startKey)
 35:     .takeUntil((_, k) => k === endKey)
 36:     .concat(Map([[endKey, blockMap.get(endKey)]]))
         ---------------------------------------------^ rest parameter array of call of method `concat`. Has some incompatible type argument with
481:   concat<KC, VC>(...iters: Array<Iterable<[KC, VC]> | PlainObjInput<KC, VC>>): KeyedSeq<K | KC, V | VC>;
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type. See: node_modules/immutable/dist/immutable.js.flow:481
  Type argument `T` is incompatible:
     36:     .concat(Map([[endKey, blockMap.get(endKey)]]))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Map. This type is incompatible with
    481:   concat<KC, VC>(...iters: Array<Iterable<[KC, VC]> | PlainObjInput<KC, VC>>): KeyedSeq<K | KC, V | VC>;
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of identifier `Iterable` | type application of polymorphic type: PlainObjInput. See: node_modules/immutable/dist/immutable.js.flow:481
      Member 1:
      481:   concat<KC, VC>(...iters: Array<Iterable<[KC, VC]> | PlainObjInput<KC, VC>>): KeyedSeq<K | KC, V | VC>;
                                            ^^^^^^^^^^^^^^^^^^ type application of identifier `Iterable`. See: node_modules/immutable/dist/immutable.js.flow:481
      Error:
       37:     .map(operation);
                    ^^^^^^^^^ function type. This type is incompatible with the expected param type of
      490:     mapper: (value: V, key: K, iter: this) => M,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See: node_modules/immutable/dist/immutable.js.flow:490
        This parameter is incompatible:
           36:     .concat(Map([[endKey, blockMap.get(endKey)]]))
                                         ^^^^^^^^^^^^^^^^^^^^ undefined. This type is incompatible with
           27:   operation: (block: ContentBlock) => ContentBlock,
                                    ^^^^^^^^^^^^ ContentBlock
      Member 2:
      481:   concat<KC, VC>(...iters: Array<Iterable<[KC, VC]> | PlainObjInput<KC, VC>>): KeyedSeq<K | KC, V | VC>;
                                                                 ^^^^^^^^^^^^^^^^^^^^^ type application of polymorphic type: PlainObjInput. See: node_modules/immutable/dist/immutable.js.flow:481
      Error:
       36:     .concat(Map([[endKey, blockMap.get(endKey)]]))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Map. This type is incompatible with
       33: type PlainObjInput<K, V> = {[key: K]: V, __proto__: null};
                                                               ^^^^ null. See: node_modules/immutable/dist/immutable.js.flow:33
```

I don’t actually know what the original intent is of passing an array of tuples to `Map` inside that `concat`. From what I can tell, the result is equivalent to the result of invoking `Map({[endKey]: blockMap.get(endKey)})`; my best guess is the array version is being used to avoid having to use ES2015 computed property names. However, when I change it to:

```js
    .concat(Map({[endKey]: blockMap.get(endKey)}))
```

…the flow error goes away.

**Comment by leebyron** [comment]
I think this is a legit error, but just the signal is buried in the noise.

Here's the signal:

```
   This parameter is incompatible:
           36:     .concat(Map([[endKey, blockMap.get(endKey)]]))
                                         ^^^^^^^^^^^^^^^^^^^^ undefined. This type is incompatible with
            27:   operation: (block: ContentBlock) => ContentBlock,
                                    ^^^^^^^^^^^^ ContentBlock
```

What's happening here is the following: 

- First, concat is actually doing the right thing: `Map<K1, V1>.concat(Map<K2, V2>) ~> `Map<K1|K2, V1|V2>`

- And `Map([[endKey, blockMap.get(endKey)]])` is being interpreted as `Map<string, ContentBlock|void>`

- Because `blockMap.get(endKey)` returns `ContentBlock|void`

- So the result of concat is also: `Map<string, ContentBlock|void>`

- Which `.map(operation)` diligently forwards.

- Where the value type `ContentBlock|void` isn't compatible with with the function argument `operation: (block: ContentBlock)` that does not accept `undefined`.

My suggestion for a fix would be to use something like `nullthrows()` around the result of `.get()` or some sort of invariant that the block at endKey definitely exists.

I'm not sure why the computed property names causes the error to go away - my guess there is that Flow has limited support for computed properties and misses the opportunity to check the type.

Part of why this error is tough to follow is because Flow is trying to show you that there are two possible ways of applying `concat()` (one for `Iterable`, one for `PlainObj`) and neither will work. Flow isn't really sure which you intended, so it shows you why both don't work, but because the clearly you intended on using the first and the punchline of the error is usually at the end of the string of Flow's rationale, and the second unindented case is printed right after it, the highest value bit gets lost in the middle of a blob of text.

/cc @calebmer for an example of error message that could be much better communicated

My suggestions for how errors like this could be improved:

- Immediately after the *where*, explain *why* there is an inconsistency, then follow up with the *how* Flow arrived at that conclusion (upside down order).

- When there are multiple Members, (or a nested tree of branching multiple members) Flow should have some idea of which one was most likely intended and start with that message. If there are alternative members that might have been intended, those should be shown next, and if there are any paths through member that are very unlikely to be intended in comparison to others, they can be omitted unless a check with --verbose is added.

- Type arguments like "`Type argument `T` is incompatible:`" are not useful out of context. Which T? Where was that defined? When the error occurred, what was the actual type of T?

- Use color and formatting in the terminal instead of ascii art

- Finally, Flow should check the width of the terminal window before printing so there is an intelligible visual hierarchy to the error output to make it easier for the eye to follow.

(Some good advice on this from Elm: elm-lang.org/blog/compiler-errors-for-humans)

Here's a mockup of how I wish this error had been communicated to be easier to read:

<img width="703" alt="screenshot 2017-10-18 16 37 11" src="https://user-images.githubusercontent.com/50130/31747620-b479515c-b422-11e7-8da4-3c66cdbeb5f7.png">

**Comment by acusti** [comment]
Thanks for the detailed explanation! I found it very helpful to follow your logic as you traced the type logic, and using `nullthrows` took care of it.
