### ISSUE TITLE
Add search to the docs

### ISSUE THREAD

**Issue by Haroenv** [facebook/immutable-js#1501]
### What happened

I wanted to look something up, but couldn't find exactly what I needed without some probing around. 

### How to solve this

We could add search to the docs, with [DocSearch](https://community.algolia.com/docsearch) this would be quite simple. I'm sure that me and @s-pace would be available to help set it up 🙌 !

**Comment by s-pace** [comment]
:wave: @leebyron

I have made [a quick showcase in order to let you try it.](http://immutablejs-docsearch.surge.sh/) You will notice that the redirection could be enhanced.

We would need some changes regarding the layout of the page. We pickup the `name` (or `id`) of the titles (matching the `lvls` selectors of [your configuration file](https://github.com/algolia/docsearch-configs/blob/master/configs/immutable_js.json)) in order to correctly scroll down to the right matching part of your content. Regarding the navigational behaviour of your website, we would need to extract these anchors. Ideally these attributes/anchors would match the subsection of your pages (if you want to continue this way of navigation within your pages).

Example for redirecting to https://facebook.github.io/immutable-js/docs/#/Seq.Set/toJSON:

We will extract the documentation content from the parent page https://facebook.github.io/immutable-js/docs/#/Seq.Set

The DOM title matching `h3.memberLabel` from this former page  should have an id equals to `toJSON`

Could you point us out how we could make these changes?

**Comment by s-pace** [comment]
FYI:

I've successfully configured the underlying crawler and it will now run every 24h.

You're now a few steps away from having it working on your website:

- Copy the following CSS/JS snippets and add them to your page
```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: 'bb766758a6a056d3d0e6e8ae19f99984',
  indexName: 'opendatasoft',
  inputSelector: '### REPLACE ME ####',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```
