### ISSUE TITLE
Empty lists from empty arrays have the same reference

### ISSUE THREAD

**Issue by Christian24** [facebook/immutable-js#1583]
### What happened

I have two arrays I create Lists from. Angular compares them by reference (ChangeDectionStrategy.OnPush). In some cases the arrays can be empty, so the resulting lists are empty too. However, even though the arrays have a different reference (because they are separate instances), the lists share the reference. This is unexpected I think. While this may be intentional, maybe it can be a creation option? 

### How to reproduce

I created a JS Bin which shows the problem: https://jsbin.com/wekorilifi/edit?js,console

**Comment by joshuahhh** [comment]
Could you explain what problem this causes? It seems to me to fit entirely within the contract Immutable makes with the user:

* Immutable.is() function or .equals() method computes equality of values in general.
* When efficient to do so, Immutable.js can return existing objects rather than new objects, "allowing for using === reference equality to determine if something definitely has not changed" (quote from https://facebook.github.io/immutable-js/).

Is there a particular property you wish Immutable had, which this behavior breaks?

**Comment by Christian24** [comment]
Sorry, I had never noticed the last paragraph you quoted. You're right, it does fit entirely within the contract Immutable makes with the user. However, maybe it is a good idea to feature the contract prominently in the docs: https://facebook.github.io/immutable-js/docs/#/. 

Closing this now now as it was more an issue of me being not familiar with the contract.
