### ISSUE TITLE
compare Immutable.toJS() object 

### ISSUE THREAD

**Issue by iShawnWang** [facebook/immutable-js#1587]
![15a3ac44-8072-4f38-b761-3603c576d842](https://user-images.githubusercontent.com/20266594/45133785-a899e180-b1c9-11e8-8cd4-6d70425c2d33.jpg)

As the above image show, i wonder is this the desired result ? 

```
let a = Immutable.fromJS({a:1})
a.toJS() === a.toJS() // output false
```

hmmmmm, this seems a little bit wired....

**Comment by conartist6** [comment]
Yes, this is the desired result, beyond a doubt. If you wish to have Immutable's reference equality property, you must be comparing immutable data structures. If `toJS()` produced the same instance on multiple calls then modifications to one object would modify the other. Solving that problem is why Immutable was created.

**Comment by iShawnWang** [comment]
I got it, thanks ~

# :D
