### ISSUE TITLE
What about DAGs?

### ISSUE THREAD

**Issue by akva** [facebook/immutable-js#1652]
How do I "update" a leaf node (or a sink) in a DAG structure so that all paths to that node see the new value. Here is a jsfiddle to illustrate the issue https://jsfiddle.net/voazr3ju/ That is how do I update the author's score so that all books see the new value? I would assume this is a pretty common situation?

**Comment by akva** [comment]
@davidmccabe, I thought about this too, but this leads to other problems. Not sure if there is  a term for this but this basically allows to sort of "logically update" books without updating them "physically". What I mean by that is that since books reference will not change the memoized books view (and this is one of the big advantages of the immutability - optimisation by reference equality instead of deep value equality) won't know it needs to re-render. So every time I update an author I would have to tell the books view to re-render. But now I am back to manual state management and the advantages of immutability are not so clear any more.

**Comment by leebyron** [comment]
@davidmccabe 's suggestion is the right direction for this - otherwise you need to keep track of all the shared links in your DAG so that when you update one you update them all.

David's suggestion is how we would model a (possibly cyclic) Graph immutably. The ID provides essentially a "pointer" so you can resolve the most recent version (and same version) of a single value at that ID across your graph data structure. While a DAG is not cyclic it still has this issue of multiple pointers to the same conceptual node.

> So every time I update an author I would have to tell the books view to re-render. But now I am back to manual state management and the advantages of immutability are not so clear any more.

Since these are just data structures, updating the data structure still requires you to tell your UI to re-render in the appropriate places. I think Redux, MobX, and other state management tools offer good solutions for subscribing to change over time. If you then make sure your components consider re-rendering not just if the "Book" model changes, but also if the "Author" model they de-reference change as well, you'll have an up to date UI. Immutable.js definitely won't do that for you, but once you have this subscription mechanism in place, immutable data will help guarantee that once your UI does attempt to re-render that it can use an equality check to short-circuit or otherwise memoize.
