### ISSUE TITLE
Why not use JavaScript getters?

### ISSUE THREAD

**Issue by JannesMeyer** [facebook/immutable-js#21]
I'm not sure if I'm overlooking something or if this is a stupid question, but... Why not use JavaScript getters?

JavaScript objects have support for getters: (works everywhere except on IE8)
- http://ejohn.org/blog/javascript-getters-and-setters/
- [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects#Defining_getters_and_setters)

Why not use them (optionally) instead of `.get()` and `.getIn()`? Especially for server-side code and for applications that aren't focusing IE8 this could be really helpful.

**Comment by ivan-kleshnin** [comment]
Unfortunately, without this you can't pass `Map` values to 3-rd party code. 
It breaks all of React mixins, e.g. `linkState`. Same with `List.size` instead of `List.length`...
I thought this library is proved to be compatible with React, but I was wrong. 
Perhaps I overestimate the rate of evolution :(
Any forecasts on when this might change?

**Comment by idolize** [comment]
@ivan-kleshnin 

You can use `.toJS()` for most things, since the whole point of Immutable data structures is that the shouldn't be changed by outside methods.

If you want the two-way data binding from `linkState` you can use this library I made for the purpose: [reactlink-immutable](https://www.npmjs.com/package/reactlink-immutable)

**Comment by leebyron** [comment]
Map is API compatible with the ES6 Map, but not JS Object - unfortunately the language does not provide a capability to do that. There's some discussion in the JavaScript technical committee to find a way to provide read API compatibility performantly, but even with a decision made, it will be months or even more than a year from a first browser adopter, and many years until browsers with that feature are widespread to the point that we can rely on such a feature. 

Unfortunately that means custom data structures in JavaScript must have a different read API from Object and Array for the foreseeable future.

**Comment by ivan-kleshnin** [comment]
@idolize

> You can use .toJS() for most things, since the whole point of Immutable data structures is that they shouldn't be changed by outside methods. If you want the two-way data binding from linkState you can use this library I made for the purpose: reactlink-immutable

Yeah, I went that road. Then went back. Unfortunately with both ImmutableJS and Mori your datastructures begin to look very messy. The probability of bugs increases, not decreases. 
At least for me. So I switched back to native ones.

**Comment by scottmas** [comment]
FWIW, `Object.defineProperty` is now just as fast as getting/setting via methods. https://jsperf.com/getter-setter/8

**Comment by Gregoor** [comment]
@scottmas awesome! @leebyron any interest in a PR adding getter support?
