### ISSUE TITLE
Delete by value

### ISSUE THREAD

**Issue by dmnd** [facebook/immutable-js#264]
I've found myself using this a lot:

```js
function deleteValue(l, x) {
  var i = l.indexOf(x);
  if (i === -1) {
    throw `Value ${x} not found in ${l}`;
  }
  return l.delete(i);
}
```

It's useful because the shorter `l.delete(l.indexOf(x))` does the wrong thing when the value is not found. Do you think this method (maybe with a better name?) belongs in the lib?

**Comment by leebyron** [comment]
I'm also finding trouble coming up with a name for this which makes it clear that this will only delete the first instance of the value, not all instances of the value.

For now I don't think it's right to add it to the library since the helper function is quite small, and it's also unclear if the correct behavior is to throw or return the unchanged list. 

I'll keep it in mind in the future though.
