### ISSUE TITLE
Use more idiomatic ES6 import/export syntax?

### ISSUE THREAD

**Issue by eventualbuddha** [facebook/immutable-js#273]
Currently all imports exist solely, as far as I can tell, to configure the order in which the files are concatenated (via [smash](https://github.com/mbostock/smash)). In a real ES6 environment instead of this

```js
import "iterable"
class Collection extends Iterable {}
```

you'd do something like this

```js
import { Iterable } from "./iterable";
class Collection extends Iterable {}
```

Ideally you'd then combine the files using a smarter version of smash, i.e. the (shameless plug) [es6-module-transpiler's bundle format](https://github.com/esnext/es6-module-transpiler).

I'm working on extracting the bundler from es6-module-transpiler into its own project, and I tried using immutable-js as a test project. I've converted some of the files to the style above and the output is essentially the same as when used with smash.

**Comment by leebyron** [comment]
Yes! I have this working almost all the way using the really nice esperanto project. I've got some work to do to leverage import/export syntax correctly, since I use circular dependencies in a way that smash handles but ES6 does not. Then I am going to tackle this. 

I appreciate you opening the task to keep track! I'll post progress here.
