### ISSUE TITLE
.fromJS doesn't preserve key types

### ISSUE THREAD

**Issue by chollier** [facebook/immutable-js#282]
I would expect `.fromJS` to preserve key types, at lease for integer. Here is my test case :

```javascript
var obj = {42: "test"};
var test = Immutable.fromJS(obj);

obj.get(42); // undefined
obj.get("42"); // "test"
```

I might be missing something but I find it odd having to `.toString()` every time I `.get` a value.

**Comment by leebyron** [comment]
This is actually just JavaScript doing it's thing. JavaScript Object keys are always strings.

```js
var obj = {42: "test"};
// get the keys using Object.keys()
var keys = Object.keys(obj).forEach(function (key) {
  console.log(key, typeof key);
});
// get the keys using for in
for (var key in obj) {
  console.log(key, typeof key);
}
```

**Comment by chollier** [comment]
Damn, of course.. Thanks !

**Comment by leebyron** [comment]
More fun facts about JavaScript:

These two lines are equivalent:

```
var obj = { foo: "bar", 42: "answer" }
var obj = { "foo": "bar", "42": "answer" }
```

And property access always coerces to string!

```
obj["42"] // answer
obj[42] // answer
```

**Comment by mczepiel** [comment]
So I understand how this happens but what is everybody doing to deal with it?

It's very easy to get into a situation with a mix of string keys (`fromJS({1: "a"})`) and number keys (`set(2, "b")` or even `set(1, "c")) and I'm just curious where people are normalizing the keys.

It's insidious that the method of population (perhaps unknown to you) leads to you not knowing what key to use to retrieve data.

**Comment by leebyron** [comment]
`Immutable.Map.get` accepts any kind of input because you can use anything as a key.

For example, what should this log?

```js
var map = Map().set(1, "number").set("1", "string");
console.log(map.get(1));
```

**Comment by leebyron** [comment]
Note, this is also how ES6 collections work:

```js
var es6Map = new Map();
es6Map.set(1, "number");
es6Map.set("1", "string");
console.log(es6Map.get(1));
```

**Comment by leebyron** [comment]
JS Objects just aren't Maps. They're collections of properties keyed by strings. ES6 collections escape this problem altogether by not providing any tools for converting to and from JS Object.

The fact that ImmutableJS provides `toJS()` and `fromJS()` is because they're legitimately convenient, but you still must be aware of the limitations.

**Comment by mczepiel** [comment]
Fair enough, probably best to match the ES6 Map behavior over object property access.

I still have a question of best practices though. Handling numeric ids is very common form a backend, I ran into a problem just down as I started using the very convenient `merge` API to integrate newfound records into a Flux store. Previously I was iterating and then `set`ting.

This leads me to a situation where it seems best to never use numeric keys and to cast them to strings upon receipt from the server. Is that something you've run into?

**Comment by mczepiel** [comment]
FWIW, I'm reverting back to iterating and using `set` `withMutations` to build a Map. I was just surprised by the downstream changes thrhoughout my apps after what appeared to be an innocuous internal change on my part over to `merge(jsObj)`

Not a huge deal though, the side-effects are understandable and I'll keep them in mind if I ever use `fromJS` explicitly or otherwise.

**Comment by leebyron** [comment]
In applications I've worked on at Facebook and elsewhere, we just avoid using numeric keys or at least make strong assumptions that they are strings. As an example, Facebook's API provides a unique numeric-string ID for every object in it's DB. We occasionally send them as keys in a JSON payload and need to respect that they are strings on the client, not numbers. This ends up important for other reasons as at some point our numbers got larger than the 52bit range that JS numbers can represent and also we ran into some cases where we needed to base64 encode IDs and we didn't need to change any app infrastructure to do so.

**Comment by mczepiel** [comment]
Heh, I'm still working at sub-Facebook scale so my needs aren't the same, but I'm glad to hear treating the otherwise numeric ids as strings is a sane move. Maybe I will do that just to avoid the unexpected casting issue I highlighted. Thanks for the insight.

**Comment by leebyron** [comment]
Funny story: we used to represent ids as numbers on the client instead of strings, we even ran `parseInt()` to get them. We had a shortcut function for linking to someone's profile, setting the URL to `"facebook.com/" + id`. At some point a bug elsewhere caused IDs to be formatted slightly differently so our number parsing started to return `NaN` and all links went to my old manager's profile.

**Comment by pluma** [comment]
FWIW, I would strongly recommend against treating IDs as numbers, just as you shouldn't treat ZIPs or phone numbers as numeric values. Even if they are integers, there may be gaps (e.g. if a record was deleted and numbers are assigned via SQL's `auto_increment`) and it's easy to run into conversion problems (e.g. accidentally applying number formatting, resulting in locale-dependent bugs).

**Comment by mczepiel** [comment]
Thanks, I've built a good number of "enterprise" apps and hadn't run into any problems using the Rails default auto-incrementing numeric ids on the client. I never assumed they were sequential or anything, it just happens to be what the frameworks vends by default when you convert an ActiveRecord model to json.

Thankfully, it's easy enough to change that in the json output, especially with jbuilder templates.
I wouldn't be surprised if Flux developers with Rails backends hit this more frequently given the defaults.

Just annotating with keywords for anybody that comes afterwards; the behavior of immutablejs is as expected.

**Comment by gabrielecirulli** [comment]
Thanks for the discussion so far. Quick follow-up question: let's say I have a collection of users keyed by ID, and as it's generated from JSON, the keys end up being strings (which seems to be good practice from what I've read).

I also have objects for "Teams", and each team contains a list of user IDs that participate in said team. Those IDs are all numbers, and in order to get the actual corresponding user object I need to do `users.get(id.toString())`.

My question is: is it a sane practice to have to run `toString()` this often throughout the code, and is it not a bad idea to have to assume such knowledge about the nature of the data?

**Comment by leebyron** [comment]
In my opinion, you should structure your app such that that `id` will always be the same type: strings or numbers, but not both at the same time. I think having to consistently remember to coerce your `id` variables to strings with `id.toString()` or to numbers with `+id` will just be an opportunity to forget to do that once and you'll introduce a bug.

It's totally possible to create an Immutable.js Map where the keys are numbers instead of strings, it's just not representable as a JSON Object. You could also go all-in on string `id` and ensure that's the case through your whole application.

**Comment by cesarandreu** [comment]
@leebyron Have you considered making a Map.withIndifferentAccess so that you can set and get values using either number *or* string? That way it would work like JS objects, and it handles serializing and deserializing JSON.

**Comment by leebyron** [comment]
@cesarandreu do you mean a String Map where keys are always first coerced to String? This is how JS objects work. They're not indifferent to type, they always coerce to String, which is what leads to this common misconception.

**Comment by leebyron** [comment]
Is the concern that a data type that restricts key type is desirable, or is the concern that JSON is a non-ideal serialization format?

**Comment by cesarandreu** [comment]
Ah, sorry for not being clear. I do mean a StringMap. I'd find it very desirable to have an immutable Map that will behave like JS objects and coerce keys to string.

I think it would just make it easier to deal with server responses. Right now whenever I'm taking a value out of my indexed collections I wrap the id with a template string (`${id}`) to make sure it's always a string.

**Comment by geekyme** [comment]
+1 i'm having the same problem. I think that when converting an object into an immutable, numbers should be preserved as numbers. 

for instance I have an object with a `count` field set to an integer. Once I do a fromJS(), any integer that was stored on `count` field becomes a string.

**Comment by leebyron** [comment]
@geekyme are you seeing an instance where a value is being coerced? That sounds like a bug, could you show some code which replicates the issue?

**Comment by geekyme** [comment]
hey @leebyron thanks turns out it was a nasty bug on my end that was coercing it to string. Not immutable's fault. sorry for the false alarm :(

**Comment by fabiosussetto** [comment]
Thanks for the details in this discussion, got into the same issue recently. Now it does make sense.

**Comment by StevenLangbroek** [comment]
Sorry to open this thing up again, but I'm working in a very large codebase where a migration from Integers -> Strings could potentially be very painful. Is there a way to extend a Map to a StringMap? Something like:

```js
import { Map } from 'immutable';

export class StringMap extends Map {
    get(key) {
        key = key.toString();

        return super.get(key);
    }

    set(key, val) {
        key = key.toString();

        return super.set(key, val);
    }
}
```

Any advice on how to approach that? Edge cases I should be aware of?

**Comment by michaelswe** [comment]
Thank you for a great discussion. I learned a lot. I see that the issue is closed, but I'd like to add some points for others to find.

As @leebyron says, consistency is good, i.e. use string-id OR integer-id. If you like me use Immutable with Redux and your data originally comes from a database, you might have integers as both primary and foreign keys. If you need to do lookups in your Redux store by foreign key you'll be best off to **use integers as keys** in your Immutable.Map. This way you never need to "manually coerce" to string when performing lookups.

Here is how I load data into Redux from my API in order to preserve the keys as integers:

`
case DRAWING_RECEIVE:
  let updatedDrawings = Map(
    action.payload.drawings.map(item => {
      return [item.id, fromJS(item)];
    })
  );
  return = state.update('items', items => items.merge(updatedDrawings));
`

N.b. I have an "items" Map for storing the actual data in each slice in the store, hence "items" in the code above. It took me some reading and testing before landing in this key-solution. It really works well and I recommend it.

**Comment by Altiano** [comment]
Whe is this not work then?
![image](https://cloud.githubusercontent.com/assets/8316282/25061976/2c697acc-21f5-11e7-9578-a2655a31383d.png)
You said that key is evaluated to string but can't get from string version after construct with integer

**Comment by pluma** [comment]
@Altiano read the original discussion again:

* when creating maps from objects, keys are always converted to strings because object property names are already strings

* when creating maps from arrays of key-value pairs, the keys' types are preserved

This is the exact behaviour you're seeing: the keys aren't converted by immutable. The original discussion was the result of a confusion about JavaScript's behaviour (i.e. object keys always being strings), not something immutable does.

**Comment by Altiano** [comment]
@pluma Must be this lines (http://facebook.github.io/immutable-js/docs/#/Map/Map):

> Keep in mind, when using JS objects to construct Immutable Maps, that JavaScript Object properties are always strings, even if written in a quote-less shorthand, while Immutable Maps accept keys of any type.

-_____-
that is not so straight explanation

anyway Thanks @pluma

**Comment by pluma** [comment]
@Altiano It's not a quirk of immutable.js, it's a "quirk" of JavaScript.

Object keys are property names. Property names are always strings (or symbols, but that's probably not as important). If you use non-string property names when defining properties, the names will be converted to strings. Don't take this as a snark but I strongly recommend you solidify your understanding of the language before moving on.

I strongly recommend the [_You Don't Know JS_ series of books](https://github.com/getify/You-Dont-Know-JS) by getify because they're available online for free and are pretty exhaustive without dwelling too much on the author's personal opinions. If you can't set aside the time to read them from back to back (which is understandable) just use them as a "take what you need" reference and look up the parts of JS you find confusing.

FWIW if you want to observe the behaviour more directly, open your browser's console (F12 or Ctrl+Shift+J/Cmd+Shift+J depending on your platform) and compare the following (assuming Chrome/Edge or a recent version of Firefox):

```js
var obj = {1: 'a', 2: 'b', 3: 'c'};
var map = new Map();
map.set(1, 'a');
map.set(2, 'b');
map.set(3, 'c');

Array.from(map);

Object.entries(obj);
```

The last two lines show you what native maps and objects look like when converted to arrays of key-value pairs. While as you can see it is possible to treat objects like maps, the keys are always strings. There are also some other caveats that make objects unfit as substitutes for proper maps (whether native or immutable.js).

(Another limitation is that some object property names are "special" and may have unintended side-effects, so it's a bad idea to use objects as maps when dealing with potentially malicious or uncontrolled values for keys.)

**Comment by billjohnston** [comment]
I kinda realized after making this I should just make the `Map` a `List`, but here is a fromJS fn that will recursively make all the number like keys of an object integers. 

	import { isNaN } from 'lodash'
	import { fromJS, Map } from 'immutable'

	const integerizeKeys = stringMap => stringMap.reduce(
		(results, value, key) => {
			const integerizedKey = parseInt(key, 10)
			const fixedKey = isNaN(integerizedKey) ? key : integerizedKey
			return results.set(
				fixedKey,
				Map.isMap(value) ? integerizeKeys(value) : value
			)
		}, Map()
	)

	export default function (obj) {
		const immutableObj = fromJS(obj)
		return integerizeKeys(immutableObj)
	}
