### ISSUE TITLE
Have Cursor.isCursor(maybeCursor)?

### ISSUE THREAD

**Issue by Dashed** [facebook/immutable-js#300]
Pretty much all collections have a static method to check if an object is that particular type. AFAIK, there's no official way to do this `Cursor.isCursor(maybeCursor)`.

This is needed for a `shouldComponentUpdate` in React whose props/state may hold cursors.

At the moment, this is used to identify cursors:

```js
function isCursor (maybeCursor) {
  return maybeCursor && typeof maybeCursor.deref === 'function';
}
```

Is there a better way to do this externally? Or if it can be baked in as a static function? :smile:

**Comment by jeffbski** [comment]
+1

**Comment by leebyron** [comment]
This is a bit counter to the purpose of Cursors, which seek to be invisible and act as the types they wrap.

For shouldComponentUpdate, I recommend using `Immutable.is()` which will automatically handle Cursor unwrapping for comparisons.

If you want to deref regardless of Cursor for more specific comparisons, you can use `obj.valueOf()`. Regular types return themselves in `valueOf`, but Cursors return their `deref()`.

**Comment by Gozala** [comment]
> This is a bit counter to the purpose of Cursors, which seek to be invisible and act as the types they wrap.

> For shouldComponentUpdate, I recommend using Immutable.is() which will automatically handle Cursor unwrapping for comparisons.

Given the discussion here https://github.com/omniscientjs/omniscient/issues/76 I agree with @leebyron that it would make more sense to defer comparison to immutable type implementation or cursor implementation than try to handle each individual type in a custom way.

**Comment by Gozala** [comment]
I also have to say that I was proposing to make a fork, but mainly to resolve issue if rendering on animation frame as om does.

Current problem with cursors can be illustrated as:

```js
const not = x => !x;


ToggleButton({ onClick: event => cursor.update(‘isChecked’, not)})
```

If onClick is invoked even number of times with in the same animation frame result will be unexpected, the problem is render won't run there for event handler will refer to cursor that has out of date knowledge of the state.

I do believe this is a reason why om has two ways to defer cursor https://github.com/omcljs/om/wiki/Cursors#consistency-and-observability `(deref cursor)` to get current state one `(om/value cursor)` to get rendered state.

I think adding such a capability to cursors would likely be necessary to handle async rendering.

**Comment by Gozala** [comment]
Deleted my response as I realised I posted it to a wrong thread.

**Comment by wmertens** [comment]
@leebyron when you do `Immutable.is(cursor, nextCursor)` and the cursors are pointing to undefined parts of a tree, Immutable.is will throw because it runs `valueOf()` and then typeof valueA.equals.
Does that mean:
- you shouldn't point cursors past the data structure
- Immutable.is should be careful about undefined returns
- cursors should return cursors on undefined valueOf?
- there should be a Cursor.is?

Is this a separate issue?
Pointing past the tree is nice because set() will fill in the missing parts...

**Comment by leebyron** [comment]
Immutable.is should not throw. Thanks for highlighting this bug!

**Comment by leebyron** [comment]
Also yes, separate issue

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
