### ISSUE TITLE
to/fromJS should maintain equalities.

### ISSUE THREAD

**Issue by tolmasky** [facebook/immutable-js#305]
I'm actually not sure if this is or should be a desired goal of the library, but I've run into the following:

```javascript
var r = I.Map();
var l = I.List([r, r])
l.get(0) === l.get(1) // return true
```

Given this, the following is a bit unfortunate:

```javascript
var obj = fromJS(r)
obj[0] === obj[1] // return false
```

The same holds with toJS (where [x,y] given x===y results in a List where [0] not equal to [1]).

I could see arguments for ignoring this. My particular use case is that there is data that is out of my control, that I am then converting to immutable.js for my use in the view layer. As such, sometimes this data has multiple internal references like this, and its important for me to know this (to be able to display this fact). I'm building my own from/toJS's that handle this, but was curious if its something that was wanted in the library as well.

**Comment by pluma** [comment]
I think the idea with immutable data structures is that they should be treated as identical by value equality for most intents and purposes. Compare immutable's behaviour with that of built-in immutable types like the various primitives.

By that logic, your code is already broken if it distinguishes between value equality and identity in immutable structures and the toJS behaviour is just a symptom of that.

**Comment by leebyron** [comment]
Maybe submit a pull request since you've already written up custom implementations?

If the performance impact of this is negligible then having the additional behavior is nice. If it's expensive then perhaps it makes sense as an external utility function.

**Comment by tolmasky** [comment]
@pluma right but one of the points of having those be essentially the same is to be able to do a === check and not pay the price of an expensive deep equality check (that's one of the main sells of using immutable values in react, having very quick and simple shouldCompknentUpdates). If we were really ambitious we could have as a goal that List.if(1.2.3).push(4) should === List.of(1.2.3.4) (the same way "123"+"4" === "1234" thanks to immutable string in JavaScript). Properties such as these would make memoized_func(list) trivial to write (thus getting similar benefits as react). Of course, that is difficult to enforce and merely an example but maintaining existing equalities seems doable.

I'll push my implementations later this week (not sure if I can get them integrated into the library itself but hopefully be able to do some perf comparison).

**Comment by leebyron** [comment]
> If we were really ambitious we could have as a goal that List.if(1.2.3).push(4) should === List.of(1.2.3.4)

This is unfortunately not possible without some devastating performance issues as it would require these two operations to "know about" each other (read: some global cache). Instead, you should favor Immutable.is() for these kinds of comparisons.

> (the same way "123"+"4" === "1234" thanks to immutable string in JavaScript).

This actually uses a deep value equality check. It's likely that the two strings occupy different memory addresses, but JS knows that comparing strings means doing a character for character check if a memory address comparison fails.

---

On the whole, we're balancing for performance here. We pay a very small penalty in order to detect no-ops and return `this` in some operations, it pays off because we know it's a common next-operation to compare both the old and new versions.

In this case, building fromJS to be aware of references requires building up a cache of all visited objects by reference, which is quite a burden to put on this method which should be quite fast.

At the end of the day, you should not be relying on `===` reference equality so directly as not everything that is value equal can also be reference equal. `Immutable.is()` is not slow, and contains the `===` check internally as a first step anyhow, so is often equivalently fast. Slowing down other operations to make `Immutable.is()` faster is very likely going to be a net-negative on performance overall.

Also, I would be thrilled to be proven wrong on this. If you have code and benchmarks I'll happily entertain them. The smartest tricks often appear to be terrible ideas at first glance.
