### ISSUE TITLE
Adding Iterable#getPath('foo.bar') to the library?

### ISSUE THREAD

**Issue by jviereck** [facebook/immutable-js#310]
In my current project I have to do a lot of deep lookups. At the moment immutable-js aids this usecase by using the `Iterable#getIn(...)` method like this:

```js
var nested2 = nested.mergeDeep({a:{b:{d:6}}});
nested2.getIn(['a', 'b', 'd']); // 6
```

Instead of passing an array to the `getIn` method, I personally find passing a string more convenient, like:

```js
nested2.getPath('a.b.d'); // 6
```

where the implementation of `Iterable#getPath(...)` might look like this:

```js
mixin(Iterable, {
    ...
    getPath: function(searchKeyPathStr, notSetValue) {
      return this.getIn(searchKeyPathStr.split('.'), notSetValue);
    },
    ...
}
```

How do you feel about adding a function like `getPath` to the library? I am happy to create a PR in case there is enough support for this idea.

PS: The idea for `getPath(...)` originates from my experience with the SproutCore library and their SC.Observable object: http://docs.sproutcore.com/symbols/SC.Observable.html

**Comment by Dashed** [comment]
Unlikely this would be in the library. This has been suggested before.

See: https://github.com/facebook/immutable-js/issues/237

**Comment by leebyron** [comment]
Thanks @Dashed. Yes, the tricky thing here is that not everyone agrees on what "path" encoding should be used. Also note that encoding path as a string means that you cannot use it to access when a non-string key is used. Finally, what would `'a.1.b'` become? `"1"` and `1` are different keys! You either exclude numeric strings, or you exclude the ability to index into a List!

Despite the issues with this, I know that it's a valuable shorthand. My suggestion to those who want this shorthand is to use a locally scoped function that turns it into a key path, so they can use the semantics they care about. Since the function is so small, it's probably fine for it to live inline in your application instead of needing to live on npm.

```js
function path(pathString) {
  return pathString.split('.').map(key => parseInt(key) || key);
}
```

Then you can use it for any `*In` function in the library:

```js
nested.getIn(path('a.b.d.1.2.3'));
```

**Comment by jviereck** [comment]
Thanks for the detailed replay @leebyron and @Dashed - make totally sense to me.
