### ISSUE TITLE
groupBy fails when using objects as the grouping key

### ISSUE THREAD

**Issue by ccapndave** [facebook/immutable-js#325]
```js
const Thing1 = {};
const Thing2 = {};

const x = {
    "key1": Thing1,
    "key2": Thing1,
    "key3": Thing2
}

// This doesn't give the expected result!
const result = Immutable.Map(x).groupBy(x => x);
```

This results in a strange object containing only a single key.  Note that changing the `Thing1` and `Thing2` values in `x` to their string equivalents gives the expected result.

```js
const Thing1 = {};
const Thing2 = {};

const x = {
    "key1": "Thing1",
    "key2": "Thing1",
    "key3": "Thing2"
}

// This works as expected
const result = Immutable.Map(x).groupBy(x => x);
```

**Comment by leebyron** [comment]
Hmm, I'm having trouble reproducing this.

After running...

```js
const Thing1 = {};
const Thing2 = {};

const x = {
    "key1": Thing1,
    "key2": Thing1,
    "key3": Thing2
}

const result = Immutable.Map(x).groupBy(x => x);
```

I inspect result...

```js
console.log(result.size);
2
```

That's expected, since we're returning `Thing1` and `Thing2` as the keys to group on.

```js
console.log(result.get(Thing1).size); // 2
console.log(result.get(Thing2).size); // 1
```

This also makes sense, Thing1 had two keys pointed at it.

```js
console.log(result.toString());
// Map { [object Object]: Map { key1: [object Object], key2: [object Object] }, [object Object]: Map { key3: [object Object] } }
```

That looks like what we expect.

---

Perhaps you could write up a quick test case that fails for you? I think I'm just not seeing the error yet.

**Comment by ccapndave** [comment]
Wow, what a quick response :)

You are absolutely right.  Given that it seems that the problem was actually that I was using `toJS()` in order to debug this in the Chrome dev tools, and `toJS` concatenates it into an object with a single key causing me lots of confusion.

**Comment by leebyron** [comment]
Ahh yes. `toJS()` is lossy for a lot of reasons.

So in this case, we're using Objects as keys in our Immutable.Map, but when we call `toJS()`, it's converting back to a JS Object, it needs to convert the keys to strings so it can use them as JS Object keys. Both `Thing1` and `Thing2` will produce `"[object Object]"` when cast as strings. Since all keys have to be unique, the 2nd key for `Thing2` overrides the first from `Thing1`, and you only see that data.

**Comment by ccapndave** [comment]
Got it.  In general is an explicit `toString()` the best way to see what is going on inside a collection?

**Comment by leebyron** [comment]
To some degree. Immutable collections implement a pretty reasonable `toString` which does its best to illustrate what's going on, but it does still involve casting everything to strings. You can see in my investigation, when calling `toString()` both object references get flattened to `[object Object]` and it's a little tricky to see which is which, but it at least illustrates the shape.

**Comment by ccapndave** [comment]
Thanks again!
