### ISSUE TITLE
toArray behavior on Maps

### ISSUE THREAD

**Issue by tgriesser** [facebook/immutable-js#333]
[This ticket](https://github.com/moreartyjs/moreartyjs/issues/58#issuecomment-74389910) was raised over in Morearty.js regarding an incorrect example of using transit with OrderedMaps.

I was looking through the tickets and didn't see any questions raised so I figured I'd ask, is the API of `toArray` on Map / OrderedMap not preserving the map entries as k/v tuples intentional?

**Comment by leebyron** [comment]
It's intentional, but probably misguided. Changing it would be a breaking change, but alongside clearer APIs about (de)serializing I think it would be the right thing to do.

**Comment by dubrowgn** [comment]
An easy way to iterate over a `Map` as a list of tuples would be really useful in some situations. Am I correct in thinking the way to do it currently is:

```javascript
// map.asTuples()
map.map((v, k) => [ k, v ]).valueSeq()
// -- or --
map.map((v, k) => { key:k, value:v }).valueSeq()
```

Of course, this might be useful for all the datatypes, not just `Map`. Eg:

```javascript
// [list|set|seq|...].asTuples()
list.map((v, i) => [ i, v ])
// -- or --
list.map((v, i) => { key:i, value:v })
```

On a side note, this kind of thing is what you would think `keySeq()` is for, but you run into all kinds of issues because `Seq.Keyed` is treated specially by just about everything. For example, you can't transform the keys via `map()` because `map()` only effects values. You can use `mapEntries()` instead, but it's only available if your original structure was a `Map` to begin with. Using `flatten()` on a sequence of `Map` produces a `Map` instead of a sequence of their values as you'd expect (it's basically `_.extend()`). Etc., etc., etc.

I wonder if this would be a good time to take a look at everything from an API level and see if there isn't a more generic solution that is more consistent.

**Comment by leebyron** [comment]
Have you tried `map.entrySeq()`? It does basically exactly what your "asTuples" does. 

Also, you can use the for of iteration loop since the natural iterator value for a Map is the entry tuple. This works both for Immutable Map and the existing ES6 Map

```
for (const [k, v] of myMap) { 
}

**Comment by dubrowgn** [comment]
That's exactly what I was looking for, thanks. It's interesting that `list.entrySeq()` works, but `list.mapEntries()` does not.

**Comment by leebyron** [comment]
mapEntries doesn't really make sense for a list, since returning anything other than incrementing ints as keys wouldn't make sense.

**Comment by dubrowgn** [comment]
It would be useful for the same reasons it's useful for `Map`: You can defined your own keys using `mapEntries()`. But, I suppose it comes back to the concrete datatype thing again. `mapEntries()` really should produce a `Map` or an `Iterable.Keyed`, but that wouldn't match the rest of the Api.
