### ISSUE TITLE
What's wrong with Maps?

### ISSUE THREAD

**Issue by ivan-kleshnin** [facebook/immutable-js#335]
```javascript
let {Map} = require("immutable");

let data = Map({
  model: Map({
    username: "foo"
  })
});

console.log(data.get("model"));                            // Map { username: "foo" }
console.log(Map({username: "foo"}));                       // Map { username: "foo" }
console.log(data.get("model") === Map({username: "foo"})); // false
```

**Comment by leebyron** [comment]
These are two different objects, so this is expected for the same reason that {k:"v"} !== {k:"v"}. 

If you want to check value equality, use Immutable.is()

**Comment by ivan-kleshnin** [comment]
This kinda defeat the whole principle...no? We already have *two different objects in JS* why replicate the same clunky behavior in this library?

**Comment by leebyron** [comment]
It certainly doesn't defeat the purpose. Objects and Maps are very different things and the data structures this library implements can be very efficient and powerful way to use persistent immutable data in JS. Native JS objects and Maps are mutable, the purpose of this library is to introduce immutability. 

As far as equality checking, it's not that this library replicates a clunky behavior, it's simply that JS does not allow for operator overloading. If it did, this library would certainly take advantage of that. In lieu of operator overloading for ===, we just settle with a function is(). 

There are proposals for future versions of JS to make this sort of thing less awkward. JS Strings are persistent immutable data structures with a custom equality implementation, but since they are native to the language we tend to not stop and think about how strings and objects behave differently relative to memory usage and value equality.

**Comment by ivan-kleshnin** [comment]
Ok, so if `===` doesn't work in all cases (and it's impossible to implement this currently), why it's used in documentation along with `.is`. Why not just `.is`? I also saw `.equals` somewhere. 
I still think multiple ways to compare "immutable" objects, yielding different results, strongly go against the fundamentals.

**Comment by leebyron** [comment]
That's good feedback. I'll clarify the documentation around this.

**Comment by ivan-kleshnin** [comment]
It would be great, thanks!
