### ISSUE TITLE
some API methods not available on cursor

### ISSUE THREAD

**Issue by tcoopman** [facebook/immutable-js#346]
I was surprised to see that some methods are not available on Cursor. For example if you have this:

```js
var data = Immutable.Map({'a': Immutable.List()});
var cursor = Cursor.from(data, ['a'], newData => {
  data = newData;
});

cursor.push(....); // error
```

It may be that I don't understand cursors completely, but I would expect cursor.push to work. Is there any reason, or is it just not implemented?

**Comment by hufeng** [comment]
maybe you can try this.

```javascript
var Immutable = require('immutable');
var Cursor = require('immutable/contrib/cursor');

var data = Immutable.fromJS({a: Immutable.List()});
var cursor = Cursor.from(data,newData => {console.log(newData);data = newData;});

cursor.withMutations((cursor) => {
  cursor.update('a', (list) => list.push(1));
});
```

**Comment by tcoopman** [comment]
This code looks like it should work without `withMutations` but it doesn't. Why is that?

Also this code cannot really work for me because the `withMutations` needs to know the structure of the root Data. I don't want that (that's a reason why I use the cursor).

**Comment by wmertens** [comment]
How about making cursors automatically proxy methods from the object it points to instead of hardcoding?
In general, it would be interesting to call root object and referenced object methods, and it would be useful to provide the _keyPath as well.

So an option would be to provide a list of names to the cursor and when it creates a subcursor it adds proxy methods for the names it can find. There would be a list for the root object and names for the referenced object, perhaps with different signature types like no path, keyPath, keyPath+first arg.
That way, you could have a single polymorphic Cursor class which would behave mostly as the referenced object.

The update function could be completely customizable, for example.

**Comment by wmertens** [comment]
In fact, since conceptually the Cursor is a API-transparent proxy for the object it references, perhaps a cursor should subclass the referenced object prototype completely, and only add/override whatever methods the root object wants exposed, always calling them with the _keyPath as the first argument.

The cursor would be whatever object or primitive it points to, plus `update`, `get`, `getIn`, ... All changes would have to go through `update`, like `cursor.update(cursor.push(...))`.

To support cursors for a path that doesn't exist, you provide a default object. Since it's immutable, it can be shared between all subcursors.

Example API:
```jsx
root = Map(...);
root.getRootSize = function() { return this.size; };
cursor = Cursor.from(root, {default: new Map(), proxy: ["getRootSize"], update:handleUpdate})
return (<Foo data={cursor}/>);
```
in Foo:
```jsx
_onClick: function (ev) { o = @props.data; o.update(o.set(...)); }
render:... return(<p>I'm 1/{@props.data.getRootSize()} of the data</p>);
```

Something like that.

(*) this could allow sparse objects, not sure if that's useful...

PS: Furthermore, I'm of the opinion that cursors used in React should be immutable too. This means that the only way to update a cursor value is with an outside code path via the `_onChange()` callback, which should not change the referenced root object. This enforces a one-way React flow and makes sure cursors cannot be mutually stale as in #255. There are probably valid use cases for mutable cursors, so I think it just needs to be documented that you need to be careful with `onChange`.

**Comment by tcoopman** [comment]
I haven't put much thought in that approach, but it might be worth looking into it.

A disadvantage is that cursor isn't transparent then anymore. It would be nice if the react component didn't have to know it was a cursor, but just an Immutable List or Map...
In that sense I've created this pull request: #365
