### ISSUE TITLE
Explain how/why triple === equality works the way it does

### ISSUE THREAD

**Issue by dchambers** [facebook/immutable-js#348]
Suppose I have a map `m` defined like this:

``` js
var m = Immutable.Map({x:1});
```

then the following code snippet returns `true` as expected:

``` js
m === m.set('x', 1);
```

But, for some reason, this doesn't work:

``` js
m === m.set('x', 10).set('x', 1); // unexpected failure #1
```

and even weirder, nor does this:

``` js
m.set('y', 5) === m.set('y', 5); // unexpected failure #2
```

I have no experience with Clojure, and perhaps this stuff would be obvious to me if I did, but as a JavaScripter I think it would be great for the documentation to explicitly mention that this is what happens, and to provide an explanation of the rationale for this behaviour.

At present, I can only guess that failure case number 1 is too hard to do for more complex use cases, so it's avoided for all cases. As for failure case number 2, I'm baffled, and it almost makes me start doubt that there is any data structure sharing going on at all!

**Comment by leebyron** [comment]
This has seemed to trip up a lot of people lately, so I will definitely include more documentation on this. 

m.set('y', 5) !== m.set('y', 5)

For the same reasons:

{y: 5} !== {y: 5}

Objects use referential identity equality, not value equality. 

For value equality, you must use Immutable.is(m, m2) or m.equals(m2) which will determine if two collections have value equality. 

As an optimization, if the two cases being compared are referentially equal, then that value comparison will be extremely cheap.

In immutable, every time you call one of the mutative methods like "set", you're creating a new object. Within that new object it may share portions of data with the previous object, but at the top level it's still a new object and will fail referential equality (===) with any other object, including other objects that happen to hold the same shared data.

As an optimization, when calling a mutative method like "set" Immutable.js first looks to see if the value you provide is === with the value already at that key position. If it is, then it short circuits, returning itself, knowing that the operation would be a no-op.

This optimization helps Immutable.is() find that fast path in this common case.

With immutable data, you're far more often looking for value equality than reference equality. You should use is() and m.equals() whenever you want to know if two collections represent the same information. 

There are some cases, usually when writing memoization functions, where you instead want to know a rough and cheap to calculate equality and are willing to give up on some false negatives, eg "are these definitely not not-equal".

Hopefully that helps explain a bit. I'll capture this in better terms and add to the documentation.

**Comment by dchambers** [comment]
Hi @leebyron,

Thanks for the very detailed response. I guess I just had some incorrect assumptions about what the structural sharing of immutable data using a trie actually looked like. I had supposed it involved a tree of information starting with a common shared root, where each addition involved the creation of a new branch, and where each modification involved the creation of a new branch from a different part of that common tree.

Were it modelled like this, then `m.set('y', 5) === m.set('y', 5)` would evaluate to `true`, as would `Immutable.Map({x:1}) === Immutable.Map({x:1})` since it would just involve the same modification to the same common root for all map data of `{}`.

I've tried Googling for a good explanation of the Clojure map trie data structure, but have struggled to find anything really comprehensive. Are you able to recommend a good resource, or would I need to read the source code?

**Comment by leebyron** [comment]
They're called Hash Array Mapped Trie and there's decent documentation of the overall concept floating around, including on Wikipedia. I also gave a talk on the structure and have some illustrated examples in that talk that you can find on YouTube. 

Your assumptions are close, but maybe a bit upside down. The root of every structure is unique but often leafs of the tries are shared amongst one another.

**Comment by dchambers** [comment]
Hi @leebyron, I've just watched [a video of your excellent conference talk](https://www.youtube.com/watch?v=I7IdS-PbEgI) that perfectly explains the underlying data structures involved, and now I finally understand why it works the way it does :+1:. The trie isn't split based on the contents of the list or map, but is a densely packed data structure used to reduce the cost of structural data sharing mutations to O(log(N)).

It may make sense to link to this resource from the site where you discuss how it works and the emergent behaviour of this design.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gniquil** [comment]
@leebyron Love this project. One thing related to the `===` is, is there no way to make strict equal work? Since all data structures are created via the `immutable` namespace, would it be possible at creation time, check a global cache (perhaps a weak map?), and see if the object already exists, if so, return a reference to the pre-existing object, rather than creating a whole new object?

**Comment by leebyron** [comment]
Unfortunately not, @gniquil - or at least not without severe performance and memory penalty.

For example, a global cache would require some sort of cache eviction policy. Having a cache at all requires a memory footprint, and a trivial cache would just grow endlessly, never allowing the GC to clean up any created collections. This would have large negative implications on most applications which use Immutable.js and heavily rely on the GC cleaning up after them.

Then there's the problem of determining how to key into the cache in the first place. This means once performing any operation, you will need to do a full hash and cache lookup, an O(N) operation on the size of the object being looked up. This would make every operation in Immutable.js O(N) which would be untenable from a performance point of view.

I believe a better forward path is for the JavaScript/ECMAScript technical committee to consider value types and overloading the `==` equality operator. This is a conversation that is happening for consideration in a future version of the language, so that we may map `==` to use `Immutable.is()` when the operands are Immutable collections.
