### ISSUE TITLE
When are hashes calculated or can traversal done by `.equals` be reused for further comparison.

### ISSUE THREAD

**Issue by Gozala** [facebook/immutable-js#360]
Omniscient (http://omniscientjs.github.io) that is react interface that embraces immutable.js and cursors provides custom implementation of `shouldComponentUpdate` to avoid re-renders unless where not necessary. Although it's implementation instead of differing comparison to `.equals` seems to prefer reference checks (you can ifnd relevant discussion https://github.com/omniscientjs/omniscient/issues/76).

I do believe there is an assumption that letting .equals run comparison on non-equal data structures may end up costing more than just re-triggering re renders.

I was assuming hashes were calculated during `.equals` but I was wrong, which got me thinking if there is a way to reuse comparison done on the root components for components down the pipe. What I mean if update has happened 10 level deep in the data structure, it will likely end up traversing same structure several time to do same comparison over, would be nice if somehow first traversal could be reused to optimise subsequent comparisons.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mschipperheyn** [comment]
+1 I would expect hashes to be calculated in stead of all attributes being processed each and every time. Should make a huge difference.

**Comment by leebyron** [comment]
Hashes are calculated only when explicitly necessary, since they're expensive to compute. They're calculated when being used as a key in a Map, as an example.

Always hashing when calling `equals` would always improve speed. Certainly the first call to `equals` for un-hashed values would face a penalty, as now we would not only be comparing equality but *also* computing these hashes. Also, in the cases that two are value-equal but not ref-equal it will compute matching hashes but still require comparing equality to ensure that no hash-collision has occurred.

I think the next step on something like this is to actually perform more research on the performance cost/benefit
