### ISSUE TITLE
Throw or warn when cursor is pointing to a primitive

### ISSUE THREAD

**Issue by Gozala** [facebook/immutable-js#361]
Currently you can create cursor to a primitive which is quite awkward as it implements same API as cursors to immutable structures but then does not quite works & in general tends to be confusing since actual underlying type interface and resulting cursor interface do not match.

I would suggest to either throw if cursor points to a primitive or just return primitive and dump a warning suggesting to use .get instead to get primitives.

**Comment by shivawu** [comment]
Agree, meeting the same problem.

If cursor points to a primitive, there's no way to update it directly right now, even with `withMutations`. Exceptions would be thrown because the primitive types like strings, don't have the same API with cursor or immutable collection, definitely a bug here.

Also considered with the API suggested in #249, I would suggest add a new cursor type like `PrimitiveCursor` to deal with primitive types and put the `set(value)` API there, and it doesn't need the same API with KeyedCursor or IndexedCursor.

**Comment by leebyron** [comment]
I actually made this change in v3, but changed back after significant push-back. In addition to further decoupling of the cursor API from this library, I think an API like #249 would be nice if cursors are to behave the same way they do today.
