### ISSUE TITLE
Comparison of 2 records that have `size` field that equals `undefined` fails with exception

### ISSUE THREAD

**Issue by zerkms** [facebook/immutable-js#362]
To reproduce just run:

    const C = Immutable.Record({
        size: undefined
    });
    
    var a = new C({});
    var b = new C({});
    
    Immutable.is(a, b);

Expected: it must run well

Actual: it fails with `Uncaught TypeError: undefined is not a function` which points to this line: https://github.com/facebook/immutable-js/blob/master/dist/immutable.js#L3885

    if (a.size === undefined) {
      if (b.size === undefined) {
        a.cacheResult(); // <--- this line
      } else {
        flipped = true;
        var _ = a;
        a = b;
        b = _;
      }
    }

**Comment by leebyron** [comment]
Thanks for the report!

**Comment by ellbee** [comment]
I've taken a quick look at this. The problem is that the supplied size key is clobbering the size key that immutable-js is adding to the prototype. This throws if set to undefined, but if it was set to a valid size (that is not the actual size of the collection) it could cause a bunch of more subtle errors. I don't have any good ideas here. Maybe the best thing is disallowing the use of size as a key name for Record Types?

**Comment by leebyron** [comment]
That's close to what I plan to do.

I also want to ensure that none of the other prototype methods are affected for the same reason, so I may use the prototype as a blacklist. Rather than throwing an invariant, I'll probably just not assign property descriptors for those keys, instead requiring that you access those keys via the `get()` method.

Either way, this will be a breaking change that will need to go into the next major version bump of immutable.js, and we may also need to include some way to opt out of this behavior in the case that you *want* to clobber the prototype.

In the short term, I will look into a way to mitigate the immediate issue reported here.

**Comment by leebyron** [comment]
Closed because this immediate issue should be resolved in https://github.com/facebook/immutable-js/commit/6b6074677ae986c92c793673ceb958bc130a76c2 but the larger issue of clobbering prototype property keys still exists.

**Comment by leebyron** [comment]
Tracking the larger issue in #377
