### ISSUE TITLE
How works the conversion from JS arrays/objects?

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/immutable-js#369]
> Designed to inter-operate with your existing JavaScript, immutable accepts plain JavaScript Arrays and Objects anywhere a method expects an Iterable with no performance penalty.
> This is possible because immutable can treat any JavaScript Array or Object as an Iterable.

I wonder what this exactly mean. I though that Immutable.js structures are always represented via tries structures. So I would expect that converting from JS Array/Object to Immutable would require some processing and creating these tries structures.  But quoted docs sounds like its using array/object directly.

So may I ask for brief explanation? Thanks!

**Comment by leebyron** [comment]
All Immutable.js collections implement the ES6 `Iterable` interface. JavaScript Array is in fact iterable in ES6-aware browsers (currently rare), but Immutable.js will wrap the array in a `Seq` in other browsers which is Iterable. Similarly for JS Object, as a convenience, will be wrapped in a `Seq` and iterated similarly to how an ES6 Map is iterated. These `Seq` wrappers have extremely low overhead, and are similar to the excellent [lazy.js](http://danieltao.com/lazy.js/) project in implementation.

All methods in Immutable.js which expect an `Iterable` argument internally have a simple check which first checks if the argument is Iterable, and if not, wraps it in a Seq so that it is Iterable before running the rest of the method.

Immutable collections are in fact Trie structures, and since they implement the `Iterable` interface directly, aren't wrapped in `Seq` when provided to these kinds of methods.

Does that help explain?

**Comment by jardakotesovec** [comment]
Thanks @leebyron . Really appreciated. As I have use cases when I don't need to update data much, but the additional Immutable.js interface is handy. So basically trying to understand if Immutable.js is good fit and does not come with significant overhead.

To make sure I understand. Lets say I have simple array `[1,2,3,4,5]` and I call `var list = Immutable.fromJS([1,2,3,4,5])`. At this point `list` is not represented via *trie* structure, but by original (wrapped) array, is that correct?  If so, when the conversion to tries is triggered - when some setter like `set()` is used?

Thanks!

**Comment by leebyron** [comment]
In that case, the expected output is an Immutable data structure - so yes, `fromJS` will create a Trie data structure from the array as input. An O(N) operation.

However, if you only want the API ( iteration and higher-order-function methods ) of Immutable, and you have no plans on actually updating that array, then creating the Trie might not be necessary. In that case, you would want to use a wrapping Seq directly.

```js
import { Seq } from "immutable"
var myArray = [1,2,3,4,5];
var list = Seq(myArray); // O(1)
list.get(2); // 3
```

The Trie data structures are really meant to be useful for persistent immutable data where updated versions are going to be created over time. You can update an immutable Trie in O(log<sub>32</sub>N) which is very close to O(1). Seq has no API for updates at all, it's designed to be read-only.

**Comment by jardakotesovec** [comment]
Thanks!
