### ISSUE TITLE
Functional API

### ISSUE THREAD

**Issue by joakin** [facebook/immutable-js#39]
I've been playing with the library and missed a functional API instead of a class based method one. To play with it i've made a little wrapper around the library that just adds the static methods to the classes making the last param the object on which the method will be invoked on.

[npm - immutable-fns](https://www.npmjs.org/package/immutable-fns)

That way we can do things like:

``` javascript
// On the immutable-js api
Immutable.Map({}).get('key')
// Added on this library
Immutable.Map.get('key', map)
```

``` javascript
var Immutable = require('immutable-fns');
var get = Immutable.Map.get;

// Create an immutable data structure
var m = Immutable.Map({a: 1});

// We can use the traditional api (obj.method(param)) or use the functional API
// (fn(...params, obj))
assert.equal(m.get('a'), get('a', m));
```

This kind of API is really useful sometimes, and doesn't conflict with the current API (that I have seen). This wrapper may serve to evaluate if this is worth pursuing on the library itself, and it does its job for the moment.

Thanks for your work on the immutable data structures, really hope to see them take off in js-land.

**Comment by ccorcos** [comment]
I'd love to see a functional API for immutable js!

**Comment by bwestergard** [comment]
Any developments on this?

**Comment by ccorcos** [comment]
Well this is an interesting option...

https://github.com/paldepind/functionize

**Comment by MoeSattler** [comment]
I'd love this. If there any current solution to a more functional API? I miss `pipe` and `compose` so much. 
Would definetly be up to contribute to a project tackling this.

**Comment by mikeaustin** [comment]
On a side note, what are people using to pair with immutable for compose, curry, flip, always/constant, etc? Ramda seems big and complicated. Crocks looks interesting, and also has ATDs such as Either and Maybe.

**Comment by iansinnott** [comment]
Many of Ramda's collection functions work quite well with immutable actually, since they dispatch to the relevant method if present. For example `R.map` and `R.filter`. That doesn't help with the relevant getters and setters of immutable, but you can use `R.lens` to gain at least some of the functionality you're looking for. [Here's a relevant article](https://medium.com/@drboolean/lenses-with-immutable-js-9bda85674780). This means you can build up functional pipelines using `R.compose` or `R.pipe` that work on immutable objects.

There's definitely a lot going on in Ramda but you can still import only what you need directly from the `src/` directory. Not as convenient as lodash but I believe there's a babel plugin which can automate this. Manual example:

```js
import map from 'ramda/src/map';
```

Not sure Ramda + Immutable is as seamless as many people would like but it's worked well enough for me for a while now.

**Comment by RichardForrester** [comment]
After doing a short exploration into point-free style with Immutable.js by manually creating some double-dispatch functions, I'm really interested being able to use Immutable.js in both object oriented and point-free styles.

leebyron stated that "I really like the idea of building a sister library which provides a functional curried API for all of the Immutable collection prototype methods" and ". . . if no one else gets to it first, I probably will write a fp wrapper for this library in the not-too-distant future :)"

ccorcos linked [functionize](https://github.com/paldepind/functionize) which on the surface seems like it would make creating such a sister library fairly trivial, i.e., all one would need to do is create a converter for Immutable.js. It's hard for me to believe that someone hasn't already done this, yet my google searches keep bringing me here.

Has this problem been solved already?
