### ISSUE TITLE
Integer values in keypath can clobber data in maps

### ISSUE THREAD

**Issue by WishCow** [facebook/immutable-js#392]
If you have an object that has integer keys, and you use setIn, with a keypath that includes an integer, it will clobber values:

```js
var Immutable = require('immutable');
var obj = Immutable.fromJS({ 5: { foo: 'bar' } });

var correct = obj.setIn(['5', 'baz'], 'qux');
console.log(correct.toJS());
// { '5': { foo: 'bar', baz: 'qux' } }

var incorrect = obj.setIn([5, 'baz'], 'qux');
console.log(incorrect.toJS());
// { '5': { baz: 'qux' } }
```
Is this expected behavior? I couldn't find any information about how keypath is defined, I just tried deducing it from the examples.

**Comment by leebyron** [comment]
This is correct behavior because toJS() coerces all keys to strings so the string key "5" and the numeric key 5 collide when creating the JS object. 

This is one example of how toJS() is lossy: JS objects can only have strings as keys where-as Map can have any value as a key.

**Comment by leebyron** [comment]
The key paths are both totally fine. If you log toString() instead of toJS(), or just otherwise manually inspect the resulting Map, you will see that both the string "5" and number 5 represent two different keys in the Map. 

Related, the JS object {5: "value"} has a string "5" as a key, not a number. JS objects cannot have numbers as property names, only strings.

**Comment by WishCow** [comment]
I see, it's the .toJS() call that is actually destroying data, makes sense, thanks.
