### ISSUE TITLE
Tests are slow

### ISSUE THREAD

**Issue by davidaurelio** [facebook/immutable-js#399]
The test suite runs rather slow, and I was wondering whether it is possible to speed it up.

I’ve tested different variants on MBPs from 2010 and 2008 (sorry, don’t have more recent hardware available atm):

CPU           | current state | [no typescript][] | [jasmine instead of jest, no typescript][]
---------------|-------------------|----------------------|--------------------------------------------
Core2Duo |     4m20.332s |       0m51.636s |     0m27.554s
i7 (2010)   |       2m1.904s |       0m24.786s |     0m23.579s

[no typescript]: https://github.com/davidaurelio/immutable-js/tree/no-typescript-in-tests
[jasmine instead of jest, no typescript]: https://github.com/davidaurelio/immutable-js/tree/no-jest-no-typescript

- The biggest offender is TypeScript, so the first question is: Do the tests really need to use typescript?

- The QuickCheck-style tests (with jasmine-check) take their time. I think it might be worth considering moving those to a separate suite. That way, there’d be a really fast running test suite that gives quick feedback (< 5 seconds) during development, and the jasmine-check-suite that can be run on occasion and by CI. 

- I don’t know why jest is slow on old hardware, but I guess that matters only to me when working on my ancient machine.

**Comment by robertknight** [comment]
I had a look at this. I don't think the problem is TypeScript inherently but the way it is being used. The current version of the compiler can compile all the .ts files in the test suite in ~2.3s on my i5 system, whereas the whole test suite takes about >100s to run.

There is a general issue on Jest's issue tracker at https://github.com/facebook/jest/issues/116 about performance. I haven't looked into that closer so I can't say how much of that is relevant.

**Comment by leebyron** [comment]
After @robertknight's diff, tests run 3x faster on travis-ci, which uses jest's inline mode. It's closer to 4-5x faster on my MPB. Still on the order of tens of seconds, but much better than the > minute.
