### ISSUE TITLE
Support toJS/toArray on iterators?

### ISSUE THREAD

**Issue by snickell** [facebook/immutable-js#404]
It'd be really convenient, esp for interactive console work, if the toJS() and/or toArray() methods were implemented on iterators. Its much easier to chain commands from the console (i.e. append to previous text) than nest functions (balance parens, etc), and also avoids having to have a reference to Immutable from the console in order to explore immutable data structures.

```
// This is a lot easier to type on the console....
someMap.keys().toJS();

// than this...
require('Immutable');
Immutable.List(someMap.keys()).toJS();
```

**Comment by leebyron** [comment]
`Seq` have a full collection API, so you could at least type out as:

```js
someMap.keySeq().toJS()
```

I'd like to keep the Iterator as simple as possible - in the future I'd like them to be true ES6 IteratorPrototype, so I hesitate on adding much to them.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by dpwrussell** [comment]
I think this is the right decision, but I think there should be a change in the docs to add the `Iterator` so that it's possible to see what that interface looks like.

It's easy to see something like `keys(): Iterator<K>` and then click on `Iterable` in the docs (which supports toArray/toJS) and then be confused why it isn't working. Obviously it's because `Iterator` and `Iterable` are not the same thing, but the abscence of `Iterator` in the focs makes it make this mistake.

Cheers

**Comment by ethanresnick** [comment]
:+1: on the docs change. I ran into this issue exactly as @dpwrussell described!

**Comment by snickell** [comment]
Having Iterator documented would be VERY helpful
