### ISSUE TITLE
mergeDeep doesn't work with Immutable.Map

### ISSUE THREAD

**Issue by jsurdilla** [facebook/immutable-js#422]
Maps created from Immutable.fromJS() and Immutable.Map are inconsistent with their mergeDeep behavior. The Immutable.fromJS one seems to be the correct of the two.

    var a1 = Immutable.fromJS({ a: 1, b: 2, c: { c1: 3, c2: 4 } })
    var b1 = Immutable.fromJS({ a: 10, b: 20, c: { c3: 30 } })
    a1.toJS().c // Object {c1: 3, c2: 4}
    b1.toJS().c // Object {c3: 30}
    a1.mergeDeep(b1).toJS().c // Object {c1: 3, c2: 4, c3: 30}

    var a2 = Immutable.Map({ a: 1, b: 2, c: { c1: 3, c2: 4 } })
    var b2 = Immutable.Map({ a: 10, b: 20, c: { c3: 30 } })
    a2.toJS().c // Object {c1: 3, c2: 4}
    b2.toJS().c // Object {c3: 30}
    a2.mergeDeep(b2).toJS().c // Object {c3: 30}

**Comment by leebyron** [comment]
This is intentional. There are two things going on here:

1. `fromJS()` deeply converts a JS object & array tree to Map and List. `Map()` (and the other factories) do not convert deeply.
2. `mergeDeep()` treats non Immutable Collections as opaque references and does not attempt to merge them.

`Map()` does not do deep conversion, only shallowly uses the provided object keys to build the map. For example, if you had custom objects in your application (say for example, React components), and wrote:

```js
var myCustomObj = new MyCustomObj();
var myMap = Immutable.Map({ "key": myCustomObj });
assert(myMap.get("key") instanceof MyCustomObj);
```

You would expect this to pass. If Map() did deep conversion, then your MyCustomObj would get iterated over and flattened into a Map.

So in your example:

```js
var a2 = Immutable.Map({ a: 1, b: 2, c: { c1: 3, c2: 4 } })
console.log(a2.toString()); // Map { "a": 1, "b": 2, "c": [Object object] }
console.log(a2.get("c") instanceof Map); // false
```

Immutable.js will treat that inner Object as an opaque object reference - it can't know enough about all objects to assume what kind of merge strategy to use, so it does the only thing that would be safe and predictable: it replaces the reference with the new reference:

```js
a2.mergeDeep(b2)
```

When it encounters the `"c"` key, it sees the existing `[Object object]` and replaces that reference with the  value of `"c"` in `b2`, which is the Object reference `{ c3: 30 }`.

**Comment by leebyron** [comment]
Also, just a tip while debugging:

`toJS()` is lossy, and can therefore make it difficult to see the true structure of Immutable collections. Some things you won't see when using toJS() to print values in a console:

* Difference between Record, Map, OrderedMap, JS Object reference.
* Difference between List, Set, JS Array reference.
* Non-string Keys of a Map, such as numbers.

`toString()` should help preserve all of this kind of information and can be helpful when peeking into a data structure.

**Comment by jsurdilla** [comment]
Thanks for the clear and detailed explanation!

The (simplistic) map I used coupled with `toJS()` is what made it tricky to see the issue. Had I used *.get('c') instead of *.toJS().c, it would have been easy to spot the difference in behavior.

Thanks again!

**Comment by ChristopherRabotin** [comment]
I don't think this is in the documentation, and definitely think it should be. I have been struggling with this for a good twenty minutes trying to figure out why the following initialization would be overwritten.
```
const initialState = Map({
  user: {info: null, error: null, loading: false}
})
state.mergeDeep({user: {loading: true}}) // state = Map{user: {loading: true}}
```

**Comment by mitermayer** [comment]
Whats the solution to get the intended result ?

**Comment by gregogalante** [comment]
No solution?

**Comment by valeriemng** [comment]
:(
