### ISSUE TITLE
Is an Immutable.List an appropriate name for the data structure ?

### ISSUE THREAD

**Issue by Gozala** [facebook/immutable-js#427]
I find name `Immutable.List` to be confusing. I was able to find this announcement that kind of explains reasoning behind the rename https://github.com/facebook/immutable-js/wiki/Upgrading-to-Immutable-v3#list-from-vector

Lists are usually name used for Linked Lists that Immutable.List are not really related to, there for I question if such a name is actually an appropriate. I could argue that `Immutable.Array` maybe even a better choice here since as both API and characteristics seem to match Array more than List.

**Comment by leebyron** [comment]
I think there's bound to be confusing no matter which direction we go. Vector was confusing to some before because it implied a certain kind of data structure and the properties associated with that data structure. Array is confusing because it's not the same API as JavaScript's Array (notably, no [] access). List does refer to Linked-List in some languages, but also refers to the abstract type of collection in other languages - abstract from any implementation. Tuple also fits this description, but is often used to describe lists of a fixed size where each index holds a different kind of value. Again, potentially causing confusion.

We can bike shed on this as much as we want, but in terms of practical things we can do, changing the name of this kind of collection in a future version of Immutable.js would be pretty high friction and not valuable unless the confusion around List is high and there's an obvious alternative to use, which I don't think there is.

I think the least confusing thing to do is to leave it as is.

**Comment by Daniel15** [comment]
I think List is fine, both C# and Java call their data structure a list.

**Comment by Gozala** [comment]
> I think List is fine, both C# and Java call their data structure a list.

To be fare only thing that List here has in common with List from those languages is a name :smiley: 

My main concern is that immutable data structures that this library implements originate from functional languages where name `List` refers to a very specific data structure with a very different characteristics.

**Comment by leebyron** [comment]
I understand your concern. I think it's a good concern - I'm just don't think it's detrimental enough that it warrants a large change to the library.
