### ISSUE TITLE
Include src dir in NPM, allowing require('immutable/src/Map')

### ISSUE THREAD

**Issue by sebastienbarre** [facebook/immutable-js#438]
In the spirit of shaving a few bytes [lodash](https://lodash.com/) has per-method exports, i.e. one can:

```
  var _map  = require('lodash/collection/map');
```

instead of:

```
  var _  = require('lodash');
```

Would it be possible to achieve the same with Immutable, i.e.

```
  var ImmutableList = require('immutable/src/List');
```

instead of: 

```
  var Immutable = require('immutable');
```

Would it provide some benefits or is everything too interlinked?
I realize the `src/` dir is mostly ES6 code, but I use babel/webpack which lets you import ES6 code (though Babel 5.0 does complain about the lack of `super()` calls when I tested earlier).

**Comment by vjpr** [comment]
+1

**Comment by leebyron** [comment]
Since there are only a small number of collections now, there's unlikely to be many bytes shaved. In some earlier experiments I found that doing something like this could save about 1.5KB from the 15KB total if you only used Map and never List or vice-versa, but if you used both it could add up to 4KB *more* because of the overhead of babel/webpack vs the current inlined build.

This is something I want to keep on deck for a future v5.0 where I hope to simplify the API and factor some functionality into separate pieces.

Also, as new collections are added in the future - the value of this will improve.

**Comment by sebastienbarre** [comment]
@leebyron Thanks Lee, I suspected as much. Do you prefer I close this issue, or leave it for 5.0?

**Comment by leebyron** [comment]
I'll leave it open for 5.0. There's a PR exploring this directly

**Comment by petermikitsh** [comment]
> could save about 1.5KB from the 15KB total

Every little bit counts. I've been going through my webpack project, cleaning up my imports, and have shaved ~100kb off my minified builds. I think this would be a valuable to consider.

**Comment by leebyron** [comment]
Unfortunately this is not yet possible - perhaps in a future version
