### ISSUE TITLE
Immutable all the way down

### ISSUE THREAD

**Issue by AsaAyers** [facebook/immutable-js#473]
Is there any mechanism to enforce that everything is recursively immutable? I can pass everything through `Immutable.fromJS(...)` and then pass that through, but it gets inconvenient to have to remember to do that everywhere.

``` javascript
tmp = Immutable.List.of({name: 'foo'})
tmp2 = tmp
tmp2.first().name // "foo"
tmp2.first().name = 'bar'
tmp.first().name // "bar"

// It seems like the right way to do this is:
tmp = Immutable.List.of(Immutable.fromJS({name: 'foo'}))
```

**Comment by AsaAyers** [comment]
I don't know if this belongs in the same issue or not, but I'm also wondering if it's possible to convert to particular types. If not, do you have any advice on how this can be done? (Or reason I don't know why this may be a bad idea?)

```
NameRecord = Immutable.Record({name: null});
tmp = Immutable.List(/* of NameRecord objects */)
tmp = tmp.push({name: 'foo'}) // implicit conversion here?
tmp.first() instanceof NameRecord // currently false, but would be nice if it were true
```

**Comment by ifunk** [comment]
You should use an array of objects to create "immutable all the way down".
```javascript
tmp = Immutable.fromJS([{name: 'foo'}]);
```
As for record type conversion, Immutable.List doesn't require all object types to be identical, so it can't automatically type this for you. You should do this yourself.
```javascript
tmp = Immutable.fromJS([new NameRecord({name: 'foo'})]);
```
Alternatively
```javascript
// create a list of immutable maps
tmp = Immutable.fromJS([{name: 'foo'}]);

// cast all of the maps to NameRecord
tmp = tmp.map(function(obj) {
    return new NameRecord(obj);
});

// add a new NameRecord
tmp = tmp.push(new NameRecord({name: 'bar'}));
```

**Comment by AsaAyers** [comment]
Now that I've given this a bit more thought, I guess what I'm really trying to figure out is, can I extend the Immutable types so that I can do something on every... mutation is the wrong word, but mutation.

```
tmp = myCustomList()
tmp.push({name: 'push'})
tmp.set(1, { name: 'set'})

parent = Immutable.Map()
parent.mergeDeep({ myList: [ {name: 'mergeDeep' } ]})
```

I looked through the code, but I'm just not seeing a central function I could override that looks like it would catch all the different ways of adding values to immutables.

**Comment by ifunk** [comment]
Sounds what you're really after is a RecordSet class (extending List) that takes a Record as object type. You would prob need to override all of the change methods and cast the object before sending it to your parent method.

You might run into issues with some of the merge methods however, if object depth is unexpected.

Using ```mergeIn``` might be good enough for your purposes of "mutating" a record instance.

```javascript
var tmp = Immutable.List();
tmp = tmp.push(new NameRecord({name: 'push'}));
tmp = tmp.mergeIn([0], {name: 'set'});
```

**Comment by ifunk** [comment]
Just saw this [interesting conversation](https://github.com/facebook/immutable-js/issues/407) with a result of a new library being developed.

https://github.com/Gozala/typed-immutable

**Comment by leebyron** [comment]
Yeah, @Gozala and I have been discussing ways to add these sorts of constraints correctly. #407 has a lot of interesting discussion as we investigate.

Part of the difficulty in getting this right is that it's pretty common to actually want to refer to a plain JS object within an immutable collection. For example, when mapping over an Immutable collection to produce React elements, you're producing plain JS objects - and if some flag was set to disallow plain JS objects, then we couldn't use Immutable.js with React anymore. Or at least not nearly as clearly.

Part of what doesn't feel right here is purely syntactical. Typing `Map({key: "value"})` is just more verbose than typing `{key: "value"}` so I definitely understand the desire to type what is syntactically most simple.

I'm definitely open to more discussion on this front - and hear out any interesting ideas people have.

**Comment by jareware** [comment]
> it's pretty common to actually want to refer to a plain JS object within an immutable collection

This is true, but this also carries the potential for very difficult-to-debug Heisenbugs; you assume your entire tree of references is immutable because the root is, but somewhere along the line someone sneaked in a mutable reference, and many of the nice guarantees immutable data structures give you no longer hold.

As to typing only `{key: "value"}`, there's many API's which could still work this way, even if the setters enforced immutability. Merging `{key: "value"}` into a Map would still be safe, but merging `{key: {nested: "value"}}` wouldn't.

I would be **very** happy being able to enforce this "deep purity" somehow. Not really sure what the API would look like, though... Should there be e.g. `Map` which works as it does now, and a `PureMap` or something which would enforce immutability for values?

**Comment by AsaAyers** [comment]
I found a solution that seems to be working for me. I'm using an `Immutable.Map()` to store data and there's only one place it can get updated. In development mode I call `verifyImmutable()` to produce an exception if it finds any mutable objects or arrays.

```
function verifyImmutable(oldObj, newObj, path=[]) {
    for (let key of newObj.keys()) { // eslint-disable-line prefer-const
        const value = newObj.get(key)
        const oldValue = (oldObj === undefined) ? undefined : oldObj.get(key)

        // There's no need to check branches that haven't changed.
        if (!Immutable.is(oldValue, value)) {

            if (value instanceof Collection) {
                const currentPath = path.concat([key])
                verifyImmutable(oldValue, value, currentPath)
            } else if (value instanceof Array || value instanceof Object) {
                const currentPath = path.concat([key])

                throw new Error('The store must contain only immutable objects.'
                    + 'Mutable Array or Object found at: '
                    + currentPath.join('.'))
            }
        }
    }
}

export function replace(newStore) {
    if (newStore instanceof Map) {
        if (newStore !== store) {
            if (process.env.NODE_ENV !== 'production') {
                verifyImmutable(store, newStore)
            }

            store = newStore
            ee.emit('CHANGE')
        }
    } else {
        throw new Error("InvalidArgument: newStore must be an update to the existing store")
    }
}
```

Maybe it would be better to just have a utility function like this to verify deep immutability instead of trying to enforce it. This allows me to safely map over any of my structures to produce whatever I need to, I just can't push mutable data to my central store.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Sidnicious** [comment]
As a new user of Immutable, I expected it to be strict and deeply convert JS objects when I insert them. I got bitten very quickly:

```js
var map = Immutable.fromJS({ a: [0, 1, 2] });
map.getIn(['a', 1]); // → 1
map = m.set('a', [1, 2, 3]);
map.getIn(['a', 1]); // → undefined
```

`m.merge({ a: [1, 2, 3] })` would've worked — it *does* deeply convert — and I don't grok why they behave differently. I also didn't expect `getIn()` to fail silently when I tried to descend into a JS array.

Maybe it would make sense to have a pointer or box type that would let regular objects be stored (explicitly) in an Immutable collection, but I think that otherwise they should be Immutable all the way down.

**Comment by JohannesHoppe** [comment]
So i just stumbled across this issue of not enforced immutability. and the thread is pretty old!
are there any plans to to avoid this pitfall?

**Comment by leebyron** [comment]
Closing this aging issue.

For those looking for guarantees about deep immutability, I strongly suggest using Flow or Typescript so that you can provide static type checks making guarantees about what kinds of values are passed around your program. For our products at Facebook this has effectively solved this sort of issue for us.
