### ISSUE TITLE
Option / Maybe structures

### ISSUE THREAD

**Issue by ryoppy** [facebook/immutable-js#476]
what do you think implements Option(scala) or Maybe(haskell).

just code image.

```
class Option<A> extends Iterable<A>
  constructor: (value) ->
    if value is null or undefined
      None
    else
      Some(value)

class Some<A> extends Option<A>

class None extends Option<Nothing>
```

action image.

```
Option(1).map((i) -> i + 1)
# Some(2)
Option(null).map((i) -> i + 1)
# None
Option(1).map((i) -> i + 1).filter((i) -> i == 9)
# None
```

and more

```
Seq([1,2,3]).find((i) -> i == 2)
# Some(1)
Seq([1,2,3]).find((i) -> i == 9)
# None

Option(1).getOrElse(0)
# 1
Option(null).getOrElse(0)
# 0
```

**Comment by Laiff** [comment]
+1
It would be a great feature , but violates api , possibly worth giving the ability to disable this functionality.

**Comment by leebyron** [comment]
I'm a big fan of the Option structure, but I think it's beyond the scope of the purpose of this library.

I think https://www.npmjs.com/package/option is pretty simple and useful.

Having the prototype methods return these structures is bit more complicated, as @Laiff points out that would be a breaking change and it's also not very idiomatic. Most javascript programs (for better or worse) expect to operate with the null and undefined primitives as a sentinel for "none", and since Immutable.js strives to be idiomatic when possible - I don't think a change like this will be appropriate.
