### ISSUE TITLE
List `.update()` mutates original list instance 

### ISSUE THREAD

**Issue by voronianski** [facebook/immutable-js#481]
Consider this demo code:

```javascript
var items = Immutable.List([{a:1, b:[{c:1}]}, {a:2, b:[{c:2}]}]);

var index = 1;
var newItems = items.update(index, function (item) {
   item.b = [{c: 22}];
   return item;
});

console.log(items === newItems);
// true..

console.log(items.get(index), newItems.get(index));
// both objects are updated..
```

This behavior looks strange to me. I'm expecting list to be immutable actually..

===

Few words on my practical case - I have some "items" as array of data in Flux store and on user's action some object from it can be updated with new data received from REST API.

**Comment by leebyron** [comment]
In this case the list itself is not being mutated. The list contains the same references to JavaScript objects before and after the operation.

In this example the list elements are mutable JavaScript objects and your update operation is mutating the JavaScript object held at the index, however the object is still the same object. In this case we can say this list is not "deeply immutable". In many cases this is preferable, but I assume you are expecting to be operating on deeply immutable data. 

Immutable.List() is a shallow constructor. It accepts an array of anything and creates an Immutable List of those same things, and makes no assumptions about what those things are - mutable or immutable. 

If you want to deeply convert nested JavaScript arrays and objects to become a deeply immutable nested List and Map, you should use Immutable.fromJS(). 

Once deeply immutable, an update operation which alters an immutable item in the list will result in a new item with that update operation applied (editing the "b" key in your example), and the new list will have to refer to this new item in the same position, and so you will get a new list with the update applied as the result of the "update" method.

**Comment by voronianski** [comment]
@leebyron thanks a lot for such descriptive response. However I've change my example code to `Immutable.fromJS` instead of `List` and result was the same.

```javascript
var items = Immutable.fromJS([{a:1, b:[{c:1}]}, {a:2, b:[{c:2}]}]);

var index = 1;
var newItems = items.update(index, function (item) {
   item.b = [{a: 456789}];
   return item;
});

console.log(items === newItems);
// true..

console.log(items.get(index), newItems.get(index));
```

**Comment by leebyron** [comment]
The issue in your example is the line `item.b = [{a: 456789}];`. There are two issues.

The first issue is that `item.b = ...` is a mutative operation on a JavaScript object, rather than part of the Immutable.js API. You should notice when inspecting newItems.get(index) that in fact the "b" item in the map has not changed, but that instead you've mutated the implementation of the data structure with a b property that isn't be used anywhere by Immutable.js. If you want to do a set operation you need to use the `set` method: `item.set('b', ...)`. After changing your code to use Immutable.js `set` method instead of the JavaScript mutative property setter, indeed `items !== newItems`.

```js
var items = Immutable.fromJS([{a:1, b:[{c:1}]}, {a:2, b:[{c:2}]}]);

var index = 1;
var newItems = items.update(index, function (item) {
   return item.set('b', [{a: 456789}]);
});

console.log(items === newItems);
// true..

console.log('old: ' + items.get(index));
console.log('new: ' + newItems.get(index));
```

The second issue is that when setting to `"b"` in `item`, you're setting a JavaScript array of a JavaScript object, not an Immutable.js List with a single Immutable Map. While this might be fine in some circumstances, my guess is that is probably not what you intended considering that the previous value was an Immutable.js List and Map. The second console.log in that prior block of code will emit:

```
old: Map { a: 2, b: List [ Map { c: 2 } ] } 
new: Map { a: 2, b: [object Object] }
```

So again you probably mean to be constructing Immutable.js collections there either by doing so explicitly: `List([ Map({ a: 456789 }) ])` or via conversion: `fromJS([{a: 456789}])`

**Comment by leebyron** [comment]
Another tip - when doing these kinds of deep edits, the `*In` collection of methods are really useful - in this case you could replace the `update` and `set` combo with `setIn`:

```js
var items = Immutable.fromJS([{a:1, b:[{c:1}]}, {a:2, b:[{c:2}]}]);

var index = 1;
var newItems = items.setIn([index, 'b'], Immutable.fromJS([{a: 456789}]));

console.log(items === newItems); // false

console.log('old: ' + items.get(index));
console.log('new: ' + newItems.get(index));
```

**Comment by voronianski** [comment]
@leebyron thanks a lot! Great examples!

**Comment by voronianski** [comment]
@leebyron what if I want to update several properties inside object from list? `setIn` is not capable with that?

**Comment by leebyron** [comment]
`mergeIn` is probably what you're after for that. There's also `mergeInDeep` which will apply deeper merges.

**Comment by reduxdj** [comment]
Man, can you girls/guys please please please update the immutable.js documentation with these examples? I'm sure one of your 100 front end engineers has the time - please - thanks.

**Comment by lacker** [comment]
@reduxdj AFAICT these functions are already documented. Which page on the docs do you think should be better? Also pull requests are welcome - if you tag me on a docs PR then I promise I will review it real soon :P
