### ISSUE TITLE
Doubt about Min/Max functions

### ISSUE THREAD

**Issue by pedroteixeira** [facebook/immutable-js#482]
Right now:
`Immutable.Set.of(10, null).min()` returns null
`Immutable.Set.of(10, null).max()` returns 10
`Immutable.Set.of(10, NaN).min()` returns NaN
`Immutable.Set.of(10, NaN).max()` returns NaN

I know we're using js for comparison, but the result seems somehow unexpected. Just wanted to bring this to attention, because it seems that the strategy to ignore nulls and NaNs for min e max seems legit for all cases, right? I mean that, if, most user code would tend to .filter null/NaN before calling min/max, isn't better to put the extra check inside min/max? 

I know it's ok to continue letting NaN poison all operations, and let the user ensure correct values or filter null, etc. Just a comment, because data structure libraries can avoid bugs with decisions like these.

[]'s

**Comment by samwgoldman** [comment]
```
> Math.min(10, null)
< 0
```

Even if the idea is to mimic `Math.max` and `Math.min`, it seems like there's a bug in your first example. It would appear that the candidate values should be converted to a number before comparison.

**Comment by pedroteixeira** [comment]
The idea would *not* be to mimic default Math.max e Math.min. I consider currrent Immutable behaviour to be better. The question is if it's better to return filter only numbers for max/min (outcome of 10 in the examples I wrote before)

**Comment by leebyron** [comment]
Immutable.js hopes to mirror Math.min/max behavior as far as ordering goes, though min/max for collections may be comparing things other than numbers, which is why the return values are not the same as Math.min/max - those methods always coerce to numeric values to compare where Collection min/max does no numeric coercion. 

It is intentional that NaN is poisonous as it's meant for error propagation. NaN is usually a surprising value and you don't want to mask over errors by default - but instead handle them explicitly when they're possible.
