### ISSUE TITLE
List concat performance

### ISSUE THREAD

**Issue by xixixao** [facebook/immutable-js#484]
First of all, let me prefix this by saying that I haven't looked into Immutable.JS implementation so I might be doing something wrong/expecting the wrong thing. First the results:

Using reduce and concat to perform what is called flatten in Immutable. Immutable.JS version:
```javascript
xs = Immutable.Range(0, 700).toList();
item = Immutable.Range(0, 50).toList();
bigList = xs.map(x => item);
t = +new Date();
bigList.reduce(((x, v) => x.concat(v)), Immutable.List([]));
new Date() - t
```
Runs in over 3 seconds (tested in FF).

Vanilla JS version:
```javascript
xs = Array.apply(null, Array(700)).map(function (_, i) {return i;});
item = Array.apply(null, Array(50)).map(function (_, i) {return i;});
bigList = xs.map(x => item);
t = +new Date();
bigList.reduce(((x, v) => x.concat(v)), []);
new Date() - t
```
Takes about 250ms.

Now of course I wouldn't write this code by hand, I'd use flatten. I am just using this as a benchmark. I would like to know why Immutable is so much slower and whether it's to be expected. I would also like to know in general how Immutable's List compares in performance to native Array. Thanks.

**Comment by leebyron** [comment]
This is about the constant time speed difference I would expect. Native Array is full of performance optimizations and relies on mutability which will always beat immutable data in raw numbers. On average Immutable.js operations are a constant time 5-15x slower than native operations, depending on the operation. In part due to their being implemented directly in JS rather than in the VM, but also because the operations themselves are more involved.

The performance wins (both time and memory) come from opportunities to use structural sharing between operations, which unfortunately `concat` currently does not provide.

**Comment by xixixao** [comment]
Thanks for the answer. I imagine that concat would be a good candidate for structural sharing?

I also wonder whether it would make sense to use native data structures for backing small collections and only switch to tries when the collections hit a certain size. I would also love to know how @swannodette's mori is doing in comparison (again, in general). 

Perhaps the answer for my use case is to switch to laziness, which unfortunately became more difficult with Immutable 3...

**Comment by leebyron** [comment]
You're correct that `concat` is a good candidate for structural sharing, and in fact there is pretty great research on how to do this - #38 is tracking this enhancement that I'm excited to have in the future.

The stock `flatten` implementation does in fact use laziness and that's likely to win back a lot of performance for this scenario.

```js
// Immutable.JS flatten
xs = Immutable.Range(0, 700).toList();
item = Immutable.Range(0, 50).toList();
bigList = xs.map(function (x) {return item});
t = +new Date();
bigList.flatten();
console.log(new Date() - t);

// Immutable non-lazy raw Array flatten
xs = Array.apply(null, Array(700)).map(function (_, i) {return i;});
item = Array.apply(null, Array(50)).map(function (_, i) {return i;});
bigList = xs.map(function (x) { return item; });
t = +new Date();
bigList.reduce(function(x, v) { return x.concat(v) }, []);
console.log(new Date() - t);
```

On my machine, the non-lazy raw Array flatten (your original code) ran in 33ms, but Immutable.js's `flatten` method ran in 20ms due to utilizing laziness under the hood - it avoids building the intermediate data structures.

mori uses many of the same techniques as Immutable.js (in fact, Immutable.js was inspired by ClojureScript's data structures) and has a similar performance profile, but also has undergone a lot more performance tuning and so that constant time slow down relative to mutable native arrays is more like 4-8x for mori (depending on the operation). ClojureScript (and mori) also do not yet feature RRB trees for enabling structural sharing in the concat case as far as I know.

**Comment by xixixao** [comment]
For future reference, I was obviously using `flatten` completely wrong, since what I wanted was Haskell's `concat`, so the fast way to do this is:
```javascript
bigList.first().concat.apply(bigList.first(), bigList.rest().toArray());
```
provided the outer collection isn't empty.

**Comment by Josie2015** [comment]
I don't know why I get this scripting for email or texting. If u know how
to decode script messages that would help me tremendously..

**Comment by Josie2015** [comment]
I sent you a message on Skout http://skout.com/d/cuPiD/
