### ISSUE TITLE
Unexpected indexOf() on List of same type elements.

### ISSUE THREAD

**Issue by vtambourine** [facebook/immutable-js#503]
List#indexOf returns unexpected result if List consists of custom type elements.

Consider following example:
```javascript
var one = new Immutable.Record();
var two = new Immutable.Record();
var list = Immutable.List([one, two]);

console.log(one === two); // false
console.log(list.indexOf(one)); // 0
console.log(list.indexOf(two)); // 1
```
This works well. Both `one` and `two` are similar empty Records, but they are not equal. `one` is first element of `list`, `two` is second element.

Something goes wrong if custom types are used:
```javascript
var Type = Immutable.Record({});
var one = new Type();
var two = new Type();
var list = Immutable.List([one, two]);

console.log(one === two); // false
console.log(list.indexOf(one)); // 0
console.log(list.indexOf(two)); // 0, but should be 1
```
For some reason, `one` and `two` appears to be on the same place in the list. What is going on? Is that expected behaviour?

**Comment by leebyron** [comment]
I believe the issue here is that your first example is mis-using the record API.

```
var one = new Immutable.Record();
```

This line of code will create a new *type* of record `one`. `one` is a function that when called will produce record values.

In your second example, you're using the record API correctly (though just a minor note, `new` is not necessary when calling these functions, but harmless). In those cases `one` and `two` are record *values*. We can use value equality to compare them.

*Value* is an important part of what is going on here. Lots of the objects Immutable.js creates are treated as values by the Immutable.js APIs. The most important difference is in how equality is determined. `one === two` will always return false here because `===` means object reference identity. However if you wrote `one.equals(two)` or `Immutable.is(one, two)`, then you should get `true` as they are equivalent *values*.

Immutable.List's `indexOf` API uses value equality rather than object identity to find the matching index in the collection, and since `one` and `two` are value-equivalent, the first one encountered by `indexOf` is returned, which is why you're getting `0`.

Please let me know if that's unclear, or if there's anything else I could do to make this sort of behavior more evident either via the API itself or via the documentation.

**Comment by vtambourine** [comment]
Thank you for explanation!

I was confused by example of `===` equality for Maps from documentation. It show following example:
```js
var one = Immutable.Map({a: 1});
var two = one.set('a', 1)
console.log(one === two); // true
```
It looks like `one` and `two` compares by values resulting they're equal. Previously didn't notice text about `Immutable` always returns itself on trivial mutation. I thought if `one.set('a', 1)` is equal to `one`, so `one.set('a', 2).set('a', 1)` must be equal. Obviously, it must not.

**Comment by vtambourine** [comment]
Can you please explain me one more thing. Is it possible to use `indexOf` to search for reference?

For example, in my project I need to maintain list of editable objects. On certain event, like clicking on item on page, I copy selected object to another variable and mutate object's fields on that variable. By that, when edition completes and updates are not discarded, I still have fresh new object and reference to original. Now I want to replace original object to the new in the list. Is it possible to know index of object in the list without storing index separately? Is it possible to have something like:
```js
var i = list.indexOfRef(object);
list = list.set(i, newObject):
```

**Comment by leebyron** [comment]
`indexOf` uses `Immutable.is` to determine if it's found a match. That uses an `equals` method on each item if it finds one, which means if `object` in your example is an Immutable.js value, that it will use value equality not reference equality.

If you want to use reference equality instead, you could certainly write a bit of code to do that using `findIndex` which will let you define your own function to decide what is "found"

```js
var i = list.findIndex(item => item === object);
```
