### ISSUE TITLE
What is the expected result when comparing Set and OrderedSet?

### ISSUE THREAD

**Issue by kentor** [facebook/immutable-js#508]
`Immutable.is()` returns `false` when comparing an `OrderedSet` and a `Set` with the same elements. I had expected this to be `true`:

``` node
> Immutable.Set('a').equals(Immutable.Set('a'))
true
> Immutable.OrderedSet('a').equals(Immutable.OrderedSet('a'))
true
> Immutable.OrderedSet('a').equals(Immutable.Set('a'))
false
```

Even if my expectations were wrong, it seems like we can't convert an OrderedSet to a Set

``` node
> Immutable.Set(Immutable.OrderedSet('a'))
OrderedSet { "a" }
```

Unless we do something like:

``` node
> Immutable.Set(Immutable.OrderedSet('a').toSeq())
Set { "a" }
```

and then use `is()`. Maybe there should be an easier way to test if an OrderedSet and a Set contain the same elements?

**Comment by tgriesser** [comment]
Ran into this the other day as well with Map / OrderedMap. It seems like this is a bug, at least when comparing with the analogous clojure behavior.

```js
(def a {2 :two 1 :one})
(def b (into (sorted-map) a)) // {1 :one 2 :two}
(= a b) // true
```

**Comment by kentor** [comment]
Ah... well it turns out that I had references to two Sets to begin with, but one reference turned into an OrderedSet.

Here's the culprit:

```node
> Immutable.Set().union(Immutable.OrderedSet([1]))
OrderedSet { 1 }
```

An empty Set union'd with a non empty OrderedSet returns an OrderedSet. 

I hope this is a bug?

**Comment by leebyron** [comment]
Hmm let me look more closely at this. Equality checking currently takes into consideration if both sides are ordered or not. If neither side has defined ordering, it just looks for the same values in the sets (or entries in the maps) - but if one has ordering and the other does not - they cannot be considered equivalent because the iteration ordering will be different between the two.

@tgriesser how does this reconcile with clojure's equality semantics?

**Comment by tgriesser** [comment]
I did a bit of searching and couldn't find anything too concrete about the reasoning, though the best explanation I could find came from this [stack overflow post](http://stackoverflow.com/a/11006759/525714)

I think maybe the simplest way to think of it would be in terms of EDN's definition of [equality](https://github.com/edn-format/edn#equality) - there is no concept of sort order maintained in reading/writing of a data structure to EDN, it's purely a runtime construct.

> sequences (lists and vectors) are equal to other sequences whose count of elements is the same, and for which each corresponding pair of elements (by ordinal) is equal.

> sets are equal if they have the same count of elements and, for every element in one set, an equal element is in the other.

> maps are equal if they have the same number of entries, and for every key/value entry in one map an equal key is present and mapped to an equal value in the other.

So yep, in Clojure it seems as though if both objects are a Set or both are a Map, the sort order is ignored in equality.

Possibly relevant, commit I came across in cljs to [change the hashing algorithm](https://github.com/clojure/clojurescript/commit/6fd16df50bca7a6118693712e6918c70a64de255) 
> "so that the various map types hash to the same value when equal, independent of insertion ordering and the like and without sorting of keys."

**Comment by tgriesser** [comment]
@leebyron any thoughts on whether you'd want a change in behavior on this? 

It's a simple patch, but was waiting to hear what you thought since it'd be a breaking change.

**Comment by leebyron** [comment]
It looks like the bug here is probably the unstable return type in union() if one is empty: the return type should always be the left hand side. Though I thought we had fixed that.

As far as equality goes, I know there are many definitions for equality (and ultimately many equality functions in some languages). However the equals() and is() functionality here should be "A could replace B for any operation, and produce the same result" - in which case OrderedSet and Set cannot be equal since OrderedSet makes a guarantee about iteration order and Set does not. Two OrderedSets which contain different orderings are not equal. If you agree that should be true then it should follow that an OrderedSet compared to a _____Set with any possible ordering cannot be safely called equal either. Interestingly, an OrderedSet should always be able to stand in for a Set for that definition of equality, however equality must follow the Transitive property. If A = B then B = A

**Comment by leebyron** [comment]
Another possible issue here is the type constructors like Set() or the conversion functions which are short hands for those like .toSet()

Right now I think if you provide an OrderedSet to those that it returns itself since an OrderedSet is a kind of Set. Perhaps that's bad behavior given that it makes the "downcasting" equality comparison difficult. isSet() should probably still return true though, what do you think?

**Comment by asazernik** [comment]
Having come across this need in my own project, I'm finding that what I really want is a separate set equality operator - I've implemented this as `a.isSubset(b) && b.isSubset(a)`, but it might be nice to have in the standard API. I agree that there are some conceptual problems with OrderedSets and unordered Sets with the same members being equal, but set equality comparison is a very common use case.

**Comment by leebyron** [comment]
Closing this aging issue - the bugs involved have long since been fixed.
