### ISSUE TITLE
What is the point of having both keys and keySeq

### ISSUE THREAD

**Issue by hleumas** [facebook/immutable-js#529]
This also applies to `values` and `valueSeq`, `entries` and `entrySeq`.

**Comment by leebyron** [comment]
`keys`, `values`, and `entries` return Iterators. They are stateful and can be consumed one time, every time you call `next()` on an iterator, there is no way to get to the previous item.

`keySeq`, `valueSeq` and `entrySeq` return Seq, which you can think of as an "Iterable". They are stateless and can be consumed multiple times. Seq is documented well elsewhere, but the primary value proposition is to use their laziness when composing multiple operations to improve performance.

For example:

```js
var myMap = Map({ a: 1, b: 2, c: 3 });
var squareOddValuesList = List(myMap.valueSeq().filter(val => val % 2 === 1).map(val => val * val);
// List [ 2, 9 ]
```

**Comment by hleumas** [comment]
Why should I ever use `keys` if I can use `keySeq`? Every code that works with `keys` should also work with `keySeq`, right?

Is there any reason why `keys` just don't return lazy sequence?

**Comment by leebyron** [comment]
That's not quite right, an `Iterator` (`keys`, `values`) and `Iterable` (`keySeq`, `valueSeq`) present different APIs and capabilities.

`keys`, `values`, and `entries` return `Iterator` to match the behavior of the ES6 collections. The same methods on ES6 Map, Set and Array return `Iterator`s, and I wanted to ensure the Immutable.js collections could be used in the same way.

Seq present a full collection-like API rather than the more simplistic `next()` that an `Iterator` provides, but each has it's purpose. `Iterator` is an important part of many ES6-aware APIs that Immutable.js is designed to play nice with.
