### ISSUE TITLE
how to find the keyPath of a deeply nested item?

### ISSUE THREAD

**Issue by coodoo** [facebook/immutable-js#548]
I want to update John's mobile number to be `{mobile: '444'}`? Is there a way to figure out the keyPath needed for that?

```js
var obj = [
	{name: 'john', phones: [
		{home: '111' },
		{office: '222'},
		{mobile: '333'}
	]}
	{name: 'mary', phones: [
		{home: 'a111' },
		{office: 'a222'},
		{mobile: 'a333'}
	]}
]
```

**Comment by leebyron** [comment]
The keypath for Lists are just the index, so for the specific example, `[0, "phones", 2, "mobile"]` is the keypath to John's mobile number.

If you want to update a structure like this, a fixed keypath isn't going to work for you since there's no way to index on what you're looking to index on (name, and type of phone). Instead, you'll need to search through the List to find the index to update:

```js
var indexOfJon = obj.findIndex(person => person.get('name') === 'john')
var indexOfMobile = obj.get(indexOfJohn).get('phones').findIndex(phone => phone.has('mobile'))
var updated = obj.setIn([indexOfJohn, "phones", indexOfMobile, "mobile"], "444");
```

Now: note that `findIndex` is an O(N) operation. It needs to potentially look at every item in the list to find the one that matches your criteria. If this is not a very common operation, or if this list is not ever particularly long, this is just fine. However if looking up people from this list by name is a common operation or the list of people is pretty long, you may find O(N) to have poor performance. If instead of a List you used a Map, access and updates would be O(1) instead of O(N) - much more resilient to larger lists.

Similarly with the list of phones, as your example illustrates a list of maps with a single key, you need to look through the list to figure out which to update, but then also remember to update at the correct key. This is probably pretty burdensome to deal with, and I would recommend a single map with many keys.

```js
Map({
  john: Map({name: 'john', phones: Map({
     home: '111',
     office: '222',
     mobile: '333'
  }) }),
  ...
});
```

Note however the tradeoff here, that you can't have multiple people with the same name, or multiple phones of the same type when using this sort of structure.

**Comment by coodoo** [comment]
Thanks for the quick reply!

The thing is, I thought the example I provided is a very common use case in everyday project (array of objects with nested array of objects inside, this is the most likely return value from a REST api).

In a typical CRUD app the manager might need to update John's info every now and then, hence I was trying to figure out an efficient way to make that happen, which is, given an object (John), and the collection, find the keyPath as fast as possible. 

I was wondering Is it possible for Immutablejs to provide an API like `myMap.keyPathOf( john:Object ): Array` through reflection/introspection in ES6? or have it store the path info internally?

**Comment by leebyron** [comment]
I think the first line of what I recommended:

```js
var indexOfJon = obj.findIndex(person => person.get('name') === 'john')
```

Is precisely how you would implement your suggested `myMap.keyPathOf( john:Object )`.

The performance problem as I described it is not just going to be an issue with Immutable.js but with any collection, including the built in native Array. Searching through a list to find one matching instance will always be O(N) where having a lookup into a Map will be O(1). This is simply a tradeoff you need to make for yourself when architecting your client code.

If your REST API returns data that is not going to be efficient to operate on within the client, you can always manipulate it into a different shape first, and then use that later. But again, there are tradeoffs involved and every application will have different needs. Immutable.js is not here to be prescriptive about how you structure your data, but just give you tools to make those decisions for yourself.

> through reflection/introspection in ES6? or have it store the path info internally?

I'm not sure what you're referring to by reflection/introspection in this case. I'm also not quite sure what you mean by storing path info. I think a data structure that maintains a fast lookup of path for every unique object is going to require looking very different depending on each use case. What may be fast for one use case would be slow for others, and constraints may be different - if your data includes the same "john" in two places, it could have two key paths - each semantically different.

**Comment by coodoo** [comment]
Right, makes sense to me, guess this is the necessary trade-offs to make while enjoying immutability, thanks for clearing up the thing a bit!

**Comment by coodoo** [comment]
Ended up I wrote this [tiny util](https://jsfiddle.net/coodoo/5w20s7th/1/) to help finding keyPath.

**Comment by akre54** [comment]
The problem is this does fine for short paths. But as [your second line](https://github.com/facebook/immutable-js/issues/548#issuecomment-121129523) demonstrates this gets worse the deeper nested your collection is.

Could `getIn`, `updateIn`, and friends support function as keys that would return the index instead? It'd be a little closer to how `update` works without needing to repeat the whole path for every dynamic key.

```js
obj.setIn(['a', 'b', list => list.indexOf(item), 'd'], '444')
```


```js
const matcher = item => list => list.indexOf(item)
m.getIn(['a', 'b', matcher(item)]);

const indexOfJon = obj.findIndex(person => person.get('name') === 'john')
const findMobile = phones => phones.findIndex(phone => phone.has('mobile'))
const updated = obj.setIn([indexOfJohn, "phones", findMobile, "mobile"], "444")
```

Of course, this would break functions-as-keys, but a) I would assume that's fairly rare, and b) we could allow only Lists to work with indexer functions.
