### ISSUE TITLE
Seq.take() without arguments causes `Maximum call stack size exceeded` exception.

### ISSUE THREAD

**Issue by asan** [facebook/immutable-js#552]
Test case - http://jsfiddle.net/1ccutco5/1/
I think take should throw exception with info about usage, or return 1 element(i issued this with takeLast() and, for me, this name sounds like function already should return last element without any arguments).

**Comment by tphyahoo** [comment]
Error: agree.
Last element: don't agree.

**Comment by leebyron** [comment]
Thank you for the report!

**Comment by tphyahoo** [comment]
@asan: I think the name is modeled after take from haskell, and that's why it should give an erorr. (Copies the behavior from haskell.)

If we REALLY wanted to copy the behavior, there's the question of what to do if take arg exceeds the size of the collection.  In haskell, the behavior is to just return the whole collection. 

Not sure what we do in immutable.js but maybe it should be in the docu.

**Comment by leebyron** [comment]
If the number provided to take is larger than the size, you'll get the whole collection (not a larger one).

This should either raise an error or default to an empty list (eg, undefined/null coerced to 0)

**Comment by asan** [comment]
The root if error is https://github.com/facebook/immutable-js/blob/master/src/IterableImpl.js#L412:
`Math.max(0, undefined)` returns `NaN`
If it`s ok to return empty list, it easy to fix using pattern from splice `Math.max(amount | 0, 0)`
Is it ok?
If ok I can make PR to fix take and skip(have same issue)

**Comment by leebyron** [comment]
Closing this issue now as the last release on npm solved the infinite recursion bug.

As far as the no-argument/undefined-argument behavior goes: since `take(N)` is shorthand for `slice(0, N)`, I think it's probably reasonable to expect number coercion to 0 and return an empty list as slice does. Throwing an error would be behavior differing from JavaScript, so I have concern that behavior would be surprising to many.

If you're looking for a method to return the last element, try `last()` - I think that's a clearer named method for the particular use case
