### ISSUE TITLE
React Component lose context with seq.map

### ISSUE THREAD

**Issue by charlie-rudenstal** [facebook/immutable-js#554]
I believe this issue fits best here (although it's also related to React and fluxible).

React Components lose context when used within a seq.map. Possibly due to lazy evaluation.
```
{Immutable.fromJS([1,2]).toSeq().map(_ => 
    <NavLink routeName="foo">bar</NavLink>)}
```
This fails with `Failed Context Types: Required context getStore was not specified in RouteHandlerStoreConnector.`

```
{Immutable.fromJS([1,2]).toSeq().map(_ => 
    <NavLink routeName="foo">bar</NavLink>)
 .toArray()}
```
When resolving the sequence explicitly, like above, it works. 

Is this expected behavior? My understanding is that converting Immutables to sequences is the recommended procedure before passing them to React.

**Comment by leebyron** [comment]
I highly recommend you open this issue in the React repo. `toSeq()` produces an iterable, and that iterable is iterated over by the React internals *at some point*. It's up to React to determine how to do that iteration in a way that guarantees any assumptions it makes about context.

I'm closing this here since it's unsolvable from Immutable.js's point of view, but please reference this issue when you open it on React.
