### ISSUE TITLE
Improve API for checking if data is Immutable

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#566]
Both write docs about the various predicates, also add an immutable value detection predicate at the top level of the API.

**Comment by myitcv** [comment]
:+1: - will this also cater for primitive values too? e.g. 

```
Immutable.isImmutable(Immutable.fromJS({x: 5})); // true
Immutable.isImmutable(5); // true
```

**Comment by myitcv** [comment]
Sorry, re-reading the title for this issue I'm guessing the capitalisation is significant. i.e. this issue is capturing an API function that returns true iff an object passed as an argument is an instance of any `Immutable.*` class. Let's call this `Immutable.isImmutableInstance(x)`

My previous comment is related but would deal with the wider question of whether the argument is immutable (lower case 'i')

**Comment by NickStefan** [comment]
:+1: 
For now, I've been shimming with something like this
```
var _ = require('./lodash');

function isImmutable(thing){
    return isList(thing) || isMap(thing) || isSet(thing) || isOrderedSet(thing) || isOrderedMap(thing);
}

function isList(thing){
	return _.isObject(thing) && thing['@@__IMMUTABLE_LIST__@@'];
}

function isMap(thing){
	return _.isObject(thing) && thing['@@__IMMUTABLE_MAP__@@'];
}

function isSet(thing){
	return _.isObject(thing) && thing['@@__IMMUTABLE_SET__@@'];
}

function isOrderedSet(thing){
	return _.isObject(thing) && thing['@@__IMMUTABLE_ORDERED__@@'] && thing.hasOwnProperty('__hash');
}

function isOrderedMap(thing){
	return _.isObject(thing) && thing['@@__IMMUTABLE_ORDERED__@@'] && !thing.hasOwnProperty('__hash');
}

module.exports = {
	isImmutable: isImmutable,
	isList: isList,
	isMap: isMap,
	isSet: isSet,
	isOrderedSet: isOrderedSet,
	isOrderedMap: isOrderedMap
};
```

**Comment by madebyherzblut** [comment]
@NickStefan you should better use the built-in [Immutable.List.isList](http://facebook.github.io/immutable-js/docs/#/List/isList), [Immutable.Set.isSet](http://facebook.github.io/immutable-js/docs/#/Set/isSet) and so on. Checking for `@@__IMMUTABLE_ORDERED__@@` is an internal detail which may change in future versions.

`isImmutable()` can be replaced with `Immutable.Iterable.isIterable()` since all classes inherit from `Immutable.Iterable`.

**Comment by NickStefan** [comment]
@madebyherzblut thank you! I must have missed those methods in the docs.

**Comment by medihack** [comment]
+1

**Comment by damienleroux** [comment]
+1

**Comment by wesleysmyth** [comment]
+1

**Comment by kjr247** [comment]
I've been using a check like this: 

```javascript
   My motivation here is mostly that .get of undefined shits itself violently, and initializing properly all over the place helps, but doesn't catch all edge cases. I just want the data or false without any breakage. Specific type checking causes me to do more work if I want it to change later. 

This looser version solves many more edge cases(most if not all extend type Iterable which has .get, and all data is eventually gotten) than a specific type check does(which usually only saves you when you try to update on the wrong type).

Here we go.

/* getValid: Checks for valid ImmutableJS type Iterable
    
    returns valid Iterable, valid Iterable child data, or undefined
    
    Iterable.isIterable(maybeIterable) && maybeIterable.get(['data', key]), becomes
    getValid(maybeIterable, ['data', key])
    
    But wait! There's more! As a result:
    getValid(maybeIterable) returns the maybeIterable or undefined would really like a false instead    */

export const validate = (maybeIterable, path) =>
  Iterable.isIterable(maybeIterable) && path
    ? ((typeof path === 'object' && maybeIterable.getIn(path)) || maybeIterable.get(path))
    : Iterable.isIterable(maybeIterable) && maybeIterable;
```

Just give me what I am asking for or tell me no. Don't explode. I believe underscore does something similar also.

**Comment by fckt** [comment]
what if I need to check it in 3rd party lib? I need some "signature" to be sure if the value I've got follows some protocol of immutableJS, like `equals`.
