### ISSUE TITLE
Deep Record.setIn()

### ISSUE THREAD

**Issue by jareware** [facebook/immutable-js#573]
The docs state that Records are implemented with Maps, and [Map.setIn](https://facebook.github.io/immutable-js/docs/#/Map/setIn) says:

> Returns a new Map having set value at this keyPath. If any keys in keyPath do not exist, a new immutable Map will be created at that key.

But:

```js
> R = Immutable.Record(({ foo: null }));
> r = new R();
> r.setIn([ 'foo' ], 123);
Object {_map: Object, __ownerID: undefined}
> r.setIn([ 'foo', 'bar' ], 123);
Uncaught Error: invalid keyPath
```

Am I missing something, or is this a bug?

**Comment by derfloscher** [comment]
As far as I understand it, Records are only meant to be used if you want to enforce a certain schema for your data while providing defaults when removing a key.

In your example the second setIn operation rightfully throws an error  because immutable recognizes that foo is set to a value (even though it is set to its default - null) and tries to forward the set call resulting in your error.

Either just use Immutable.Map() 
```javascript
> Immutable.Map().setIn(['foo','bar'], 'baz').toJS()
{"foo":{"bar":"baz"}} 
```
or enforce a suitable schema with Record
```javascript
> r = Immutable.Record({foo: Immutable.Record({bar: 'baz'})()})()
> r.toJS()
{"foo":{"bar":"baz"}}
> r.setIn(['foo','baz'], 'bar') // fails becaus the inner record only allows the "bar' key
Uncaught Error: Cannot set unknown key "baz" on Record
> r2 = r.setIn(['foo','bar'], 'qux')
> r2.toJS()
{"foo":{"bar":"qux"}}
> r2.remove('foo').toJS()
{"foo":{"bar":"baz"}}
> r2.removeIn(['foo','bar']).toJS()
{"foo":{"bar":"baz"}}
```

**Comment by jareware** [comment]
This is an interesting interpretation, but I'm not sure if "Records are only meant to be used if you want to enforce a certain schema" is entirely accurate... since it's actually not possible to enforce any kind of content policy on Immutable objects (at least before e.g. #473).

As to "immutable recognizes that foo is set to a value [...] and tries to forward the set call", what actually makes this different from a Map?

**Comment by derfloscher** [comment]
You are right, that Records do not enforce any types or immutability on the keys, however they do limit ability to remove keys set in the Record and the ability to set keys which are not defined in the Record.

You are correct, that your initial example would also throw for a Map
```javascript
> Immutable.Map({foo:null}).setIn(['foo', 'bar'], 'baz')
Uncaught Error: invalid keyPath
```
This is due to the same reason - the key foo is set to a type (in this case null) which does not support the setIn / set function.

With a Map it would however be possible to 

```javascript
> Immutable.Map({foo:null}).remove('foo').setIn(['foo','bar'], 'baz').toJS()
{"foo":{"bar":"baz"}}
> Immutable.Record({foo: null})().remove('foo').setIn(['foo','bar'], 'baz') 
Uncaught Error: invalid keyPath
> Immutable.Record({foo: null})().remove('foo').toJS() // on removal the default is being set
{"foo":null}
```

**Comment by jareware** [comment]
OK, that makes sense. So it's actually more about how Maps work with `setIn()`, than Records being somehow exceptional.

Thanks for a thorough explanation!

**Comment by kyldvs** [comment]
This is very unintuitive based on the behavior of `setIn` with other objects, and incredibly hard to debug due to #635 

The way this series of calls work also makes this unintuitive:

```
var r = Immutable.Record({foo: undefined});
var r1 = new r()
var r2 = r1.set('foo', undefined);
r1 === r2 // false

var m1 = Immutable.Map();
var m2 = m1.set('foo', undefined);
m1 === m2 // false
```

The above makes me incorrectly assume that the default of a record is somehow similar to the "not set" state of map. In any case it would be nice to support a form of record that allows safe usage of `setIn` and `deleteIn`.
