### ISSUE TITLE
Have asMutable/withMutations act recursively?

### ISSUE THREAD

**Issue by rmadsen** [facebook/immutable-js#612]
Am I missing some sort of API that lets me make a complex object deeply mutable?

For example, given a Map with another Map nested inside, I'd love to grab a reference to that nested Map, alter it and not have to re-assign it to the containing Map. Here is some code that illustrates this behavior:

``` js
  let m = Immutable.fromJS({x: 1, y: Immutable.fromJS({a:5, b:6})});
  console.log("Before:", m.toJS());

  let m2 = m.withMutations((res) => {
    res.set("x", 2);
    res.setIn(["y", "a"], 8);
    let y = res.get("y");
    y.set("b", 9);
  });
  console.log("Final:", m2.toJS()); // {x: 2, y: {a: 8, b: 6}} - "b" doesn't get updated
```

Even if I do `y.asMutable().set("b", 9)` the final `m2` does not show an updated b. Is there any way to turn an object "deeply" mutable so I can pass substructures to helper methods?

**Comment by hackwaly** [comment]
As the other side, I want a asImmutable(deep: true) act recursively.
It's not easily done outside the library and is a common demand.

**Comment by leebyron** [comment]
`withMutations` is designed for performance-tuning code, so it's critical that it's fast. It would be inappropriate to have it attempt to perform deep operations which could be very costly.

**Comment by tp** [comment]
(Did not want to create a new ticket, but I was basically looking for the same thing.)

@leebyron So if `withMutations`s scope should not be changed, do you think that a feature like this should be discussed as new functionality? Does this usage even make sense for Immutable, or are the author and myself using the library in some unintended way and hence run into this?

**Comment by leebyron** [comment]
Yes I would call this mistaken usage. For example in the original example here is the issue:

 ```js
let m2 = m.withMutations((res) => {
    let y = res.get("y");
    y.set("b", 9);
  });
```

While the `m` collection is in a mutable mode, the collection at the `y` key being referenced is of course still immutable. If `m.withMutations` were to recursively walk the data structure to convert all referenced collections to mutable, it would be extremely costly (O(N) instead of O(1)), defeating the purpose of having `withMutations` as a performance tuning tool.

A correct code would be:

 ```js
let m2 = m.withMutations((res) => {
    let y = res.get("y");
    res.set("y", y.set("b", 9));
  });
```

Or more tersely:

 ```js
let m2 = m.withMutations((res) => {
  res.setIn(["y", "b], 9);
});
```

If there are multiple updates happening to the collection at `y` which suggest needing `withMutations` performance tuning, then that can be done as well:

 ```js
let m2 = m.withMutations((res) => {
  res.update("y", y => y.withMutations(yMutable => {
    y.set("b", 9);
  })
});
```

Remember that `withMutations` still always creates a copy from the original, so using `withMutations` to apply a single change is overkill and will be slower than just doing the simpler update directly. In general I suggest using `withMutations` only when metrics draw you to a costly piece of code, since normal immutable updates are already quite fast (O(logN)). 

I understand that the original example was intentionally contrived, but any code that updates a single or few values like this is best done directly:

 ```js
let m2 = m.setIn(["y", "b"], 9);
```
