### ISSUE TITLE
Immutable List is really slow on push

### ISSUE THREAD

**Issue by nilveryawesome** [facebook/immutable-js#628]
https://jsperf.com/native-list-vs-immutable-list

**Comment by billyjanitsch** [comment]
By design, Immutable List is creating a new array for each push, whereas the native push is mutating the existing list. If you want to do multiple mutations in sequence like this, you should batch them. See the "Batching Mutations" section on the [homepage](https://facebook.github.io/immutable-js/) -- it has an example of doing exactly this.

**Comment by nilveryawesome** [comment]
Thanks, Actually I figured that immutable is faster than / as quick as  Vanilla JS if u are creating a new array or object. I am happy about immutable now :) http://jsperf.com/immutable-set-vs-native-set-with-lodash-clone/4
