### ISSUE TITLE
Feature request: `addIn`, add element to nested `Set`.

### ISSUE THREAD

**Issue by rhys-vdw** [facebook/immutable-js#640]
A function `addIn` that is analogous to `setIn`, but for nested `Set`s.

``` js
import { Set } from 'immutable';
const map = Immutable.fromJS({ indices: { ids: Set() } });

map.addIn(['indices', 'ids'], 5);
// Shorthand for:
map.updateIn(['indices', 'ids'], ids => ids.add(5));
```

**Comment by rhys-vdw** [comment]
Also `removeIn` would be helpful.

Additionally (perhaps this deserves its own issue) this seems inconsistent:

```js
var set = Immutable.Set([0, 1, 2]);
var map = Immutable.fromJS({ s: set });

set.delete(1).toString();
// "Set { 0, 2 }"

map.deleteIn(['s'], 1).toString();
// "Map {}"
```

**Comment by tyrsius** [comment]
It seems *strange* to me that this is missing. Working with nested sets is uniquely difficult due to this ommission

**Comment by R3D4C73D** [comment]
This seems like an easy and obvious improvement.  Why hasn't there been any movement in almost a year?  Would the maintainers like a pull request?

**Comment by tyrsius** [comment]
I guess immutable applies to the API as well...

**Comment by leebyron** [comment]
There's a fairly large API, and at some point we need to draw a line between how many methods have `*In` variations. Generally we favor the methods that apply to many different types for most convenience.

Otherwise, any time a deep method, say `data.xxxIn(arg)` is needed, a worthy substitute is `data.updateIn(_ => _.xxx(arg))`
