### ISSUE TITLE
I'm curious if/how people are using Cursors with React.

### ISSUE THREAD

**Issue by ccorcos** [facebook/immutable-js#659]
https://github.com/facebook/immutable-js/tree/master/contrib/cursor

Are you using a pattern like redux?

**Comment by ccorcos** [comment]
Seems to me like you can just pass down a cursor to a child component and it will be able to manipulate that cursor as it pleases. All the state pipes all the way down through props. Will all the references change, or will React update optimally?

It seems to be like this could entirely replace redux.

**Comment by tomwidmer** [comment]
Yes, it is a simpler alternative to flux, if you want to make your components responsible for data updates. If your app is simple, it may suit you. If your app is complex, I suspect the store+action abstraction might help you.

If you have PureComponents, then the updates should be fairly optimal however you do the update (cursors, or state.setIn, or whatever), since they all boil down the the same Immutable.JS calls ultimately.

**Comment by ccorcos** [comment]
Hmm. Is there an example somewhere I can look at? I havent entirely understood how the whole cursor lifecycle works.

**Comment by tomwidmer** [comment]
A few libraries make working with Immutable JS cursors and react a bit easier (I've not tried them):
https://github.com/omniscientjs/immstruct
https://github.com/omniscientjs/omniscient (includes some cursor examples, uses immstruct optionally)
https://github.com/lukasbuenger/immutable-cursors (includes a simple react cursor example - the library itself is minimal)
https://github.com/arch-js/arch

For optimal rendering, you will need to provide a shouldComponentUpdate implementation that is cursor-aware. Just loop over the props and state, detect if the prop is a cursor (using instanceof), and if so check if `next.deref() !== old.deref()` because the cursors themselves will always be !== if they are recreated by a re-render, even if the held immutable data is === (non-cursor props should just be === compared). But that's just optimization, and not required to make it work...

**Comment by ccorcos** [comment]
Thanks for the links! It looks like they are building their own cursors though. not using the immutable.js cursors...

**Comment by ccorcos** [comment]
Hmm. I'm figuring it out a little bit -- is it possible to nest cursors though? for example:

```js
var data = Immutable.fromJS({ a: { b: { c: 1 } } });
var cursor = Cursor.from(data, 'a', newData => {
  data = newData;
});

cursor.get('b')

**Comment by tomwidmer** [comment]
The links I think all use ImmutableJS cursors under the hood. Your nested cursor example should work, yes.

**Comment by leebyron** [comment]
Closing this aging issue
