### ISSUE TITLE
React + Immutable.JS: Best practice for sending Immutable.Map as props to children components?

### ISSUE THREAD

**Issue by liorbrauer** [facebook/immutable-js#667]
Hi,

I'm doing the following inside a render() function on my Component:
```
posts.map((post) => 
  <PostComponent post={post} key={post.get('id')} />
)
```

Where `posts` is an `Immutable.Map`, and each item in it `post` is also a Map.

This seems to work but I'm getting the following warning:
```Warning: Using Maps as children is not yet fully supported. It is an experimental feature that might be removed. Convert it to a sequence / iterable of keyed ReactElements instead.```

What alternative approach is suggested? I don't want to lose `Immutable.Map`'s functionality like `.hasIn` and `.getIn`.

Thanks!

**Comment by eyston** [comment]
`Immutable.Map#map` returns an `Immutable.Map` so you are giving react a Map of children.  You should be able to do:

```javascript
posts.values().map(post =>
  <PostComponent post={post} key={post.get('id')} />
)
```

I don't know if you'd need to append an `toArray` or not.

**Comment by liorbrauer** [comment]
@eyston Thanks for the help! :+1: 

Yeah, it's `valueSeq` and then `toArray` is not even needed for the iteration:

```coffeescript
posts.valueSeq().map(post =>
  <PostComponent post={post} key={post.get('id')} />
)
```

I guess I'm still a bit confused at to what an `Immutable.Seq`is. Is there a good primer/tutorial on all the different Immutable data types (other than the regular documentation)?

**Comment by eyston** [comment]
I don't know of one.  I came from clojure so I just guess a lot when it comes to Immutable.js :).

I'm actually not sure why so many functions have a `x` and `xSeq` version.  I generally use `x` and then get told `map` is not a function and see if an `xSeq` version exists.

Guessing from clojure ... `Immutable.Seq` is an immutable lazy list.  It is the base most of the other data structures implement.  So when you call something like `valueSeq` the contract is it is going to return a `Seq` but that might take the form of an eager `List` of all values, or it might be a lazy `Seq` where it only does the work to pull a single value out at a time.  The thing is, you don't care.  As long as it implements the `Seq` interface you can `map` away.

**Comment by liorbrauer** [comment]
@eyston Thanks for the explanation :+1: 

Hopefully we'll get a more thorough documentation and some more examples from Immutable.

**Comment by agilgur5** [comment]
+1 for the solutions described here!

**Comment by ccerrato147** [comment]
+1

**Comment by anhhh11** [comment]
+1 solutions 
posts.valueSeq().map(post =>
  <PostComponent post={post} key={post.get('id')} />
)

**Comment by cettoana** [comment]
+1 thanks

**Comment by rikkuporta** [comment]
If you don't want to lose the key-value relationship you can also use `entrySeq()`, which is like a combination of keySeq and valueSeq:
```
posts.entrySeq().map(o => 
     <Post value={o[1]} key={o[0]} />
)
```

**Comment by dulguun0225** [comment]
They also have `mapEntries()` which is `entrySeq` and `map` combined `map . entrySeq`.

```
posts.mapEntries(o => 
     <Post value={o[1]} key={o[0]} />
)
```

**Comment by vinnymac** [comment]
`entrySeq().map` and `valueSeq().map` did not throw a warning and produced a `IndexedIterable`.

When using `mapEntries()` I get the warning the OP originally had in the first comment. This produces a `OrderedMap`, which is the data structure I am mapping with. If you attempted to use `mapEntries()` hopefully this provided a hint as to why you may be receiving that warning.

**Comment by betoharres** [comment]
All the solutions throws flattenChildren error when you modify its state out of the component, and then try to mount it back.

**Comment by Ciul** [comment]
You could instead of passing Immutable Collections such as Maps and Lists to your React components, pass normal js objects and arrays, respectively. Thay way, it's easier to read and understand, and you remove dependency/boilerplate of Immutable from your React components.

Remember that Immutable Map each _keys_ and _values_ method return an iterator, which can be converted to an array using the spread operator inside brackets.

This way, using a normalized state for a Todos demo app e.g:
```javascript
const stateShape = Record({
    todos: Map({
        1: {
            name: 'Eat a lot'
        },
        2: {
            name: 'Take span'
        },
    })
})
```
I'd suggest a mapStateToProps function like this:
```javascript
[...] // some other code
const getProjectsArray = state => {
    const todos = state.get('todos')
    const todosArray = [...todos.values()]
   
   return todosArray
}

const mapStateToProps = (state) => {
    projects: getProjectsArray(state)
}
[...] // Some other code
```

**Notes:**
- This makes easier to use tools like [Normalizr](https://github.com/paularmstrong/normalizr) and [Reselect](https://github.com/reactjs/reselect).
- Remember to convert back to Immutable Collections your data before injecting it in your state. Which could be done in reducers but a better approach would be keep reducers out of complex logic and move all logic to something like a middleware.

**Comment by matiasgarcia** [comment]
Wouldn't that, however, kill any performance optimization done on react components based on ImmutableJS?

**Comment by andrewcapodieci** [comment]
@Ciul that's going to cause unnecessary rerenders every time unless you implement shouldComponentUpdate with a deep comparison, which can be costly depending on your object.

**Comment by wSLecHayfIeNdock** [comment]
```
posts.map((post) => <PostComponent post={post} key={post.get('id')} />).toArray();
```

**Comment by acusti** [comment]
@wSLecHayfIeNdock That behavior of `toArray()` that your example relies on, where it just takes the values of an immutable `Map` and drops the keys, has been removed in Immutable v4: https://github.com/facebook/immutable-js/pull/1340

The immutable v4 version of your snippet:

```js
posts.map((post) => <PostComponent post={post} key={post.get('id')} />).valueSeq().toArray();
```

**Comment by Ciul** [comment]
@andrewcapodieci That's why I suggest using Reselect. This will make a kind of cache and will return same array if not changed.

**Comment by bogdaniy** [comment]
@Ciul are your transforming your immutable objects toJS() in selectors or using .get() syntax in jsx?

**Comment by CMCDragonkai** [comment]
I have a strange request here. I'm also using Typescript, and converting to using `entrySeq` for React lists seemed like the right idea. Especially as https://reactjs.org/docs/lists-and-keys.html recommends getting the `key` as well.

However what is the type that should be set for the component that receives a Seq? It shouldn't be an Immutable Seq. It should be some sort of "Functor" type that supports `map`. Because the component can also take just an array as well.

Furthermore, this is basically React rendering of a Map. Does converting to an entrySeq mean that every time, the Map changes, we have to reproduce a list so that React can render it. It seems rather inefficient for React, and it seems that it would be better if there was some key-value structure that was also always iterable without needing to be converted into a different in-memory representation.

I want to use some generic functor type instead of immutable Seq so to avoid the dependency of react components on immutablejs.

**Comment by usman-subhani** [comment]
Try reduce()
```
posts.reduce((jsxArray, post) => {
  jsxArray.push(
    <PostComponent post={post} key={post.get('id')} />,
  );
  return jsxArray;
}, []);
```
