### ISSUE TITLE
is returning false on equal lists

### ISSUE THREAD

**Issue by jhicken** [facebook/immutable-js#675]
Immutable.is( new Immutable.List([]), new Immutable.List([])); --> true
Immutable.is( new Immutable.List([{}]), new Immutable.List([{}])); --> false

I'm guessing this is due to the object being 2 different instances of a native object. Is this the desired behavior?

**Comment by samwgoldman** [comment]
Yes, this is the expected behavior.

**Comment by jhicken** [comment]
What is the preferred way to check this?

**Comment by leebyron** [comment]
```js
Immutable.is( new Immutable.List([{}]), new Immutable.List([{}])) === false
```

Is correct for the same reason

```js
Immutable.is( {}, {} ) === false
```

For the same reason

```js
({} === {}) === false
```

Two object references are always considered not equal since they are designed to be mutable and allowed value equality checking between them can be dangerous and lead to bugs.

Immutable.js only treats the immutable collections as value equal, which is why comparing two immutable empty lists together is considered equal.

A variation of your original example but using `Map` instead of a JS object will result in value equality:

```js
Immutable.is( 
  Immutable.List([ Immutable.Map() ]),
  Immutable.List([ Immutable.Map() ])
) === true
```
