### ISSUE TITLE
List.map() equality confusion

### ISSUE THREAD

**Issue by blackChef** [facebook/immutable-js#678]
var arr1 = immutable.fromJS([
      { age: 25, name: 'john' },
      { age: 32, name: 'sam' },
    ]);
    
    // simply return the same item
    var arr2 = arr1.map( item => item);

    console.log(arr2 === arr1) // false

Is this behavior designed on purpose? In my opinion, arr2 & arr1 should be equal here.

**Comment by rawls238** [comment]
I believe it is designed on purpose since === will check if arr1 and arr2 are the same object (using reference equality) but map returns a new immutable object so arr1 !== arr2. If you used immutable.is then they would be equal since is uses value equality

**Comment by leebyron** [comment]
Unfortunately the "return the same reference" optimization does exist for `map` yet, so while the result will have the same value equality, it won't have reference equality. 

Similar to how:

```js
var array = [1, 2, 3];
array !== array.map(x => x);
```

I've opened an issue for this at https://github.com/facebook/immutable-js/issues/679 since this would be a nice optimization to have.
