### ISSUE TITLE
Better support for ES6 Iterators

### ISSUE THREAD

**Issue by leebyron** [facebook/immutable-js#68]
As spec'd (kinda) in:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/The_Iterator_protocol
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/iterable
http://wiki.ecmascript.org/doku.php?id=harmony:iterators
http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts

**Comment by magnushiie** [comment]
Should the typings of `Iterable<K, V>` be updated to include the method?
```typescript
[Symbol.iterator](): Iterator<T>;
```

I'm not sure this is the right way for 2 reasons:
- The Symbol symbol is declared only for TypeScript ES6 target - for backwards compatibility, should SymbolConstructor and Symbol be defined in immutable.d.ts also?
- From source it seems KeyedIterable returns entries() instead of values(), so the type of it is different. Maybe it's enough to override the iterable method in Iterable.Keyed to return the appropriate type instead.

**Comment by samwgoldman** [comment]
> From source it seems KeyedIterable returns entries() instead of values()

You hit the nail on the head here. This is the real issue with making the base class iterable. Consider the following function:

```
function f(iter: Iterable<A,B>): Array<?> {
  out = [];
  for (let x of iter) {
    out.push(x);
  }
  return out;
}
```

What type belongs in `?`? If I pass a `KeyedIterable`, it would be `[K,V]`, if I pass anything else, it would be `V`.

**Comment by magnushiie** [comment]
It seems then that `Immutable.Iterable` itself should not be `Iterable` in the ES6 sense (as defined in lib.core.es6.d.ts), because its type is ill-defined. Instead, `Iterable.Indexed` and `Iterable.Keyed` should be ES6-iterable. It's bit of a pain because the Iterable methods like `map` aren't typed as returning this, but it would still be better than nothing.
