### ISSUE TITLE
Collection.without()

### ISSUE THREAD

**Issue by jareware** [facebook/immutable-js#688]
Sorry if this is already somehow supported or if there's an issue open for it; I couldn't find either.

This is a rather common use case:

``` js
someCollection.filterNot(item => Immutable.is(item, unwantedItem));
```

It would be much easier to write (and later understand) as:

``` js
someCollection.without(unwantedItem);
```

FWIW, lodash has [this same method](https://lodash.com/docs#without).

**Comment by jareware** [comment]
An alternative (and/but with broader implications) would be for `filter()` and friends to delegate to `Immutable.is()` when they're called with a value that's not a function.

**Comment by arjunblj** [comment]
Is there a plan to implement a `without` fn? I'm happy to take a stab at it.

**Comment by jareware** [comment]
Don't know, didn't get any feedback from the maintainers and then promptly forgot about this myself. :)

**Comment by jareware** [comment]
@arjunblj did you ever?

**Comment by leebyron** [comment]
One recurring point of confusion with this library is that people confuse what operations are fast vs slow. I'm noticing that this is related to how verbose an API is - people seem to expect short terse API to be fast. That gives me pause for `without` - since it's a one-liner to implement yourself so there's low value in adding it to the library, and people may become confused between when to use `without` and when to use `delete`.
