### ISSUE TITLE
Appropriate use of immutable.js with React

### ISSUE THREAD

**Issue by shilpan** [facebook/immutable-js#70]
I have an immutable object which I am passing through as state `this.setState(getStateFromStore())`.
However it looses all its prototype functions related to `immutable.js` on trying to access the state.

It works fine when the state is set as:  `this.setState({data: getStateFromStore()})` which is kindof clunky and hackish.

This makes me wonder, what are the best practices on using `Immutable.js` data structures inside React views?

**Comment by andersekdahl** [comment]
Sorry to wake up an old issue, but it seems appropriate for my question. I'm using a Immutable.Map as my state object and calling `replaceState`. But since `replaceState` doesn't set the state synchronously (for good reasons), you can find yourself in a difficult spot if you do:

```
this.replaceState(this.state.set('x', 1));
this.replaceState(this.state.set('y', 2));
```

Because the first will get discarded, and the second call to `replaceState` doesn't contain the new value for `x` (since `this.state` hasn't been updated). This simple example can be solved by replacing the two calls with just one, but in a more complex example you might have one call to `replaceState` in a method in component A, and that method sends out an event. The event triggers something which comes back to an event handler in component A, which reads from a data store and calls `replaceState` again. If React doesn't update `this.state` between those calls, the first call to `replaceState` is ignored.

How would you solve this? Make sure that all events are synced with Reacts batching? Or always send out events in a callback that you pass to `replaceState`?

**Comment by samwgoldman** [comment]
Looks like this alternate method of setting state from @leebyron himself would help you out: https://github.com/facebook/react/pull/2991

**Comment by andersekdahl** [comment]
That looks great, definitely looks like the right way to do it.

**Comment by steida** [comment]
Check my ES6 React Flux webpack gulp om-like isomorphic immutable k̶i̶t̶c̶h̶e̶n̶s̶i̶n̶k̶ t̶w̶e̶e̶t̶y̶b̶i̶r̶d̶s̶ TodoMVC example. https://github.com/steida/este-todomvc

**Comment by leebyron** [comment]
@samwgoldman has the right idea here. React is trying to move away from `replaceState` in the future, and in v0.13 `setState` can accept a delta function:

```js
getInitialState() {
  return { data: Immutable.Map() };
}

...

this.setState(state => ({ data: state.data.set('x', 1) }));
this.setState(state => ({ data: state.data.set('y', 2) }));
```

The setState delta functions will be called in the order supplied.

**Comment by andersekdahl** [comment]
Any plans on letting you override the merge strategy for setState so you can use an immutable record as state instead of in a property on a regular object?

**Comment by leebyron** [comment]
@andersekdahl at this time, no. You should bring that up on the React github issues if you want to discuss further.
