### ISSUE TITLE
Next version should leverage ramda approach

### ISSUE THREAD

**Issue by steida** [facebook/immutable-js#712]
I mean composable curried by default functions.

**Comment by leebyron** [comment]
The next version of Immutable.js will strive to have an even smaller surface area, as it's primary benefit is providing highly performant persistently immutable data structures, not a broad data API. Ramda presents an excellent API for functional programming within JS, but that is not the goal of this library.

Immutable.js's data structures are intended to be used as flexibly as possible with many libraries. Unfortunately JavaScript's Array exotic can make this pretty difficult, but ideally libraries like Ramda and Lodash could help determine a standard access pattern so that Ramda and Immutable can work very well together rather than be seen as a "vs".
