### ISSUE TITLE
docs for list.insert?

### ISSUE THREAD

**Issue by jeffbski** [facebook/immutable-js#718]
I am not real clear how the documentation is created for Immutable.js, but unless I am looking at a stale copy of the docs, I don't see the new List.insert method documented.

http://facebook.github.io/immutable-js/docs/#/List

Thanks!

The relevant commits:

It was added to typescript here.
https://github.com/facebook/immutable-js/commit/189678f700a1197befa9f74b42169fe4224dc9a1

Here was the original commit for the code
https://github.com/facebook/immutable-js/commit/193ebd572929837156b660eb1d0b6a2304ed3fea

**Comment by rawls238** [comment]
possible that the docs need to be redeployed or something

**Comment by vlinder** [comment]
The docs seem waay off to me. Lots of stuff missing.

for example Map.filter and List.filter?

**Comment by tshinnic** [comment]
See more recent issue #798 for more problems with docs (such as vlinder mentions above (and found under `Iterable` (!) at the moment)).  However, in the meantime your original problem with List.insert() seems to be fixed by now, and can be found [here](https://facebook.github.io/immutable-js/docs/#/List/insert).

**Comment by leebyron** [comment]
Fixed
