### ISSUE TITLE
Using a dot notation to chain getters

### ISSUE THREAD

**Issue by dok** [facebook/immutable-js#757]
I was wondering if it would be possible to implement an upgrade to the .get api so that users will be able to do something like props.get('one.two.three') with Immutable.js.

It would potentially be implemented similar to the lines of [lodash's](https://lodash.com/docs#get) api.

What do you guys think? I apologize if this is already a duplicate.

**Comment by rickyvetter** [comment]
You can use the getIn syntax to pass a keyPath as an array of key values. Your example would look like `props.getIn(['one','two','three'])`. https://facebook.github.io/immutable-js/docs/#/Iterable/getIn

**Comment by kimmobrunfeldt** [comment]
I think the support for also dot notation would be a good upgrade to the API. Other libraries are using it, it is nicer to read and feels more intuitive. 

Would you be willing to support both ways?

1. `props.getIn(['one','two','three'])`
2. `props.getIn('one.two.three')`

It would be a backwards compatible API addition.

**Comment by Delapouite** [comment]
Yes. This would be better than doing manually each time : 
`props.getIn('one.two.three'.split('.'))`

**Comment by rickyvetter** [comment]
I really don't think it makes sense to support the dot notation API. getIn is more flexible with iterables, as they can be dynamically generated with powerful built in JS APIs. In addition, immutable can use non-strings as keys in most objects. Using dot notation isn't even possible in many of those cases.

**Comment by kimmobrunfeldt** [comment]
I don't understand what you mean by this:

> getIn is more flexible with iterables, as they can be dynamically generated with powerful built in JS APIs.

Do you have an example?

The dot notation is pretty common in many libraries including lodash [_.get method](https://github.com/lodash/lodash/blob/252ea445cab947c6e762b1d99a29ad08806e3b7d/doc/README.md#_getobject-path-defaultvalue), which makes it intuitive to use. How common is it that someone uses non-strings as keys? In my opinion the API could bend a little in this case instead of strictly consistent with marginal use cases(I'm roughly assuming that it is marginal to have non-string keys, don't have any backing data). 

In any case, supporting this and making a note that the dot notation only works with string keys would be a big improvement for using this the getIn, setIn, etc. methods.

**Comment by rickyvetter** [comment]
```js
const getFieldByID = (id, field) => _privateThing.getIn([id, field]);
const getNestedEncryptedFields = (...args) => _privateThing.getIn(args.map((key) => decrypt(key));
```
lodash definitely [implements "casting" the dot notation to an array](https://github.com/lodash/lodash/blob/4.7.0/lodash.js#L5738). It just doesn't seem like it provides any real advantage over an iterable. It's more work to create them if you want them to by dynamic and it's always more work for the library to use them.

**Comment by leebyron** [comment]
This is unfortunately not something we're going to do, as the performance of `get` and `getIn` are critical, and doing type sniffing on the input would be a serious performance loss.

I recommend writing a function like:

```js
function p(path) {
  return path.split('.');
}

so you can write: `getIn(p('a.b.c'))`

**Comment by kimmobrunfeldt** [comment]
Thanks for the responses. +1 for keeping the performance good. A custom function for the job solution sounds the way to go :+1:

**Comment by Glidias** [comment]
What about using a Proxy query wrapper over a given object, so you could use ES6 Proxy dot access to perform context-origin-specific setter operations + current target getter operations). That way, you can code using regular dot syntax without relying on get/getIn() or set/setIn() function calls.

function imProxy(immutable) {
   // ...
  //  actual transformed structure can become something like: {origin:rootImmutable, chain:["someProperty", "someNestedProperty"], current:currentSelectedImmutable} upon accessing nested object properties within this Proxy down the dot access chain.
    // by default
    return new Proxy({current:immutable}, {  someStandardJSManagementHooksForQueryingImmutables } );
}

// Assuming you're performing a mutation operation on a root state atom..

```
someImmutable.withMutations(  function(someImmutable) {
   var root= imProxy(someImmutable);  // define an origin for the query
   root.c= 4;     // actually calls current.set("c", 4) from proxy, where current is someImmutable.
   var nestedQuery = root.someProperty;
   nestedQuery .v= 2;  // after retrieving another Proxy with root.someProperty, forming an origin+query chain, actually calls   origin.setIn(["someProperty, "v"], 2); , where origin is still someImmutable
   nestedQuery.someNestedProperty.b = 3; // after retrieving another Proxy with nestedQuery.someNestedPropert,. extending the query chain, actually calls      origin.setIn(["someProperty", "someNestedProperty", "v"], 2);
   root.someProperty.someNestedProperty = 2;  // actually does the same thing above, but re-queries everything from root rather than using the previous nested dot query cache var.
});
```

**Comment by smeijer** [comment]
I'm not sure if that is a good idea, as  `Proxy` cannot be polyfilled.  There is a project that tried to achieve this, but it's terrible in performance and recommended to not be used in production code.

**Comment by Glidias** [comment]
If proxying over an unrestricted Map, it would be a problem without es6 Proxy, since u can't polyfill a es6 proxy exactly. If however the  properties of the immutable structs are known beforehand ,, ( somewhat like https://github.com/GoogleChrome/proxy-polyfill proxy polyfill   implementation with such  a requirement   ),  it does imply that actually a full es6 Proxy isn't  entirely necessary either for such a case,  but, simply a wrapper/manager class  with automatic prop set-up es5 getters/setters  over the known existing immutable struct would do the same thing as well.
