### ISSUE TITLE
Set#has equality comparison

### ISSUE THREAD

**Issue by jzahka-fiksu** [facebook/immutable-js#777]
I see that `Immutable.Set` is not using SameValueZero comparison, which is in the es6 specification http://www.ecma-international.org/ecma-262/6.0/#sec-set.prototype.has

This isn't really an issue or problem, just wondering the reasoning behind this design.

Here's an example.
``` javascript
a = {test: 1}
b = {test: 1}
set = Immutable.Set([A])
set.has(B) //=> true
```

**Comment by leebyron** [comment]
I'm not seeing the same results:

```
> a = {test: 1}
{ test: 1 }
> b = {test: 1}
{ test: 1 }
> set = Immutable.Set([a])
Set { [object Object] }
> set.has(b)
false
>
```

Immutable uses something very similar to the `SameValueZero` comparison, however if both sides of the comparison are Immutable collections like `Map` or `List` then they use *Value Equality* rather than *Object Equality* which is a concept that ES6 does not contain.
