### ISSUE TITLE
Merging `fromJS` object with deeply nested array does not behave as expected

### ISSUE THREAD

**Issue by dsteinbach** [facebook/immutable-js#781]
Merging an object created with fromJS that has a deeply nested array behaves unexpectedly. Merging an object created with Map works expectedly.

```
// Good
var x = Immutable.Map({a: {b: {c: [10, 40], c2: true}}});
var y = Immutable.Map({a: {b: {c: [10], c2: false}}});

console.log(JSON.stringify(x.mergeDeep(y)));
// {"a":{"b":{"c":[10],"c2":false}}}

// Unexpected results
var a = Immutable.fromJS({a: {b: {c: [10, 40], c2: true }}});
var b = Immutable.fromJS({a: {b: {c: [10], c2: false }}});

console.log(JSON.stringify(a.mergeDeep(b)));
// {"a":{"b":{"c":[10,40],"c2":false}}}

```

**Comment by ntgn81** [comment]
@dsteinbach , I believe that's the expected behavior.

`Immutable.Map`, unlike `Immutable.fromJS`, does not convert deeply nested values into `Map`s and `List`s.

```js
var x = Immutable.Map({a: {b: {c: [10, 40], c2: true}}});
Immutable.Iterable.isIterable(x.get('a')); // false

var a = Immutable.fromJS({a: {b: {c: [10, 40], c2: true }}});
Immutable.Iterable.isIterable(a.get('a')); // true
```

And `mergeDeep` would try to merge nested items only when they are instances of `Iterable`.

In your sample code, the `unexpected results` case is actually expected.
As merging arrays `[1, 2, 3]` with `[3, 4]` would result in  `[3, 4, 4]`. This is similar to merging objects `{'0': 1, '1': 2, '2': 3}` with `{'0': 3, '1': 4}`, resulting in `{'0': 3, '1': 4, '2': 3}`

Though it might be correct as per spec (I'm not sure which, but the guys created this are definitely smarter than me :D :), it really messes up arrays in my use case of `mergeDeep`. I had to work around for mergeDeep to completely replace arrays when it finds one instead of trying to merge.

https://github.com/facebook/immutable-js/issues/762

**Comment by leebyron** [comment]
Thanks for answering!

In the future, ask this kind of question on stack overflow where answers can be easily searched. https://stackoverflow.com/questions/tagged/immutable.js?sort=votes
