### ISSUE TITLE
toJS not deeply converting the results of entrySeq()

### ISSUE THREAD

**Issue by rossipedia** [facebook/immutable-js#803]
Not sure if this affects anything else other than `entrySeq()`, but it's how I ran into it.

Code to duplicate the issue (using [mjackson/expect](https://github.com/mjackson/expect)):

``` javascript
var arr = [
  {key:'a'}
];

var a1 = Immutable.fromJS(arr).toJS();

expect(a1[0]).toEqual({key:'a'}); // this passes

var entries = Immutable.fromJS(arr).entrySeq().toJS();

// entries[0] should be: [0, {key:'a'}]
expect(entries[0]).toBeA(Array); // this passes
expect(entries[0][0]).toEqual(0); // this passes
expect(entries[0][1]).toEqual({key:'a'}); // this fails, it's still an instance of Immutable.Map
```

[JSBin demo](https://jsbin.com/siwadi/edit?html,js,console,output)

**Comment by myme** [comment]
I just ran into a similar issue with `.toList().toJS()`.

```javascript
const list = Immutable
  .fromJS({ a: true, b: [1, 2] })
  .map((value, key) => ({ value, key }))
  .toList()
  .toJS();
```

Expected list to deep equal:

```javascript
[{ key: a, value: true}, { key: b, value: [1, 2] }]
```

Actual:

```javascript
[{ key: a, value: true}, { key: b, value: List(...) }]
// list[1].value is still an instance of Immutable.List
```

**Comment by myme** [comment]
Never mind me. The reason my example fails is because of the `.map(...)` return value, which is a plain JS object. When `.toJS()` encounters this it does not recurse further.

**Comment by sabahang** [comment]
@myme according to docs `.map(...)` actually returns another Iterable. I'm having a similar issue and I'm using map

**Comment by myme** [comment]
@sabahang If you have a look at the return value of the `.map()` callback, you see that in my example it's returning a plain JS object, not an Immutable structure. When `.toJS()` encounters non-Immutable structures it stops recursing into the plain JS objects.

So instead of `.map((value, key) => ({ value, key }))` if you return e.g. `fromJS()` from the mapper function: `.map((value, key) => fromJS({ value, key }))`. A fairly easy gotcha to trip you up, but it makes perfect sense.
