### ISSUE TITLE
why would getIn return the key rather than the value

### ISSUE THREAD

**Issue by Kielan** [facebook/immutable-js#809]
let isAuthorized = basicStore.getState().getIn('auth', 'username')

I want to access the value of a redux store outside of a react component, specifically in routes to validate an onEnter check. 

for some reason isAuthorized returns the key of the store rather than the value, so I am unable to check if false, true, or null.

**Comment by samwgoldman** [comment]
http://facebook.github.io/immutable-js/docs/#/Iterable/getIn

`getIn` takes two arguments, an iterable of keys and a default value. I suspect you meant `getIn(['auth', 'username'])`. You've provided `'username'` as a default value. If you got that value back, it's because `auth` was not found (or had the value `'username'` for some reason).

**Comment by Kielan** [comment]
Ah I'm blind. thanks so much.
