### ISSUE TITLE
Arrays in Sets vs Lists

### ISSUE THREAD

**Issue by alkhoo** [facebook/immutable-js#810]
Updated:

```
Immutable.Set.of("a","b","c").first() => a // OK
Immutable.Set.of(["a"],["b"],["c"]).get(1) => undefined  // expecting ["a"]

Immutable.Set.of("a","b","c").get("a") => "a" // 
Immutable.Set.of(["a"],["b"],["c"]).get(["a"]) => undefined

Immutable.List.of("a","b","c").get(1) => "b" // OK
Immutable.List.of(["a"],["b"],["c"]).get(1) => ["b"] // OK
```

Why does `Set.of(["a"],["b"],["c"]).get(1)` fails?
And `Set.of(["a"],["b"],["c"]).get(["a"])` fails too?

Question from: http://stackoverflow.com/questions/36098807/accessing-immutablejs-orderedset - was trying to access 2nd element in OrderedSet.

**Comment by shri3k** [comment]
Take this with a grain of salt since I'm new to `ImmutableJS` and `ES6/2015` but `Set` and `List` are two different data types which behave differently. From quick glance at `List` from the doc, it's supposed to be much like Arrays and extends from `Collection.Index` while `Set` is a different data type which extends from `Collection.Set`. That should answer why you get `undefined` when you try `get(1)` in `Set` but what I'm a little confused on is why `get` even works with `Set` in the first place when it's not even available in ES6/2015. 
On, `Immutable.Set.of(["a"],["b"],["c"]).get(["a"])`, if you want to check the value then you can do

```js
var x = Immutable.Set.of(["a"],["b"],["c"]);
var y = x.values();
y.next().value;
y.next().value; //at index 1
```
But as you stated you don't want to iterate over the `Iterables` I suppose you can do :- 

```js
var x = Immutable.Set.of(["a"],["b"],["c"]);
var vals = [...x]
vals[1]
```
But I don't know if you're taking advantage of `Immutable` by doing this.
Again, I'm new to this so feel free to correct me on anything that I've said here is blatantly wrong.

**Comment by alkhoo** [comment]
There is no _wrong_ or _right_ just little quirks in `Immutable` which hopefully will be resolved through discussion and better understanding. 

It is like saying when I'm in this room `List`, I scratch my nose the usual way but if I walk into next room `Set` with same items, the usual method will fail. Even Sets of arrays will behave differently from Set of strings.

To summarize, `Immutable` has:-
**Sets** — Unordered collections of unique elements, use interable to access
**OrderedSet** — Ordered collections of unique elements, use interable to access (no direct access). 
**Lists** — Ordered collections of elements, direct access.

Note: My original question was why OrderedSet can't be accessed directly since it is similar to a list, only with duplicate checking.
