### ISSUE TITLE
groupBy fails when using objects or list, but works fine with Immutable List / Map

### ISSUE THREAD

**Issue by jdeniau** [facebook/immutable-js#816]
The result of `groupBy` is strange and I think wrong when your `groupBy` key is an array or an object.
I found #325 but it seems thats it's more than that when you have non-empty objects / arrays.

Here the jsfiddle exemple: https://jsfiddle.net/bLr50640/3/

Thank you !

**Comment by leebyron** [comment]
Could you provide more information? What did you expect? By looking at your example, all output appears correct.

**Comment by jdeniau** [comment]
The wrong results are l.11 and l.16.

The `size` result is wrong.

If you run then `result.forEach((v, k) => { console.log(k, v); })`, you have the following output :
```js
Object {a: "1", b: "1"} Wt {size: 1, _origin: 0, _capacity: 1, _level: 5, _root: null…}
Object {a: "1", b: "2"} Wt {size: 1, _origin: 0, _capacity: 1, _level: 5, _root: null…}
Object {a: "1", b: "2"} Wt {size: 1, _origin: 0, _capacity: 1, _level: 5, _root: null…}
```
with the same keys on the second and third iteration instead of 
```js
Object {a: "1", b: "1"} Wt {size: 1, _origin: 0, _capacity: 1, _level: 5, _root: null…}
Object {a: "1", b: "2"} Wt {size: 2, _origin: 0, _capacity: 2(?), _level: 5, _root: null…}
```

**Comment by leebyron** [comment]
groupBy uses equality checking to determine groups. Unfortunately JS arrays and objects are mutable collections that use reference equality.

A good way to remember this is:

```js
[] !== [] // true
{} !== {} // true
```

That means returning arrays or objects from groupBy will create a new group for every return value.

This is tricky to coerce since JS primitives are often used as opaque identifiers in many apps.
