### ISSUE TITLE
Add Class type (i.e. a Record but no default values)

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/immutable-js#839]
I want an immutable object with typed properties (TypeScript). I want something like a Record, but without default values.

In Scala we have case classes that do this. Would it be possible to add this type to immutable-js?

**Comment by myitcv** [comment]
@OliverJAsh is this in TypeScript?

Did [this comment](https://github.com/facebook/immutable-js/issues/341#issuecomment-177268163) not work out for you?

**Comment by OliverJAsh** [comment]
Yes, it is in TypeScript. Thanks for the link, I'm trying to make sense of it all but a lot of it is going over my head. Seems like it should be simpler?

**Comment by leebyron** [comment]
Unfortunately I don't think this is possible, as what you're asking for is syntactic rather than library code.

A default value must *always* exist, because you can always do `myRecord.myField` and it must return *something*, even if that something is undefined. For example, this is totally fine:

`MyRecordType = Record({
  myField1: undefined,
  myField2: undefined
})`

**Comment by leebyron** [comment]
We have a slightly nicer syntax coming in a future version that lets you provide coercion functions rather than just default values:

https://github.com/facebook/immutable-js/commit/44b20e4168613a7d28920495115a741b20fef2b4

**Comment by myitcv** [comment]
@OliverJAsh the immutable aspect you require does not _require_ ImmutableJS. You can use the type checking of TypeScript to achieve the same thing (indeed there is a performance benefit to doing so).

Consider:

```ts
class A1 {
	private name: string;
	private age: number;
	private hobbies: Immutable.Set<string>;

	constructor() {
		// could set defaults here... or take parameters
		// to assign
	}

	Name(): string {
		return this.name;
	}

	SetName(v: string): A1 {
		if(v === this.name) {
			return this;
		}
		let res = this.dup();
		res.name = v;
		return res;
	}

	Age(): number {
		return this.age;
	}

	SetAge(v: number): A1 {
		if(v === this.age) {
			return this;
		}
		let res = this.dup();
		res.age = v;
		return res;
	}

	Hobbies(): Immutable.Set<string> {
		return this.hobbies;
	}

	SetHobbies(v: Immutable.Set<string>): A1 {
		if(v === this.hobbies) {
			return this;
		}
		let res = this.dup();
		res.hobbies = v;
		return res;
	}

	private dup(): A1 {
		let res = new A1();
		res.hobbies = this.hobbies;
		res.age = this.age;
		res.name = this.name;
		return res;
	}
}

let x1 = new A1();
let x2 = x1.SetName("Paul");

console.log(x1 === x2); // false
console.log(x1.Name()); // undefined
console.log(x2.Name()); // "Paul"
```

Here the model class `A1` is "immutable" in a roughly equivalent sense to the API exposed by containers etc in ImmutableJS.

You will notice the primitive properties (`string`, `number`) can be typed as such because a string value is immutable. `Array`, `Object` etc are mutable, hence you must use an ImmutableJS container for the types of such properties (e.g. `Hobbies`).

If you are using the latest [`nightly`](https://github.com/Microsoft/TypeScript/wiki/Nightly-drops) version of TypeScript you can avoid methods for the getters and do the following:

```ts
class A1 {
	private name: string;
	private age: number;
	private hobbies: Immutable.Set<string>;

	constructor() {
		// could set defaults here... or take parameters
		// to assign
	}

	get Name(): string { // getter
		return this.name;
	}

	SetName(v: string): A1 { 
		if(v === this.name) {
			return this;
		}
		let res = this.dup();
		res.name = v;
		return res;
	}

	get Age(): number { // getter
		return this.age;
	}

	SetAge(v: number): A1 {
		if(v === this.age) {
			return this;
		}
		let res = this.dup();
		res.age = v;
		return res;
	}

	get Hobbies(): Immutable.Set<string> { // getter
		return this.hobbies;
	}

	SetHobbies(v: Immutable.Set<string>): A1 {
		if(v === this.hobbies) {
			return this;
		}
		let res = this.dup();
		res.hobbies = v;
		return res;
	}

	private dup(): A1 {
		let res = new A1();
		res.hobbies = this.hobbies;
		res.age = this.age;
		res.name = this.name;
		return res;
	}
}

let x1 = new A1();
let x2 = x1.SetName("Paul");

console.log(x1 === x2); // false
console.log(x1.Name); // undefined
console.log(x2.Name); // "Paul"
```

**Comment by coodoo** [comment]
@leebyron Is there any reason why `44b20e4` hasn't landed yet?

**Comment by cameron-martin** [comment]
The constructor could error if not given all the specified parameters. Then if you don't have a `remove` method, only `set`, then no default values are needed to fall back on.
