### ISSUE TITLE
TypeScript type safety for toJS()

### ISSUE THREAD

**Issue by mmorearty** [facebook/immutable-js#859]
When using ImmutableJS with TypeScript, it would be nice to have better type safety for the return value of `toJS()`.

`toJS()` is defined like this in `interface Iterable`:

``` typescript
/**
 * Deeply converts this Iterable to equivalent JS.
 *
 * `Iterable.Indexeds`, and `Iterable.Sets` become Arrays, while
 * `Iterable.Keyeds` become Objects.
 *
 * @alias toJSON
 */
toJS(): any;
```

I think it should be possible to redeclare `toJS()` with the appropriate, more specific type (using covariance) in `Iterable.Indexeds`, `Iterable.Sets`, and `Iterable.Keyeds`. E.g. in `Indexed` and `Set`, I think the declaration would be:

```
toJS(): T[];
```

And in `Keyed`, I think it would be:

```
toJS(): { [key: K]: V };
```

**Comment by myitcv** [comment]
@mmorearty interesting suggestion although there are plenty of edge cases that might make this tricky (what key type results when you convert an Immutable JS map which has a complex key type?)

The following however:

```ts
toJS(): T[];
```

does not work because `toJS` is not defined as a generic method in your definition. If `T` is instead a reference to the type of the contained type, then this also will not be correct because `toJS` is a deep conversion.

Instead I would propose something like:

```ts
// Iterable.Indexeds, and Iterable.Sets
toJS(): {}[];
```

But at a minimum it's unsafe for `toJS()` to be declared of type `any` - it should be:

```ts
toJS(): {};
```

(which forces people to assert the resulting type)
