### ISSUE TITLE
The iterable parameter of the map function of the Stack is reversed 

### ISSUE THREAD

**Issue by josepot** [facebook/immutable-js#869]
I'm not sure if this is a bug or if it is the intentional behaviour, but I think that if this is the intentional behaviour it should be noted in [the documentation of the map method of the Stack](https://facebook.github.io/immutable-js/docs/#/Stack/map).

I find it odd that the iterator of the `map` function of the `Stack` is reversed. For example, I would expect the result of the following instructions to be equivalent:

```
Stack.of('a','b','c').map(
  (x, idx, iterable)=> iterable.get(idx) + (iterable.get(idx + 1) || '')
).toArray();
// Returns: ['a', 'ba', 'cb']

Stack.of('a','b','c').toArray().map(
  (x, idx, array)=> array[idx] + (array[idx + 1] || '')
);
// Returns: ['ab', 'bc', 'c']
```

**Comment by leebyron** [comment]
It's partly a bug, and partly intentional!

After some investigation:

It's intentional that `map` is called in reverse order to preserve the order of the ultimate Stack - that is Stacks are constructed "bottom up" and because `map()` uses a prior Stack to create the new one - the initial Stack is iterated in reverse order to create the new one.

However the bug is that idx is not correct for the reversed values. fix incoming

**Comment by leebyron** [comment]
Just some debugging knowledge dump before I leave this for the night. This might be a larger issue than just Stack and map, but perhaps any Seq that has been reversed *after* mapped (or filtered, or anything else) the prior operations may then get reversed indices.

I think fixing this may require a deeper refactor of how sequence reversal works at the moment.

```
> Stack('abc')
Stack [ "a", "b", "c" ]
> s = Stack('abc')
Stack [ "a", "b", "c" ]
> m = s.toSeq().map((v, i, c) => v + i + c.get(i))
Seq [ "a0a", "b1b", "c2c" ]
> Stack(m)
Stack [ "a2c", "b1b", "c0a" ]
> km = m.toKeyedSeq()
Seq { 0: "a0a", 1: "b1b", 2: "c2c" }
> Stack(km)
Stack [ 0,a2c, 1,b1b, 2,c0a ]
>
```
