### ISSUE TITLE
Feature Request: Immutable Priority Queue.

### ISSUE THREAD

**Issue by jckdrpr** [facebook/immutable-js#872]
How about an immutable implementation of the Priority Queue data structure might come in handy for  some people.

I tried to do a heap based implementation using the Immutable List but I got O((logn)^2) (well ~c_log_2(n)_log_32(n)) bound for pop and push. Surely there should be a better way of doing it.
Something based on the binomial heap.

Interested in what is others think of this?

**Comment by leebyron** [comment]
Closing this aging issue - there's no plans to add this to the library, however if you ever feel up for a serious contribution, I'd love to see your research into how to accomplish this.

**Comment by awaidmann** [comment]
@leebyron 

I have been working on a prototype for an immutable Heap/Priority Queue implementation. Before I go too far down the rabbit hole I would like your input.

First off, there are two possible access paradigms that we must consider. The first being strictly a Heap structure which resembles the Stack in it's basic operations: `peek()`, `push(priority, item)`, and `pop()`. The second (and more useful) option would be to combine some Map functionality, namely keyed entries, with the basic Stack operations to support `get(key, nsv)`, `update(key, nsv, fn)` and related operations on both the entry itself AND the associated priority. I have chosen to pursue the more complicated second option, as it more fully captures my needs (namely updating existing priorities) and what I believe the community needs/expects.

### Goals
Explicit functionality and performance goals:

- O(1) `peek()`, `first()`, and/or `head()`
- O(log32(N)) `pop()`
- O(log32(N)) `get*(key)`, `set*(key, [priority, value])`. Same big-O bounds as Map. For `set*(...)` a change to value can be done without changing the nodes' internal ordering, but a priority change will require the use of internal siftUp/Down operations.
- O(N) for each collection in `merge*(...collections)`. Same big-O bounds as Map (I assume as it isn't explicitly stated in the docs).
- O(TBD) iteration, we get most sequence and search operations for free once an iterator and iteration scheme is defined. This will depend on whether iteration should maintain heap ordering or first-come-first-serve ordering. I look forward to discussion on this issue.

> Note: There have been [previous efforts](http://www.brics.dk/RS/96/37/BRICS-RS-96-37.pdf) to create purely functional heap/priority queue implementations. However, they do not address efficient lookups of existing elements in the heap for updating purposes. Likewise, other more advanced heaps like the [Fibonacci heap](https://en.wikipedia.org/wiki/Fibonacci_heap) are not applicable because they require a pointer back to the parent, violating the acyclic requirement of a Directed Acyclic Graph (DAG) which underlies all of Immutable-js. Nevertheless, I have used ideas from theses sources, such as structural bootstrapping and tree decomposition, to inform/inspire my prototype.

### Implementation

#### Node Types
The proposed Heap would be comprised of 3 node types (names are negotiable):
1. `ValueNode`: Leaf node containing key, keyHash, priority, and value properties.
2. `HashCollisionNode`: Modified leaf node containing `[k, [p, v]]` entries that have identical keyHashes (similar to the [`Map.HashCollisionNode`](https://github.com/facebook/immutable-js/blob/master/src/Map.js#L484)). Entries are stored in an binary heap ordered array rather than by insertion order. Array size is unbounded as we cannot know a priori the number of hash collisions. This node's priority and value are set as the current first entry's priority and value, so as to provide efficient lookups.
3. `HashBucketNode`: Non-leaf node containing pointers to child nodes of any type. It is comprised of depth/shift integer and two identically sized arrays each with a max size of [TrieUtils.SIZE](https://github.com/facebook/immutable-js/blob/master/src/TrieUtils.js#L15). The first array is the subqueue array which is a binary heap array, ordered on node priority. The second is the hash redirect array where each slot corresponds to a secondary hash (more on this below) on the child node's keyHash and each value is that node's index in the subqueue array. A slot is initially empty, then is filled with a ValueNode, and if another node maps to that slot then a new HashBucketNode is created as the new child with both ValueNodes in the new child HashBucketNode. The depth/shift property is incremented for each child HashBucketNode and serves as a way to prevent child keyHashes from mapping to the same location at every depth. Like the HashCollisionNode, this node's priority and value are set as the current first node's priority and value.

#### Hash Redirect Slot Hashing
A HashBucketNode's hash redirect array has a max size of [`TrieUtils.SIZE`](https://github.com/facebook/immutable-js/blob/master/src/TrieUtils.js#L15) and maps a particular range of keyHashes to a heap subtree or leaf. An incrementing depth/shift value is provided for each child HashBucketNode, starting at 0. The proposed equation is below:
```javascript
function rotatorHash(shift, keyHash) {
  const truncatedHash = keyHash & 0xFFFFFFFF;
  return Math.abs((truncatedHash << shift) | (truncatedHash >>> -shift)) % SIZE;
}
```
In Javascript bitwise operations are limited to 32 bits even if a number is actually represented with more. This can result in some odd behavior for numbers > 32 bits, hence the mask/truncation operation. Effectively all the bits shifted off the end are shifted back on to the front of the hash, then the whole value is modulo'd with the `TrieUtils.SIZE` to ensure it maps only to the specified range of buckets.

The "rotation" method was chosen as it maintains a uniform modulo distribution at deeper levels of the tree. For example, if a simple left shift was performed at the 31st level, all values would begin with either a 0 or 1 and hence would only map to one of two buckets, artificially limiting our bucket space. Like all shift based hashes, this effectively limits the tree depth to 32 levels with deeper levels becoming degenerate cases with only one usable slot. And while 32^32 is quite a large size, the keyHashing method is open sourced and there are pathological cases where an attacker could force all keys into a single bucket and force a depth > 32 levels.

If anyone has a better suggestion I would love to hear it, but keep in mind that whatever the scheme is, it will need to be deterministic for a particular depth or parent slot due to the proposed implementation of the `merge*(...)` functions (see below).

#### Methods
I believe these to be the basic operations that underpin all other immutable-js operations (please let me know if I missed anything). Below is rough pseudo code on how to implement these operations:

##### peek()/first()/head()
return `[root.priority, root.value]`.
If root is a ValueNode the priority and value correspond to it's own properties. If either a HashBucketNode or a HashCollisionNode, the root's priority and value are the priority and value of the head node which corresponds to the node with the min/max priority. On every modification, the priority and value are reset on all affected composite nodes, if necessary.

##### pop()
```
1. Start at root
2a. If HashBucketNode: recurse on subqueue[0], goto step 2*.
2b. If HashCollisionNode or ValueNode: end recursion, goto step 3*.
3a. If HashCollisionNode: copy node, in copy: set entries[0] to entries.last, delete entries.last, heapify (binary heap siftDown operation), return copy or undefined if entries.length === 0, goto step 4.
3b. If ValueNode: return undefined.
4. Will always be a HashBucketNode:
  - If return value === undefined: set subqueue[0] to subqueue.last, delete subqueue.last, heapify subqueue and update hash redirect array accordingly, return copy or undefined if subqueue.length === 0.
  - If return value is node: set subqueue[0] to returned node, heapify subqueue and update hash redirect array accordingly, return copy or undefined if subqueue.length === 0.
  Repeat until back at root.
5. Set root to final returned node and return new Heap instance.
```

##### get*(key, notSetValue)
```
1. Start at root
2a. If HashBucketNode:
  - if this.hashRedirect[rotatorHash(this.depth, key)] !== undefined recurse on this.subqueue[this.hashRedirect(this.depth, key)], goto step 2*.
  - else return notSetValue
2b. If HashCollisionNode: perform linear search through entries
  - if entries has entry with matching key: return entry[1], i.e. [priority, value] of [key, [priority, value]]
  - if no matching key: return notSetValue
2c. If ValueNode:
  - if key matches this.key: return [this.priority, this.value]
  - else return notSetValue
```

##### set*(key, [priority, value])
doubles as `remove*(key)`
```
1. Start at root and compute keyHash
2a. If HashBucketNode:
  - if this.hashRedirect[rotatorHash(this.depth, keyHash)] !== undefined recurse on this.subqueue[this.hashRedirect(this.depth, keyHash)], goto step 2*.
  - if [p, v] !== undefined: copy, create new ValueNode, insert new node at end of subqueue, heapify (siftUp), update hashRedirect accordingly, return copy, goto step 3.
  - else (![p, v]): return this (unmodified), goto step 3.
2b. If HashCollisionNode: perform linear search through entries
  - if entries has entry with matching key:
    - if [p, v] !== undefined: copy this, in copy: update priority and value as necessary, if priority changed remove previous entry, replace with last element and siftDown, then insert new entry at end and siftUp, return copy
  - else: copy this, in copy: remove previous entry, replace with last element, and siftDown, return copy, goto step 3.
  - if no matching key:
    - if [p, v] !== undefined:  copy this, in copy: create new entry, push to end and heapify (siftUp), return copy, goto step 3.
    - else: return this (unmodified)
2c. If ValueNode:
  - if key doesn't match this.key and [p,v] === undefined: return this (unmodified), goto step 3.
  - if key matches this.key: return copy of this, goto step 3.
  - if keyHash matches this.keyHash: create new HashCollisionNode with [this.key, [this.priority, this.value]] and supplied parameters [key, [priority, value]], return new node, goto step 3.
  - else: create new HashBucketNode and new ValueNode with supplied parameters. Pass new ValueNode and this to HashBucketNode, return new HashBucketNode, goto step 3.
3. Will always be HashBucketNode:
  - if returned node === recursed node: return this (unmodified).
  - if returned node !== undefined: copy this, in copy: remove previous/recursed node from subqueue, put subqueue.last in removed location and siftDown, insert returned node at tail and siftUp, update hashRedirect accordingly, return copy.
  - else: remove previous/recursed node from subqueue, put subqueue.last in removed location and siftDown, update hashRedirect accordingly, return copy.
  Repeat until back at root.
4. Set root to final returned node and return new Heap instance.
```

##### merge*(...collections)
I will be a little bit more vague on this method as I haven't developed a prototype implementation yet. For each collection in collections, we need to recursively merge the HashBucketNodes at each level. If both nodes at the same level with the same parent keyHash slot are HashBucketNodes, then for every keyHash slot which exists in one node and not the other we can insert the a reference to the node/subtree as is. For every keyHash slot which exists in both we will need to recurse on those nodes. This is where the deterministic depth based rotator hash comes into play. We know that the slot hashing scheme is consistent across all nodes at a particular depth and so we can insert/combine nodes at the same level without introducing inconsistencies into our slots. If the two nodes are both HashCollisionNodes with the same keyHash, then insert the node with the fewer elements into a copy of the one with the greater number and heapify. If they have different keyHashes then insert references to them into a new HashBucketNode. If they are both ValueNodes with matching keys, then return a reference to the other node. If their keys don't match insert references to them into a new HashBucketNode. If one node is a HashBucketNode and the other is a HashCollisionNode or ValueNode, then recursively merge those nodes into the appropriate keyHash slot of a copy of the HashBucketNode. And if one node is a HashCollisionNode and the other is a ValueNode with matching keyHashes, construct a new entry from the ValueNode and insert into a copy of the HashCollisionNode. If their keyHashes don't match, create a new parent HashBucketNode for them. Upon returning from a child node, the calling HashBucketNode should heapify it's subqueue and hashRedirect accordingly. If there is a more efficient batch heapify function please let me know.

##### Iteration
TBD. If first-come-first-serve a simple DFS would suffice to iterate over all [key, [priority, value]] entries. If heap/priority based will require some level of virtual popping or actual popping and reordering (which would be O(N*log32(N)), which is not ideal).

**Comment by awaidmann** [comment]
I know this is very long and dense. Over the next few days I will be working to clean up the language a bit and to provide clarifying pictures.

Please let me know if there is anything that needs further explanation and I'll take care of that first.

**Comment by hedgepigdaniel** [comment]
so.... what happened here?

**Comment by tanduong** [comment]
How did it go...

**Comment by awaidmann** [comment]
Sorry, everyone. I will be working on it again in the next couple weeks. I was working on it for a project, but then switched to using Scala/Akka for scalability reasons.
