### ISSUE TITLE
Inconsistent documentation of withMutations

### ISSUE THREAD

**Issue by louisremi** [facebook/immutable-js#890]
Hi,

I was looking for info about batching mutations in Immutable.js and found inconsistent info about the methods that can be used inside a `withMutations` call:
- on the landing page, the [part about batching](https://facebook.github.io/immutable-js/#batching-mutations) states that "_Only a select few methods can be used in withMutations including set, push and pop._"
- in the docs, the [part about withMutations](http://facebook.github.io/immutable-js/docs/#/Map/withMutations) states that "_Only set and merge may be used mutatively._"

My hope is that all of `set`, `push`, `pop` and `merge` can be used in withMutations, but also `shift`, `unshift`, `insert` and `delete`.  I believe there should be a documented list of methods that are unit-tested to be compatible with `withMutations`.

**Comment by vinnymac** [comment]
This issue is related to #721, #663, #228 and #196. `withMutations` has plenty of undocumented features and methods. The documentation that does exist is meant to be the recommended usage in its current state. I think as certain methods are tested and have more support, the documentation will improve. For example `remove` currently works well with `Map` but not with `List`.

Maybe in the meantime someone will put together a pull request with improved documentation based on all this information.
