### ISSUE TITLE
More examples in the docs

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/immutable-js#905]
This is rather easy question. Would it be good  to have more examples in the docs? ( More JS examples)

**Comment by mozgeek** [comment]
100% agree. The Doc is bad and it doesn't helpful mostly.

**Comment by Strajk** [comment]
References:

**Comment by kingjerod** [comment]
I agree, the lack of examples in the documentation makes it really hard to use this library. Considering this is replacing basic JS data structures, it should be rather easy to make examples.

**Comment by lacker** [comment]
I agree, the docs would be better with some examples, like an "intro" or "tutorial" type thing. That said, I am going to close this issue because we are trying to keep the issues focused on bug reports. My goal here FWIW is to first clean up the outstanding issues & pull requests and then look at some stuff like improved docs, so I am hoping to fix some of this up. And pull requests to improve the docs are welcome too ;-)
