### ISSUE TITLE
Updating state in Redux, merge or update?

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/immutable-js#906]
I just started working in Immutable, and I've hit some cornerstones. I'm insecure about several things, and I hope that you'll help out with me figuring out how it works :) ( I've also asked on SO, but people doesn't answer seriously ) 

1. To update state in Redux with Immutable, do I call `state.merge(something)` or `state.update(...)`
2. When structuring my changed values, what is the best way to do that? I most certainly know that I have done something and most likely everything wrong, so I hope that you will correct me on this. 
3. How do I call `update` /  `updateIn` on flat objects? 

Thanks for helping me out! Here's the sc.

<img width="738" alt="skjermbilde 2016-06-28 kl 11 17 21" src="https://cloud.githubusercontent.com/assets/16735925/16410382/8bc81626-3d22-11e6-962b-6b3592237c2d.png">

**Comment by AugustinLF** [comment]
I always use update/set, to modify exclusively the portion of the state that needs to be modified. In your  example, you don't show how your previous state looks like, so I'm not sure what is the best here :/

**Comment by ev1stensberg** [comment]
Previous state is empty, it gets populated by a payload in the first reducer, if I have got the concept right :) @AugustinLF

**Comment by AugustinLF** [comment]
If the state is empty, then it doesn't matter, you can even directly `return updatedState`. But this think work only if the content of the state doesn't have any influence on the updatedState

**Comment by ev1stensberg** [comment]
Updated state is the new state @AugustinLF , you can´t set it directly

**Comment by AugustinLF** [comment]
No but you can just return it. a reducer is a `(state, action) => newState` function. `Map().merge(fromJS({a: true}))` is shallow equal to fromJS({a: true}). So in your case, you can simply do (since state is an empty Map):
```
case POPULATE:
  let updatedState = fromJS({data: action.payload.meetingNote});
  return updatedState;
```

**Comment by leebyron** [comment]
> To update state in Redux with Immutable, do I call state.merge(something) or state.update(...)

Both of these will return a new version of your state with a change applied. They just do different kinds of changes. Merge looks fine as you're using it now. There's a good parallel here to Arrays. push(), shift(), and map() are all about changing things, but they do different things. One isn't superior to the other. 

> When structuring my changed values, what is the best way to do that? I most certainly know that I have done something and most likely everything wrong, so I hope that you will correct me on this.

I think you're over thinking this. There's basically no wrong way to structure your data. It's your data. Structure it however you like that works for your app.

> How do I call update / updateIn on flat objects?

Could you clarify what a flat object is?

**Comment by leebyron** [comment]
One thing I noticed is that your function says it will accept Map as state and action, but you're using property accessors like `state.data` or `action.type`. Immutable Maps are not like JS Objects, they're like ES6 Maps. They don't have properties but instead have a get() method.

**Comment by ev1stensberg** [comment]
@AugustinLF  @leebyron  thanks! Flat object would be like this:

```js
updatedState: {
        data: someval,
        more: false,
        less: ...
}
```

**Comment by ev1stensberg** [comment]
Okay, so here's how it looks now. Is there any optimizations needed to be picky now? Also, I really want to have each action return the state & not `updatedState`. Do I use `state.set(updatedState)` on all my reducers or do I use `updateIn` or similar? I'm adding a optional question at the end here, asking the following: I'm unsure about updating multiple values through `update`, how do I do that?
<img width="811" alt="skjermbilde 2016-06-29 kl 07 24 13" src="https://cloud.githubusercontent.com/assets/16735925/16441418/9d6602f0-3dca-11e6-85b8-2b0911bbfdd8.png">

**Comment by leebyron** [comment]
I'm not sure this code does what you think it does. Does it work?

I think you may be misunderstanding some fundamental concepts here. I definitely recommend backing up and getting a better grasp on what it is you're trying to accomplish without additional tools like redux and immutable or babel/es6 and only including these when they help you accomplish something in a better way.

To start, I suggest reading more about redux and reducers. Typically the goal or a reducer function is to accept an older version of something and one other value and then return a newer version of that same thing by using the value. When called multiple times with each new value becoming the "older version" with each subsequent call to the function, you can model change over time via the sequence of events. Immutability is a fundamental aspect to how a reducer function should work (not specific to JavaScript, the concept exists in most languages) but you don't need a special library to use immutability. Simply don't edit the "older version" and instead always create a new copy with your change applied. Redux is really just about popularizing this existing concept of reducers to UI programming. The "thing" being updated over time we call "state" and the value used to update it is the "action". You can see that in your latest version of your code, you're not using the previous state at all to produce the new returned state, that's definitely a big red-flag that your reducer isn't doing what you want it to do. 

Next, the ES6 features enabled with Babel being used here represent the "default values" for arguments, or what value to use if one is not passed to your function. In a reducer the second argument "action" is always provided, so the default value there isn't doing anything valuable. It's probably just distracting from how the reducer works. The first argument "state" is only not provided for the very first time the reducer is called in the case that you're not providing an initial state. If your redux setup has an initial state then you don't need that either. If it doesn't, then here's where that initial state can be defined. An empty Map is very likely not what you are expecting to be your initial state. So it's either distracting from what's really going on, or your probably have a bug there, depending on if you're providing your initial state to redux or not.

then there's immutable.js. I would strongly suggest familiarizing yourself with the concepts of immutability without using this library first just by using plain old JavaScript objects at first. Actually in your case it looks like your state is quite simple so you're probably not gaining much by using immutable.js anyhow. Since plain JS objects are much simpler, hopefully this can help you better visualize what's going on. You can return new versions of your state using Object.assign like this:

var newState = Object.assign({}, prevState, { keyToChange: newValueToUse })

I'm sure you can find ample examples of this sort of thing in the redux documentation and explainers. 

Once you get a better grasp of using redux to build apps and things are working, come back to immutable.js as you need to model more complex state or state that has larger amounts of data in it. Immutable.js uses different kinds of data structures that help conserve memory and improve performance for those kinds of situations.

I'm going to close this issue since both the question in the title was answered in an earlier comment (both merge and update are useful for updating redux states, as are the many other methods immutable.js provides) and the discussion has mostly been focused on this one piece of code, which may be better handled by either working with some tutorials or asking on stack overflow.
