### ISSUE TITLE
Lists are immutable? Not too understand

### ISSUE THREAD

**Issue by ghost** [facebook/immutable-js#931]
```
var a = [
            {name: 'hehe'},
            {name: 'haha'}
        ]

var a1 = Immutable.List(a)
var a2 = Immutable.List(a)

console.log(Immutable.is(a1, a2))

a[0].name = "heihei"
console.log(a1.get(0)) // {name: "heihei"}
console.log(a2.get(0)) // {name: "heihei"}
```

'name' value : heihei

It looks like Array  :)

**Comment by pori** [comment]
This is a consequence of how Objects act as _references_ to values in JavaScript, rather than being values themselves. The same goes for arrays, since they're just a subset of Objects.

Consider this example:

```js
var array1 = [1, 2, 3]

function clone (array) {
  return array
}

var array2 = clone(array1)

array1.push(4)

console.log(array1) // => [1, 2, 3, 4]
console.log(array2) // => [1, 2, 3, 4] (!!!)

function mutate (array) {
  array.push(9001)
}

mutate(array2)

console.log(array1) // => [1, 2, 3, 4, 9001]
console.log(array2) // => [1, 2, 3, 4, 9001]
```
Immutable evidently takes the [reference of an array](https://github.com/facebook/immutable-js/blob/master/src/List.js#L25) rather than copying its individual values to a new structure. This may be to avoid an additional `O(n)` time when creating new Lists and such.

The example you provided seems like a misuse of the library, anyhow. Would defeat the purpose if you wanted an immutable List _and_ an array. Given that, I wouldn't call this a bug _per se_. It's more like settling with the realities of the language and trusting devs to use in the intended manner. 😺

**Comment by vdh** [comment]
@smilingxinyi 
The `List` is immutable, but the Object data you're storing inside it is not. Consider using `fromJS` to convert a deep structure into an immutable one, or manually building with `List`, `Map`, etc.

```js
var a1 = fromJS([{ name: 'hehe' }, { name: 'haha' }]);
var a2 = List([Map({ name: 'hehe' }), Map({ name: 'haha' })]);
// Both methods create the same structure
console.log(a1.toString()); // List [ Map { "name": "hehe" }, Map { "name": "haha" } ]
console.log(is(a1, a2)); // true

var a3 = a1.setIn([0, 'name'], 'heihei');
console.log(a3.toString()); // List [ Map { "name": "heihei" }, Map { "name": "haha" } ]
```
