### ISSUE TITLE
Add .length property for BC with array.

### ISSUE THREAD

**Issue by Strate** [facebook/immutable-js#944]
Could we add `.length` property to immutable structures, for ease migrate from arrays?

**Comment by kokokenada** [comment]
+1.  As well as migration convenience, it would allow for easier function overloads like:
````
  static indexOf(cards:List<Card>, cardToFind:Card):number
  static indexOf(cards:Card[], cardToFind:Card):number
  static indexOf(cards:any, cardToFind:Card):number {
    for (let i = 0; i<cards.length; i++) {
...
````

**Comment by leebyron** [comment]
The previous major version had `.length` but a very common problem was that other code would see the `.length` property and attempt to use Immutable collections as if they were arrays, however that does not work because `list[0]` syntax does not work on anything except arrays, with Lists you need `list.get(0)`. So the `.length` property was deprecated and removed, replaced with `.size` to remove confusion and mirror the same decision made for ES6 native `Map` and `Set`.
