### ISSUE TITLE
toJSON produces non-equal values

### ISSUE THREAD

**Issue by just-boris** [facebook/immutable-js#956]
Given the following code sample

``` js
const map = new Immutable.Map();
map.toJSON() === map.toJSON(); // returns false
```

`toJSON` returns new value every time, even though that's obvious that instance of _immutable_ map object should produce the same object every time.

I use `toJSON` call in my React+Redux application in the `connect` function to pass data from store to components and I see that non-equality of toJSON affects the performance of my app because it causes re-render even this was not necessary.

**Comment by Retsam** [comment]
The map is immutable, but the JS-object representation of it returned by `toJS/toJSON` is mutable, and so returning the same object every time wouldn't make sense.  If it did return the same object every time, then mutating the return value of one `toJSON` call would affect the result of all calls to `map.toJSON`, which is problematic:

   const map = new Immutable.Map({x: 1});
   const rawMap = map.toJSON();
   rawMap.x = 2;

   //This might be a completely different part of the source code
   console.log(map.x); //1
   console.log(map.toJSON().x); //2, this is rather unexpected

---

Rather than trying to insist that a mutable JS object be treated as immutable, perhaps instead you should use some form of memoization?  [reselect](https://github.com/reactjs/reselect) is a pretty standard choice for these sort of problems in Redux apps:

```
import { createSelector } from "reselect";

const mapSelector = (state) => state.map; //Or however your map is stored in your state

const mapJSONSelector = createSelector(
     mapSelector,
     (map) => map.toJSON()
);
```

Or even just a lodash memoized function: 

```
const getJSON = _.memoize(function (map) {
    return map.toJSON();
});
```

Either one of these will return the same JS object for a given Immutable map, as you want.

**Comment by just-boris** [comment]
@Retsam thank you for the idea of using reselect. That probably will work for me.

But still, I would like to consider adding this memoization directly into Immutable.js itself. I understand that output object can be changed by third-party code, but this is not an issue, because everybody can remove some properties on immutable instances as well:

```js
var map = new Immutable.Map({key: 'value'})
delete map._root
map.toJSON() // prints empty object
```

**Comment by Retsam** [comment]
The difference is that `delete map._root` (or equivalent) is pretty clearly "evil": you're digging into a library's internals and mucking around with undocumented properties.  It's expected that that can cause unexpected things to happen.

But in my above example, on the other hand, there's nothing "evil" going on at all.  The "problem" line is `rawMap.x = 2`, but this is just setting a property on a normal, mutable JS object: that's a perfectly normal JS operation, and there's no reason why it should be allowed to cause unexpected behavior elsewhere in the codebase.  

To add this sort of memoization into ImmutableJS would be to insist that everyone treat the output of `.toJSON` as if it were an immutable object, but it's not an immutable object.  Heck, I think one of the primary reasons why people `toJSON` is because they want a mutable version of their immutable data structure.

**Comment by kentor** [comment]
so why are you calling `toJSON()` in mapStateToProps instead of in `render()`?

**Comment by leebyron** [comment]
@Retsam thanks for the excellent answer

**Comment by a-x-** [comment]
Why you don't memoize toJSON?
You can use low memory consuble memoize-one, for example
