### ISSUE TITLE
Immutable is not defined on website (devTools console)

### ISSUE THREAD

**Issue by applebya** [facebook/immutable-js#971]
I usually use the Chrome devTools console on the ImmutableJS docs website as a sandbox for trying things out.

Recently, I've no longer been able to use it. See screencap below:

![screen shot 2016-09-05 at 2 45 41 pm](https://cloud.githubusercontent.com/assets/9222480/18257373/7ff8cefe-7377-11e6-88d9-a8cc77725467.png)

Seems the `Immutable` variable isn't exposed globally anymore.

PS. Love this framework, amazing work :)

**Comment by AugustinLF** [comment]
That's actually a (quite recent) devTools bug. See on the image below, the `chrome-extension://...` thing, it's because you're executing your code in the context of an extension. You need to switch back to `top`. At least, that how it went for me :)
![image](https://cloud.githubusercontent.com/assets/5271169/18264649/d7637f3c-7411-11e6-9e74-abe28f2b7aae.png)

**Comment by applebya** [comment]
Woa, super weird. Funny enough, this solves a related problem with NWjs recently updating Chromium - so thank you ++

Does this impact the extensions' functionality then? :|

**Comment by AugustinLF** [comment]
I don't think so, never had any problems, The problem is that you have to switch back to `top` all the time...

**Comment by dspoonia7** [comment]
Was working on a project and Immutable doesn't work in browser (chrome) console. If anyone has some way to get around this, that would be great! Thanks :)

![immutable-in-console](https://user-images.githubusercontent.com/8257269/28876032-5d5a0186-77b5-11e7-9cd9-62e088148adb.jpg)

**Comment by danschumann** [comment]
Something something
`  "chromium-args": "--mixed-content",`
something something...
solved my issue as it related to nw.js
