### ISSUE TITLE
`.flatten` behaves differently on a List of 1 Set vs a List of 2 Sets

### ISSUE THREAD

**Issue by fenduru** [facebook/immutable-js#974]
I'm not sure which is correct, but I don't think these snippets should behave differently. I was trying to flatten a List of Sets into a single Set.

```
Immutable.List([
  Immutable.Set([ 1 ])
])
.flatten()
.has(1) // false
```

```
Immutable.List([
  Immutable.Set([ 1 ]),
  Immutable.Set([ 2 ])
])
.flatten()
.has(1) // true
```

**Comment by leebyron** [comment]
Try `contains`. `has` looks for keys/indices while `contains` looks for values.

The first example correctly returns false because the flattened list has only one thing in it (index 0) so it does not have index 1. In the second example there are two things (index 0 and index 1) so it does have index 1.
