### ISSUE TITLE
Flow: OrderedMap is typed as a regular Map

### ISSUE THREAD

**Issue by rsolomon** [facebook/immutable-js#979]
### What happened

I'd like to ensure that an parameter passed to a function is of type `OrderedMap` and not just an ordinary `Map`. However, `OrderedMap` simply extends `Map`, and all of its member functions return type `Map`.
### How to reproduce

```
function mergeOrderedMaps<T, S>(
  map1: OrderedMap<T, S>,
  map2: OrderedMap<T, S>,
): OrderedMap<T, S> {
  return map1.merge(map2);
```

Result:

```
Map
This type is incompatible with
OrderedMap
```

**Comment by iansinnott** [comment]
I've ran into this one as well. The type in question seems to be:

https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L538

As @rsolomon stated `OrderedMap` extends `Map`. I'm not sure if there is an elegant way to extend `Map` in such a way that all its methods return an instance of `this` as opposed to `Map`. Otherwise maybe a duplication of the `Map` type is necessary with every occurance of `Map` replaced with `OrderedMap`.

I would be happy to PR this with a bit of guidance on how to best implement the types.

P.S. It should also be noted that `toOrderedMap` currently returns `Map` ([source](https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L63)).

**Comment by bgw** [comment]
@iansinnott I'm not sure how well it would work in Flow, but the typical solution to this kind of problem in Java is to use a recursive generic. For example, `Enum` is defined as:

```java
public abstract class Enum<E extends Enum<E>>
    implements Comparable<E>, Serializable
```

Then `Enum` can treat type `E` as the type of `this`. Subclasses of `Enum` can then pass themselves as a type parameter.

**Comment by stevenla** [comment]
My suspicion is this line here:
https://github.com/facebook/immutable-js/blob/master/type-definitions/immutable.js.flow#L473

`myOrderedMap.set()` returns a `Map` instead of an `OrderedMap`

**Comment by leebyron** [comment]
Fixed in master will release soon

**Comment by bent0b0x** [comment]
Is it possible to see in which release this is fixed? Thanks!
